/**
 * Sicoob / Bancoob (756) � CNAB 400 � Detalhe de Remessa (Registro Tipo 1)
 * Cooperativa de cr�dito, nosso n�mero 12 d�gitos (com DV).
 *
 * Fontes:
 * - Planilha oficial Sicoob (Layout_Cobranca_CNAB400 (1).xls, mai/2025)
 * - cnab_yaml (fonte original, concordante)
 * Particularidades do Sicoob:
 * - logradouro com 37 caracteres (n�o 40 como outros bancos)
 * - aceite usa d�gito ('0'/'1') em vez de letra ('N'/'A')
 * - vencimento aceita valores especiais: '888888'=� vista, '999999'=contra apresenta��o
 * - nosso_numero: zeros se emiss�o Sicoob, ou sequencial 10 d�gitos + DV m�dulo 11 se emiss�o cliente
 * - campo de moeda condicional (pos 193-205): se Real=valor IOF, se outra moeda=quantidade monet�ria
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  tipo_inscricao_beneficiario: {
    pos: [2, 3],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do benefici�rio: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao_beneficiario: {
    pos: [4, 17],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do benefici�rio',
    canonical: null,
  },
  prefixo_cooperativa: {
    pos: [18, 21],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo: {
    pos: [22, 22],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador do prefixo (ver planilha Contracapa)',
    canonical: null,
  },
  conta_corrente: {
    pos: [23, 30],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente (ver planilha Contracapa)',
    canonical: null,
  },
  dv_conta: {
    pos: [31, 31],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta (ver planilha Contracapa)',
    canonical: null,
  },
  numero_convenio_cobranca: {
    pos: [32, 37],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000000',
    description: 'N�mero do conv�nio de cobran�a',
    canonical: null,
  },
  numero_controle_participante: {
    pos: [38, 62],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de controle do participante (campo livre para o cliente)',
    canonical: null,
  },
  nosso_numero: {
    pos: [63, 74],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso n�mero: zeros se emiss�o Sicoob (comando 01), ou sequencial 10 d�gitos + DV m�dulo 11 se emiss�o cliente',
    canonical: 'nossoNumero',
  },
  numero_parcela: {
    pos: [75, 76],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '01',
    description: 'N�mero da parcela (01 se parcela �nica)',
    canonical: null,
  },
  grupo_valor: {
    pos: [77, 78],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Grupo de valor',
    canonical: null,
  },
  brancos_1: {
    pos: [79, 81],
    type: FieldType.ALFA,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  indicativo_mensagem_sacador: {
    pos: [82, 82],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indicativo de mensagem do sacador: branco=mensagem livre no campo observacoes_mensagem_ou_sacador_avalista, A=dados do sacador/avalista',
    canonical: null,
  },
  prefixo_titulo: {
    pos: [83, 85],
    type: FieldType.ALFA,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo do t�tulo (espa�os em branco)',
    canonical: null,
  },
  variacao_carteira: {
    pos: [86, 88],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000',
    description: 'Varia��o da carteira',
    canonical: null,
  },
  conta_caucao: {
    pos: [89, 89],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Conta cau��o',
    canonical: null,
  },
  numero_contrato_garantia: {
    pos: [90, 94],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00000',
    description: 'N�mero do contrato de garantia (00000 para carteira 1, ou n�mero sem DV para carteira 3)',
    canonical: null,
  },
  dv_contrato: {
    pos: [95, 95],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'D�gito verificador do contrato (0 para carteira 1, ou DV real para carteira 3)',
    canonical: null,
  },
  numero_bordero: {
    pos: [96, 101],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do border� (preencher se carteira 3)',
    canonical: null,
  },
  brancos_2: {
    pos: [102, 105],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  tipo_emissao: {
    pos: [106, 106],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de emiss�o: 1=Cooperativa, 2=Cliente',
    canonical: null,
  },
  carteira_modalidade: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Carteira/modalidade: 01=Simples Com Registro, 03=Garantida Caucionada',
    canonical: null,
  },
  comando_movimento: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de comando/movimento: 01=Entrada de T�tulos, 02=Solicita��o de Baixa, 04=Concess�o de Abatimento, 05=Cancelamento de Abatimento, 06=Prorroga��o de Vencimento, 08=Altera��o de Seu N�mero, 09=Instru��o para Protestar, 10=Desist�ncia do Protesto e Baixar T�tulo, 11=Instru��o para Dispensar Juros, 12=Altera��o de Pagador, 31=Altera��o de Outros Dados, 34=Baixa - Pagamento Direto ao Benefici�rio',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do documento (seu n�mero)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento (DDMMAA, ou 888888=� vista, ou 999999=contra apresenta��o)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do t�tulo (2 decimais impl�citas)',
    canonical: 'valor',
  },
  numero_banco: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '756',
    description: 'N�mero do banco (756)',
    canonical: null,
  },
  prefixo_cooperativa_cobradora: {
    pos: [143, 146],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa cobradora (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo_cobradora: {
    pos: [147, 147],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador do prefixo da cobradora (ver planilha Contracapa)',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Esp�cie do t�tulo: 01=Duplicata Mercantil, 02=Nota Promiss�ria, 03=Nota de Seguro, 05=Recibo, 06=Duplicata Rural, 08=Letra de C�mbio, 09=Warrant, 10=Cheque, 12=Duplicata de Servi�o, 13=Nota de D�bito, 14=Triplicata Mercantil, 15=Triplicata de Servi�o, 18=Fatura, 20=Ap�lice de Seguro, 21=Mensalidade Escolar, 22=Parcela de Cons�rcio, 99=Outros',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aceite: 0=sem aceite, 1=com aceite (nota: Sicoob usa d�gito, n�o letra como BB/Bradesco/Ita�)',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emiss�o do t�tulo',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira instru��o (se 01 E instrucao_2=01, habilita mensagens no trailer)',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda instru��o (se 01 E instrucao_1=01, habilita mensagens no trailer)',
    canonical: null,
  },
  taxa_mora_mes: {
    pos: [161, 166],
    type: FieldType.NUM,
    size: 6,
    decimals: 4,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Taxa de mora ao m�s (4 decimais impl�citas - ex: 022000=2,20%)',
    canonical: null,
  },
  taxa_multa: {
    pos: [167, 172],
    type: FieldType.NUM,
    size: 6,
    decimals: 4,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Taxa de multa (4 decimais impl�citas - mesmo formato da taxa de mora)',
    canonical: null,
  },
  tipo_distribuicao: {
    pos: [173, 173],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de distribui��o: 1=Cooperativa, 2=Cliente',
    canonical: null,
  },
  data_primeiro_desconto: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data do primeiro desconto (DDMMAA ou zeros se sem desconto)',
    canonical: null,
  },
  valor_primeiro_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do primeiro desconto (2 decimais impl�citas)',
    canonical: null,
  },
  codigo_moeda_valor_iof_ou_qtde_moeda: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Campo composto: 1 d�gito de c�digo da moeda + 12 d�gitos que significam valor do IOF (se moeda=Real) ou quantidade monet�ria (se moeda?Real)',
    canonical: null,
  },
  valor_abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento (2 decimais impl�citas)',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do pagador: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 311],
    type: FieldType.ALFA,
    size: 37,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do pagador (37 chars no Sicoob - particularidade confirmada pela planilha oficial)',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [312, 326],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do pagador',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do pagador',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do pagador',
    canonical: 'sacado.endereco.estado',
  },
  observacoes_mensagem_ou_sacador_avalista: {
    pos: [352, 391],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Observa��es/mensagem ou dados do sacador/avalista (condicional ao campo indicativo_mensagem_sacador: se branco=mensagem livre, se A=nome/CPF-CNPJ do sacador/avalista)',
    canonical: null,
  },
  dias_protesto: {
    pos: [392, 393],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dias para protesto (0=usar padr�o do cliente cadastrado)',
    canonical: null,
  },
  brancos_3: {
    pos: [394, 394],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco (posi��o corrigida conforme manual - off-by-one na planilha original)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro (incrementa 1 a cada registro)',
    canonical: null,
  },
}
