/**
 * Sicoob / Bancoob (756) — CNAB 400 — Detalhe de Remessa (Registro Tipo 1)
 *
 * Cooperativa de crédito, nosso número 12 dígitos (com DV).
 *
 * Fontes:
 * - Planilha oficial Sicoob (Layout_Cobranca_CNAB400 (1).xls, mai/2025)
 * - cnab_yaml (fonte original, concordante)
 *
 * Particularidades do Sicoob:
 * - logradouro com 37 caracteres (não 40 como outros bancos)
 * - aceite usa dígito ('0'/'1') em vez de letra ('N'/'A')
 * - vencimento aceita valores especiais: '888888'=à vista, '999999'=contra apresentação
 * - nosso_numero: zeros se emissão Sicoob, ou sequencial 10 dígitos + DV módulo 11 se emissão cliente
 * - campo de moeda condicional (pos 193-205): se Real=valor IOF, se outra moeda=quantidade monetária
 *
 */

import { RecordSchema } from '../../../../types'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  tipo_inscricao_beneficiario: {
    pos: [2, 3],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do beneficiário: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao_beneficiario: {
    pos: [4, 17],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do beneficiário',
    canonical: null,
  },
  prefixo_cooperativa: {
    pos: [18, 21],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo: {
    pos: [22, 22],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador do prefixo (ver planilha Contracapa)',
    canonical: null,
  },
  conta_corrente: {
    pos: [23, 30],
    type: 'num',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente (ver planilha Contracapa)',
    canonical: null,
  },
  dv_conta: {
    pos: [31, 31],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta (ver planilha Contracapa)',
    canonical: null,
  },
  numero_convenio_cobranca: {
    pos: [32, 37],
    type: 'num',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000000',
    description: 'Número do convênio de cobrança',
    canonical: null,
  },
  numero_controle_participante: {
    pos: [38, 62],
    type: 'alfa',
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de controle do participante (campo livre para o cliente)',
    canonical: null,
  },
  nosso_numero: {
    pos: [63, 74],
    type: 'num',
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso número: zeros se emissão Sicoob (comando 01), ou sequencial 10 dígitos + DV módulo 11 se emissão cliente',
    canonical: 'nossoNumero',
  },
  numero_parcela: {
    pos: [75, 76],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '01',
    description: 'Número da parcela (01 se parcela única)',
    canonical: null,
  },
  grupo_valor: {
    pos: [77, 78],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Grupo de valor',
    canonical: null,
  },
  brancos_1: {
    pos: [79, 81],
    type: 'alfa',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  indicativo_mensagem_sacador: {
    pos: [82, 82],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indicativo de mensagem do sacador: branco=mensagem livre no campo observacoes_mensagem_ou_sacador_avalista, A=dados do sacador/avalista',
    canonical: null,
  },
  prefixo_titulo: {
    pos: [83, 85],
    type: 'alfa',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo do título (espaços em branco)',
    canonical: null,
  },
  variacao_carteira: {
    pos: [86, 88],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000',
    description: 'Variação da carteira',
    canonical: null,
  },
  conta_caucao: {
    pos: [89, 89],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Conta caução',
    canonical: null,
  },
  numero_contrato_garantia: {
    pos: [90, 94],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00000',
    description: 'Número do contrato de garantia (00000 para carteira 1, ou número sem DV para carteira 3)',
    canonical: null,
  },
  dv_contrato: {
    pos: [95, 95],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Dígito verificador do contrato (0 para carteira 1, ou DV real para carteira 3)',
    canonical: null,
  },
  numero_bordero: {
    pos: [96, 101],
    type: 'num',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do borderô (preencher se carteira 3)',
    canonical: null,
  },
  brancos_2: {
    pos: [102, 105],
    type: 'alfa',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  tipo_emissao: {
    pos: [106, 106],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de emissão: 1=Cooperativa, 2=Cliente',
    canonical: null,
  },
  carteira_modalidade: {
    pos: [107, 108],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Carteira/modalidade: 01=Simples Com Registro, 03=Garantida Caucionada',
    canonical: null,
  },
  comando_movimento: {
    pos: [109, 110],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de comando/movimento: 01=Entrada de Títulos, 02=Solicitação de Baixa, 04=Concessão de Abatimento, 05=Cancelamento de Abatimento, 06=Prorrogação de Vencimento, 08=Alteração de Seu Número, 09=Instrução para Protestar, 10=Desistência do Protesto e Baixar Título, 11=Instrução para Dispensar Juros, 12=Alteração de Pagador, 31=Alteração de Outros Dados, 34=Baixa - Pagamento Direto ao Beneficiário',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento (seu número)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de vencimento (DDMMAA, ou 888888=à vista, ou 999999=contra apresentação)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: 'num',
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título (2 decimais implícitas)',
    canonical: 'valor',
  },
  numero_banco: {
    pos: [140, 142],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '756',
    description: 'Número do banco (756)',
    canonical: null,
  },
  prefixo_cooperativa_cobradora: {
    pos: [143, 146],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa cobradora (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo_cobradora: {
    pos: [147, 147],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador do prefixo da cobradora (ver planilha Contracapa)',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espécie do título: 01=Duplicata Mercantil, 02=Nota Promissória, 03=Nota de Seguro, 05=Recibo, 06=Duplicata Rural, 08=Letra de Câmbio, 09=Warrant, 10=Cheque, 12=Duplicata de Serviço, 13=Nota de Débito, 14=Triplicata Mercantil, 15=Triplicata de Serviço, 18=Fatura, 20=Apólice de Seguro, 21=Mensalidade Escolar, 22=Parcela de Consórcio, 99=Outros',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aceite: 0=sem aceite, 1=com aceite (nota: Sicoob usa dígito, não letra como BB/Bradesco/Itaú)',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de emissão do título',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira instrução (se 01 E instrucao_2=01, habilita mensagens no trailer)',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda instrução (se 01 E instrucao_1=01, habilita mensagens no trailer)',
    canonical: null,
  },
  taxa_mora_mes: {
    pos: [161, 166],
    type: 'num',
    size: 6,
    decimals: 4,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Taxa de mora ao mês (4 decimais implícitas - ex: 022000=2,20%)',
    canonical: null,
  },
  taxa_multa: {
    pos: [167, 172],
    type: 'num',
    size: 6,
    decimals: 4,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Taxa de multa (4 decimais implícitas - mesmo formato da taxa de mora)',
    canonical: null,
  },
  tipo_distribuicao: {
    pos: [173, 173],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de distribuição: 1=Cooperativa, 2=Cliente',
    canonical: null,
  },
  data_primeiro_desconto: {
    pos: [174, 179],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data do primeiro desconto (DDMMAA ou zeros se sem desconto)',
    canonical: null,
  },
  valor_primeiro_desconto: {
    pos: [180, 192],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do primeiro desconto (2 decimais implícitas)',
    canonical: null,
  },
  codigo_moeda_valor_iof_ou_qtde_moeda: {
    pos: [193, 205],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Campo composto: 1 dígito de código da moeda + 12 dígitos que significam valor do IOF (se moeda=Real) ou quantidade monetária (se moeda≠Real)',
    canonical: null,
  },
  valor_abatimento: {
    pos: [206, 218],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento (2 decimais implícitas)',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do pagador: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 311],
    type: 'alfa',
    size: 37,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do pagador (37 chars no Sicoob - particularidade confirmada pela planilha oficial)',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [312, 326],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do pagador',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do pagador',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do pagador',
    canonical: 'sacado.endereco.estado',
  },
  observacoes_mensagem_ou_sacador_avalista: {
    pos: [352, 391],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Observações/mensagem ou dados do sacador/avalista (condicional ao campo indicativo_mensagem_sacador: se branco=mensagem livre, se A=nome/CPF-CNPJ do sacador/avalista)',
    canonical: null,
  },
  dias_protesto: {
    pos: [392, 393],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dias para protesto (0=usar padrão do cliente cadastrado)',
    canonical: null,
  },
  brancos_3: {
    pos: [394, 394],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco (posição corrigida conforme manual - off-by-one na planilha original)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro (incrementa 1 a cada registro)',
    canonical: null,
  },
}
