/**
 * Sicoob / Bancoob (756) — CNAB 400 — Header de Arquivo (Remessa)
 *
 * Cooperativa de crédito, nosso número 12 dígitos (com DV).
 *
 * Fontes:
 * - Planilha oficial Sicoob (Layout_Cobranca_CNAB400 (1).xls, mai/2025)
 * - cnab_yaml (fonte original, concordante)
 *
 */

import { RecordSchema } from '../../../../types'

export const HEADER: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificação do header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operação: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: 'alfa',
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Código de serviço',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 19],
    type: 'alfa',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de serviço',
    canonical: null,
  },
  brancos_1: {
    pos: [20, 26],
    type: 'alfa',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  prefixo_cooperativa: {
    pos: [27, 30],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo: {
    pos: [31, 31],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador do prefixo (espaços em branco)',
    canonical: null,
  },
  codigo_cliente_beneficiario: {
    pos: [32, 39],
    type: 'num',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código do cliente/beneficiário (ver planilha Contracapa)',
    canonical: null,
  },
  dv_codigo_cliente: {
    pos: [40, 40],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador do código do cliente (ver planilha Contracapa)',
    canonical: null,
  },
  numero_convenio_lider: {
    pos: [41, 46],
    type: 'alfa',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do convênio líder (espaços em branco - campo existe mas não é usado)',
    canonical: null,
  },
  nome_beneficiario: {
    pos: [47, 76],
    type: 'alfa',
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficiário (ver planilha Contracapa)',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '756',
    description: 'Código FEBRABAN do Sicoob',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'BANCOOBCED',
    description: 'Nome do banco (campo único combinado código+nome na planilha original: 756BANCOOBCED)',
    canonical: null,
  },
  data_gravacao: {
    pos: [95, 100],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de gravação do arquivo',
    canonical: 'dataGeracao',
  },
  sequencial_remessa: {
    pos: [101, 107],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial da remessa (incrementa 1 a cada remessa, inicia em 0000001)',
    canonical: null,
  },
  brancos_2: {
    pos: [108, 394],
    type: 'alfa',
    size: 287,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Número sequencial do registro no arquivo (000001 no header)',
    canonical: null,
  },
}
