/**
 * Sicoob / Bancoob (756) � CNAB 400 � Header de Arquivo (Remessa)
 * Cooperativa de cr�dito, nosso n�mero 12 d�gitos (com DV).
 *
 * Fontes:
 * - Planilha oficial Sicoob (Layout_Cobranca_CNAB400 (1).xls, mai/2025)
 * - cnab_yaml (fonte original, concordante)
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const HEADER: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identifica��o do header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de opera��o: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'C�digo de servi�o',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 19],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de servi�o',
    canonical: null,
  },
  brancos_1: {
    pos: [20, 26],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  prefixo_cooperativa: {
    pos: [27, 30],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo: {
    pos: [31, 31],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador do prefixo (espa�os em branco)',
    canonical: null,
  },
  codigo_cliente_beneficiario: {
    pos: [32, 39],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do cliente/benefici�rio (ver planilha Contracapa)',
    canonical: null,
  },
  dv_codigo_cliente: {
    pos: [40, 40],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador do c�digo do cliente (ver planilha Contracapa)',
    canonical: null,
  },
  numero_convenio_lider: {
    pos: [41, 46],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do conv�nio l�der (espa�os em branco - campo existe mas n�o � usado)',
    canonical: null,
  },
  nome_beneficiario: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do benefici�rio (ver planilha Contracapa)',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '756',
    description: 'C�digo FEBRABAN do Sicoob',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'BANCOOBCED',
    description: 'Nome do banco (campo �nico combinado c�digo+nome na planilha original: 756BANCOOBCED)',
    canonical: null,
  },
  data_gravacao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de grava��o do arquivo',
    canonical: 'dataGeracao',
  },
  sequencial_remessa: {
    pos: [101, 107],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial da remessa (incrementa 1 a cada remessa, inicia em 0000001)',
    canonical: null,
  },
  brancos_2: {
    pos: [108, 394],
    type: FieldType.ALFA,
    size: 287,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'N�mero sequencial do registro no arquivo (000001 no header)',
    canonical: null,
  },
}
