/**
 * Sicoob / Bancoob (756)  CNAB 400  Header de Arquivo (Remessa)
 * Cooperativa de crdito, nosso nmero 12 dgitos (com DV).
 *
 * Fontes:
 * - Planilha oficial Sicoob (Layout_Cobranca_CNAB400 (1).xls, mai/2025)
 * - cnab_yaml (fonte original, concordante)
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const HEADER: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificao do header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operao: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Cdigo de servio',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 19],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de servio',
    canonical: null,
  },
  brancos_1: {
    pos: [20, 26],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaos em branco',
    canonical: null,
  },
  prefixo_cooperativa: {
    pos: [27, 30],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da cooperativa (ver planilha Contracapa)',
    canonical: null,
  },
  dv_prefixo: {
    pos: [31, 31],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dgito verificador do prefixo (espaos em branco)',
    canonical: null,
  },
  codigo_cliente_beneficiario: {
    pos: [32, 39],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo do cliente/beneficirio (ver planilha Contracapa)',
    canonical: null,
  },
  dv_codigo_cliente: {
    pos: [40, 40],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dgito verificador do cdigo do cliente (ver planilha Contracapa)',
    canonical: null,
  },
  numero_convenio_lider: {
    pos: [41, 46],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do convnio lder (espaos em branco - campo existe mas no  usado)',
    canonical: null,
  },
  nome_beneficiario: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficirio (ver planilha Contracapa)',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '756',
    description: 'Cdigo FEBRABAN do Sicoob',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'BANCOOBCED',
    description: 'Nome do banco (campo nico combinado cdigo+nome na planilha original: 756BANCOOBCED)',
    canonical: null,
  },
  data_gravacao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de gravao do arquivo',
    canonical: 'dataGeracao',
  },
  sequencial_remessa: {
    pos: [101, 107],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial da remessa (incrementa 1 a cada remessa, inicia em 0000001)',
    canonical: null,
  },
  brancos_2: {
    pos: [108, 394],
    type: FieldType.ALFA,
    size: 287,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaos em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Nmero sequencial do registro no arquivo (000001 no header)',
    canonical: null,
  },
}
