/**
 * Sicredi (748) � CNAB 400 � Detalhe de Remessa (Registro Tipo 1)
 * Fonte:
 * - Manual oficial Sicredi CNAB 400 (2026_03_12_manual_cnab_400_30.pdf, v3.0, fev/2026) � �8.2, p.26-31
 * - laravel-boleto (Cnab/Remessa/Cnab400/Banco/Sicredi.php) � confirma um subconjunto das posi��es
 *   (a lib n�o implementa ~15 campos de neg�cio do manual: tipo de impress�o/carn�, datas de in�cio
 *   de cobran�a de juros/multa, desconto por antecipa��o, multa em valor monet�rio, negativa��o
 *   autom�tica, abatimento � grava zeros/brancos fixos nessas faixas em vez de expor os campos)
 * Nomenclatura "Benefici�rio Final" (n�o "Sacador/Avalista", nome usado por libs de terceiros mais
 * antigas) segue as Circulares BACEN 3598, 3656 e 3956, citadas explicitamente pelo manual.
 * Particularidade: datas de in�cio de cobran�a de juros/multa e a data de instru��o usam formato
 * AAAAMMDD (8 d�gitos) � diferente de vencimento/emiss�o/desconto, que usam DDMMAA (6 d�gitos).
 * Duas formata��es de data convivem no mesmo registro; confirmado pelo manual oficial, n�o � erro.
 * Ver an�lise completa (incluindo notas sobre inconsist�ncias do pr�prio PDF do manual) em:
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Identifica��o do registro detalhe',
    canonical: null,
  },
  tipo_cobranca: {
    pos: [2, 2],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de cobran�a: A=Sicredi com Registro (�nico valor documentado)',
    canonical: null,
  },
  numero_carteira: {
    pos: [3, 3],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de carteira: A=Simples (�nico valor documentado)',
    canonical: null,
  },
  tipo_impressao: {
    pos: [4, 4],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de impress�o: A=Normal, B=Carn�',
    canonical: null,
  },
  brancos_1: {
    pos: [5, 5],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  tipo_boleto: {
    pos: [6, 6],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de boleto: H=H�brido (com QR Code) � controla se o registro tipo 8 � obrigat�rio',
    canonical: null,
  },
  brancos_2: {
    pos: [7, 16],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  tipo_moeda: {
    pos: [17, 17],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de moeda: A=Real (�nico valor documentado)',
    canonical: null,
  },
  tipo_desconto: {
    pos: [18, 18],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de desconto: A=Valor monet�rio, B=Percentual',
    canonical: null,
  },
  tipo_juros: {
    pos: [19, 19],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de juros: A=Valor monet�rio, B=Percentual di�rio, C=Percentual mensal',
    canonical: null,
  },
  tipo_multa: {
    pos: [20, 20],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de multa: A=Valor monet�rio, B=Percentual (default percentual se n�o informado)',
    canonical: null,
  },
  data_inicio_juros: {
    pos: [21, 28],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.AAAAMMDD,
    pattern: null,
    description: 'Data de in�cio da cobran�a de juros (m�n. vencimento+1, ou zeros)',
    canonical: 'juros.vigenciaAPartirDe',
  },
  data_inicio_multa: {
    pos: [29, 36],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.AAAAMMDD,
    pattern: null,
    description: 'Data de in�cio da cobran�a de multa (m�n. vencimento+1, ou zeros)',
    canonical: null,
  },
  brancos_3: {
    pos: [37, 47],
    type: FieldType.ALFA,
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  nosso_numero: {
    pos: [48, 56],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nosso n�mero � pode ficar em branco se impress�o pelo Sicredi (gerado automaticamente)',
    canonical: 'nossoNumero',
  },
  brancos_4: {
    pos: [57, 62],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  data_instrucao: {
    pos: [63, 70],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.AAAAMMDD,
    pattern: null,
    description: 'Data de instru��o � s� usada quando instrucao (109-110) = "31"; sen�o vazio',
    canonical: null,
  },
  campo_alterado_instrucao31: {
    pos: [71, 71],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Campo alterado quando instrucao=31: A=Desconto, B=Juros por dia, C=Desconto por antecipa��o, D=Data limite para desconto, E=Cancelamento de protesto autom�tico',
    canonical: null,
  },
  postagem_titulo: {
    pos: [72, 72],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Postagem do t�tulo: S=Sicredi posta, N=benefici�rio/cedente posta',
    canonical: null,
  },
  brancos_5: {
    pos: [73, 73],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  impressao_boleto: {
    pos: [74, 74],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Impress�o do boleto: A=Sicredi, B=benefici�rio/cedente',
    canonical: null,
  },
  numero_parcela_carne: {
    pos: [75, 76],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero da parcela do carn� � s� quando tipo_impressao=B',
    canonical: null,
  },
  total_parcelas_carne: {
    pos: [77, 78],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Total de parcelas do carn� � s� quando tipo_impressao=B',
    canonical: null,
  },
  brancos_6: {
    pos: [79, 82],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  valor_desconto_antecipacao: {
    pos: [83, 92],
    type: FieldType.NUM,
    size: 10,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto por dia de antecipa��o',
    canonical: null,
  },
  valor_multa_percentual: {
    pos: [93, 96],
    type: FieldType.NUM,
    size: 4,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor da multa em PERCENTUAL � usar s� quando tipo_multa=B',
    canonical: null,
  },
  valor_multa_monetario: {
    pos: [97, 108],
    type: FieldType.NUM,
    size: 12,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor da multa em VALOR MONET�RIO � usar s� quando tipo_multa=A',
    canonical: null,
  },
  instrucao: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'C�digo de instru��o: 01=Cadastro de T�tulos, 02=Pedido de Baixa, 04=Concess�o de Abatimento, 05=Cancelamento de Abatimento, 06=Altera��o de Vencimento, 09=Pedido de Protesto, 18=Sustar protesto e baixar t�tulo, 19=Sustar protesto e manter em carteira, 31=Altera��o de outros dados, 45=Incluir negativa��o, 75=Excluir negativa��o e manter na carteira, 76=Excluir negativa��o e baixar t�tulos',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Seu n�mero � sem espa�o em branco (ex: "123/4", n�o "123 4")',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento � deve ser 7 dias maior que a data de emiss�o (151-156)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do t�tulo',
    canonical: 'valor',
  },
  brancos_7: {
    pos: [140, 148],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  especie: {
    pos: [149, 149],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'Esp�cie do t�tulo: A=Duplicata Mercantil, B=Duplicata Rural, C=Nota Promiss�ria, D=Nota Promiss�ria Rural, E=Nota de Seguros, G=Recibo, H=Letra de C�mbio, I=Nota de D�bito, J=Duplicata de Servi�o, K=Outros, O=Boleto Proposta (n�o permite h�brido)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Aceite do t�tulo: S=Sim, N=N�o',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emiss�o � deve ser 7 dias menor que o vencimento (121-126)',
    canonical: 'dataEmissao',
  },
  instrucao_protesto_automatico: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Instru��o de protesto autom�tico: 00=N�o protestar, 06=Protestar',
    canonical: null,
  },
  dias_protesto: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Dias para protesto autom�tico: m�nimo 03, m�ximo 99 (03-04 dias = �teis, 05+ = corridos)',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros por dia de atraso, valor ou percentual conforme tipo_juros (posi��o 19)',
    canonical: null,
  },
  data_limite_desconto: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para desconto � zeros = usa a data de vencimento',
    canonical: 'desconto.dataLimite',
  },
  valor_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto conforme tipo_desconto (posi��o 18)',
    canonical: 'desconto.valor',
  },
  instrucao_negativacao: {
    pos: [193, 194],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Instru��o de negativa��o autom�tica: 00=N�o negativar, 06=Negativar (s� benefici�rio PJ; excludente com protesto)',
    canonical: null,
  },
  dias_negativacao: {
    pos: [195, 196],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Dias para negativa��o autom�tica: m�nimo 03, m�ximo 99 (03-04 dias = �teis, 05+ = corridos)',
    canonical: null,
  },
  brancos_8: {
    pos: [197, 205],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zeros pelo manual)',
    canonical: null,
  },
  valor_abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 219],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do pagador/sacado: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  brancos_9: {
    pos: [220, 220],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zero pelo manual)',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do pagador/sacado � deve ser v�lido mesmo em homologa��o',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador (padr�o FEBRABAN, 40 posi��es � n�o a variante 37+3 do BB)',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  codigo_pagador_cooperativa: {
    pos: [315, 319],
    type: FieldType.ALFA,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do pagador na cooperativa do benefici�rio � zeros se n�o cadastrado',
    canonical: null,
  },
  brancos_10: {
    pos: [320, 325],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zeros pelo manual)',
    canonical: null,
  },
  brancos_11: {
    pos: [326, 326],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador � obrigat�rio ser um CEP v�lido quando informado',
    canonical: 'sacado.endereco.cep',
  },
  codigo_pagador_cliente: {
    pos: [335, 339],
    type: FieldType.ALFA,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do pagador junto ao cliente � zeros se n�o houver',
    canonical: null,
  },
  numero_inscricao_beneficiario_final: {
    pos: [340, 353],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'CPF/CNPJ do Benefici�rio Final (nomenclatura BACEN 3598/3656/3956, n�o "sacador/avalista") � deve ser diferente do benefici�rio e do pagador; deixar em branco se n�o existir',
    canonical: null,
  },
  nome_beneficiario_final: {
    pos: [354, 394],
    type: FieldType.ALFA,
    size: 41,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Benefici�rio Final � deixar em branco quando inexistente',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no arquivo',
    canonical: null,
  },
}
