/**
 * Sicredi (748) — CNAB 400 — Detalhe de Remessa (Registro Tipo 1)
 *
 * Fonte:
 * - Manual oficial Sicredi CNAB 400 (2026_03_12_manual_cnab_400_30.pdf, v3.0, fev/2026) — §8.2, p.26-31
 * - laravel-boleto (Cnab/Remessa/Cnab400/Banco/Sicredi.php) — confirma um subconjunto das posições
 *   (a lib não implementa ~15 campos de negócio do manual: tipo de impressão/carnê, datas de início
 *   de cobrança de juros/multa, desconto por antecipação, multa em valor monetário, negativação
 *   automática, abatimento — grava zeros/brancos fixos nessas faixas em vez de expor os campos)
 *
 * Nomenclatura "Beneficiário Final" (não "Sacador/Avalista", nome usado por libs de terceiros mais
 * antigas) segue as Circulares BACEN 3598, 3656 e 3956, citadas explicitamente pelo manual.
 *
 * Particularidade: datas de início de cobrança de juros/multa e a data de instrução usam formato
 * AAAAMMDD (8 dígitos) — diferente de vencimento/emissão/desconto, que usam DDMMAA (6 dígitos).
 * Duas formatações de data convivem no mesmo registro; confirmado pelo manual oficial, não é erro.
 *
 * Ver análise completa (incluindo notas sobre inconsistências do próprio PDF do manual) em:
 */

import { RecordSchema } from '../../../../types'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Identificação do registro detalhe',
    canonical: null,
  },
  tipo_cobranca: {
    pos: [2, 2],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de cobrança: A=Sicredi com Registro (único valor documentado)',
    canonical: null,
  },
  numero_carteira: {
    pos: [3, 3],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de carteira: A=Simples (único valor documentado)',
    canonical: null,
  },
  tipo_impressao: {
    pos: [4, 4],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de impressão: A=Normal, B=Carnê',
    canonical: null,
  },
  brancos_1: {
    pos: [5, 5],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  tipo_boleto: {
    pos: [6, 6],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de boleto: H=Híbrido (com QR Code) — controla se o registro tipo 8 é obrigatório',
    canonical: null,
  },
  brancos_2: {
    pos: [7, 16],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  tipo_moeda: {
    pos: [17, 17],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de moeda: A=Real (único valor documentado)',
    canonical: null,
  },
  tipo_desconto: {
    pos: [18, 18],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de desconto: A=Valor monetário, B=Percentual',
    canonical: null,
  },
  tipo_juros: {
    pos: [19, 19],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de juros: A=Valor monetário, B=Percentual diário, C=Percentual mensal',
    canonical: null,
  },
  tipo_multa: {
    pos: [20, 20],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de multa: A=Valor monetário, B=Percentual (default percentual se não informado)',
    canonical: null,
  },
  data_inicio_juros: {
    pos: [21, 28],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'AAAAMMDD',
    pattern: null,
    description: 'Data de início da cobrança de juros (mín. vencimento+1, ou zeros)',
    canonical: 'juros.vigenciaAPartirDe',
  },
  data_inicio_multa: {
    pos: [29, 36],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'AAAAMMDD',
    pattern: null,
    description: 'Data de início da cobrança de multa (mín. vencimento+1, ou zeros)',
    canonical: null,
  },
  brancos_3: {
    pos: [37, 47],
    type: 'alfa',
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  nosso_numero: {
    pos: [48, 56],
    type: 'num',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nosso número — pode ficar em branco se impressão pelo Sicredi (gerado automaticamente)',
    canonical: 'nossoNumero',
  },
  brancos_4: {
    pos: [57, 62],
    type: 'alfa',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  data_instrucao: {
    pos: [63, 70],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'AAAAMMDD',
    pattern: null,
    description: 'Data de instrução — só usada quando instrucao (109-110) = "31"; senão vazio',
    canonical: null,
  },
  campo_alterado_instrucao31: {
    pos: [71, 71],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Campo alterado quando instrucao=31: A=Desconto, B=Juros por dia, C=Desconto por antecipação, D=Data limite para desconto, E=Cancelamento de protesto automático',
    canonical: null,
  },
  postagem_titulo: {
    pos: [72, 72],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Postagem do título: S=Sicredi posta, N=beneficiário/cedente posta',
    canonical: null,
  },
  brancos_5: {
    pos: [73, 73],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  impressao_boleto: {
    pos: [74, 74],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Impressão do boleto: A=Sicredi, B=beneficiário/cedente',
    canonical: null,
  },
  numero_parcela_carne: {
    pos: [75, 76],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da parcela do carnê — só quando tipo_impressao=B',
    canonical: null,
  },
  total_parcelas_carne: {
    pos: [77, 78],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Total de parcelas do carnê — só quando tipo_impressao=B',
    canonical: null,
  },
  brancos_6: {
    pos: [79, 82],
    type: 'alfa',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  valor_desconto_antecipacao: {
    pos: [83, 92],
    type: 'num',
    size: 10,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto por dia de antecipação',
    canonical: null,
  },
  valor_multa_percentual: {
    pos: [93, 96],
    type: 'num',
    size: 4,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor da multa em PERCENTUAL — usar só quando tipo_multa=B',
    canonical: null,
  },
  valor_multa_monetario: {
    pos: [97, 108],
    type: 'num',
    size: 12,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor da multa em VALOR MONETÁRIO — usar só quando tipo_multa=A',
    canonical: null,
  },
  instrucao: {
    pos: [109, 110],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'Código de instrução: 01=Cadastro de Títulos, 02=Pedido de Baixa, 04=Concessão de Abatimento, 05=Cancelamento de Abatimento, 06=Alteração de Vencimento, 09=Pedido de Protesto, 18=Sustar protesto e baixar título, 19=Sustar protesto e manter em carteira, 31=Alteração de outros dados, 45=Incluir negativação, 75=Excluir negativação e manter na carteira, 76=Excluir negativação e baixar títulos',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Seu número — sem espaço em branco (ex: "123/4", não "123 4")',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de vencimento — deve ser 7 dias maior que a data de emissão (151-156)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: 'num',
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título',
    canonical: 'valor',
  },
  brancos_7: {
    pos: [140, 148],
    type: 'alfa',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  especie: {
    pos: [149, 149],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'Espécie do título: A=Duplicata Mercantil, B=Duplicata Rural, C=Nota Promissória, D=Nota Promissória Rural, E=Nota de Seguros, G=Recibo, H=Letra de Câmbio, I=Nota de Débito, J=Duplicata de Serviço, K=Outros, O=Boleto Proposta (não permite híbrido)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Aceite do título: S=Sim, N=Não',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de emissão — deve ser 7 dias menor que o vencimento (121-126)',
    canonical: 'dataEmissao',
  },
  instrucao_protesto_automatico: {
    pos: [157, 158],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Instrução de protesto automático: 00=Não protestar, 06=Protestar',
    canonical: null,
  },
  dias_protesto: {
    pos: [159, 160],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Dias para protesto automático: mínimo 03, máximo 99 (03-04 dias = úteis, 05+ = corridos)',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros por dia de atraso, valor ou percentual conforme tipo_juros (posição 19)',
    canonical: null,
  },
  data_limite_desconto: {
    pos: [174, 179],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data limite para desconto — zeros = usa a data de vencimento',
    canonical: 'desconto.dataLimite',
  },
  valor_desconto: {
    pos: [180, 192],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto conforme tipo_desconto (posição 18)',
    canonical: 'desconto.valor',
  },
  instrucao_negativacao: {
    pos: [193, 194],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Instrução de negativação automática: 00=Não negativar, 06=Negativar (só beneficiário PJ; excludente com protesto)',
    canonical: null,
  },
  dias_negativacao: {
    pos: [195, 196],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Dias para negativação automática: mínimo 03, máximo 99 (03-04 dias = úteis, 05+ = corridos)',
    canonical: null,
  },
  brancos_8: {
    pos: [197, 205],
    type: 'num',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zeros pelo manual)',
    canonical: null,
  },
  valor_abatimento: {
    pos: [206, 218],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 219],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do pagador/sacado: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  brancos_9: {
    pos: [220, 220],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zero pelo manual)',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do pagador/sacado — deve ser válido mesmo em homologação',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador (padrão FEBRABAN, 40 posições — não a variante 37+3 do BB)',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  codigo_pagador_cooperativa: {
    pos: [315, 319],
    type: 'alfa',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do pagador na cooperativa do beneficiário — zeros se não cadastrado',
    canonical: null,
  },
  brancos_10: {
    pos: [320, 325],
    type: 'num',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Filler (preenchido com zeros pelo manual)',
    canonical: null,
  },
  brancos_11: {
    pos: [326, 326],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  cep: {
    pos: [327, 334],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador — obrigatório ser um CEP válido quando informado',
    canonical: 'sacado.endereco.cep',
  },
  codigo_pagador_cliente: {
    pos: [335, 339],
    type: 'alfa',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do pagador junto ao cliente — zeros se não houver',
    canonical: null,
  },
  numero_inscricao_beneficiario_final: {
    pos: [340, 353],
    type: 'num',
    size: 14,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'CPF/CNPJ do Beneficiário Final (nomenclatura BACEN 3598/3656/3956, não "sacador/avalista") — deve ser diferente do beneficiário e do pagador; deixar em branco se não existir',
    canonical: null,
  },
  nome_beneficiario_final: {
    pos: [354, 394],
    type: 'alfa',
    size: 41,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Beneficiário Final — deixar em branco quando inexistente',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no arquivo',
    canonical: null,
  },
}
