/**
 * Sicredi (748) — CNAB 400 — Registro Tipo 5 (Informativo)
 *
 * Registro opcional para incluir dados/texto adicional ao boleto, além do que cabe no
 * registro Mensagem (tipo 2). Até 5 registros tipo 5 encadeados por título (20 linhas no total).
 *
 * Fonte:
 * - Manual oficial Sicredi CNAB 400 (2026_03_12_manual_cnab_400_30.pdf, v3.0, fev/2026) — §8.4, p.32
 *
 * Sem confirmação de terceiros — nenhuma lib do projeto implementa este registro.
 *
 * Ver: src/schemas/banks/sicredi/cnab400/registros-opcionais/tipo5/tipo5-informativo.md
 */

import { RecordSchema, FieldType } from '@/types/all-types'

export const TYPE5_INFORMATIVE: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '5',
    description: 'Identificação do registro informativo',
    canonical: null,
  },
  tipo_informativo: {
    pos: [2, 2],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'E',
    description: 'Tipo de informativo: E=Específico de um título (único valor documentado)',
    canonical: null,
  },
  codigo_beneficiario_cedente: {
    pos: [3, 7],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código do beneficiário/cedente na Cooperativa',
    canonical: null,
  },
  identificacao_titulo_seu_numero: {
    pos: [8, 17],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Deve bater com posições 111-120 do detalhe',
    canonical: null,
  },
  brancos_1: {
    pos: [18, 18],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  tipo_cobranca: {
    pos: [19, 19],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'A',
    description: 'Tipo de cobrança: A=Cobrança com registro',
    canonical: null,
  },
  numero_linha_informativo_1: {
    pos: [20, 21],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da linha do informativo (1-99)',
    canonical: null,
  },
  texto_linha_informativo_1: {
    pos: [22, 101],
    type: FieldType.ALFA,
    size: 80,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Texto livre da linha 1',
    canonical: null,
  },
  numero_linha_informativo_2: {
    pos: [102, 103],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da linha do informativo (1-99)',
    canonical: null,
  },
  texto_linha_informativo_2: {
    pos: [104, 183],
    type: FieldType.ALFA,
    size: 80,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Texto livre da linha 2',
    canonical: null,
  },
  numero_linha_informativo_3: {
    pos: [184, 185],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da linha do informativo (1-99)',
    canonical: null,
  },
  texto_linha_informativo_3: {
    pos: [186, 265],
    type: FieldType.ALFA,
    size: 80,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Texto livre da linha 3',
    canonical: null,
  },
  numero_linha_informativo_4: {
    pos: [266, 267],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da linha do informativo (1-99)',
    canonical: null,
  },
  texto_linha_informativo_4: {
    pos: [268, 347],
    type: FieldType.ALFA,
    size: 80,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Texto livre da linha 4',
    canonical: null,
  },
  brancos_2: {
    pos: [348, 394],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no arquivo',
    canonical: null,
  },
}
