module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: ['**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/**/index.ts',
    '!src/**/tests/**',
    '!src/**/docs/**',
  ],
  coverageDirectory: 'coverage',
  verbose: true,
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@cnab/type/(.*)$': '<rootDir>/src/cnab/type/$1',
    '^@cnab/exception/(.*)$': '<rootDir>/src/cnab/exception/$1',
    '^@cnab/validators/(.*)$': '<rootDir>/src/cnab/validators/$1',
    '^@cnab/utils/(.*)$': '<rootDir>/src/cnab/utils/$1',
    '^@cnab/bank/(.*)$': '<rootDir>/src/cnab/bank/$1',
    '^@test/(.*)$': '<rootDir>/test/$1',
  },
}
