/* *
 * Segmento opcional que cont�m:
 * - Segundo e terceiro descontos
 * - Multa
 * - Mensagens livres para impress�o no boleto
 * Segmento: R
 * 
 * Baseado em:
 * - Manual "Layout Padr�o 240 � Cobran�a, Vers�o 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SANTANDER_CNAB240_SEGMENT_R: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'C�digo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Segmento R = descontos, multa e mensagens',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento da remessa (vari�vel: 01=Entrada, 02=Baixa, 04=Abatimento, etc.)',
    canonical: null,
  },
  desconto2_codigo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo do 2� desconto: 0=Sem, 1=Valor, 2=%',
    canonical: null,
  },
  desconto2_data: {
    pos: [19, 26],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para o 2� desconto',
    canonical: null,
  },
  desconto2_valor: {
    pos: [27, 41],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do 2� desconto',
    canonical: null,
  },
  desconto3_codigo: {
    pos: [42, 42],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo do 3� desconto: 0=Sem, 1=Valor, 2=%',
    canonical: null,
  },
  desconto3_data: {
    pos: [43, 50],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para o 3� desconto',
    canonical: null,
  },
  desconto3_valor: {
    pos: [51, 65],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do 3� desconto',
    canonical: null,
  },
  multa_codigo: {
    pos: [66, 66],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo de multa: 0=Sem, 1=Valor, 2=%',
    canonical: {
      field: 'multa.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2) return 'percentual'
        return undefined
      },
    },
  },
  multa_data: {
    pos: [67, 74],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data a partir da qual incide multa',
    canonical: 'multa.vigenciaAPartirDe',
  },
  multa_valor: {
    pos: [75, 89],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual da multa',
    canonical: 'multa.valor',
  },
  cnab_exclusivo_2: {
    pos: [90, 99],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  mensagem_1: {
    pos: [100, 139],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 1 para impress�o no boleto',
    canonical: null,
  },
  mensagem_2: {
    pos: [140, 179],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 para impress�o no boleto',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [180, 240],
    type: FieldType.ALFA,
    size: 61,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
