/**
 * Santander CNAB 240 - Segmento Y-03 (PIX)
 * Registro opcional para dados de PIX vinculados ao boleto (chave PIX, QR Code).
 * Introduzido em Novembro/2021.
 * Segmento Y-03 (pos 8 = '3', pos 14 = 'Y', pos 18-19 = '03')
 * 
 * Fonte do layout: Manual "MANUAL DO CLIENTE DE COBRAN�A", c�digo H7815, Vers�o 6, Fevereiro/2023
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const SANTANDER_CNAB240_SEGMENT_Y03: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'C�digo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento Remessa',
    canonical: null,
  },
  registro_opcional_id: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '03',
    description: 'Identifica��o do Registro Opcional: 03=PIX',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [20, 80],
    type: FieldType.ALFA,
    size: 61,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  pix_tipo_chave: {
    pos: [81, 81],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de Chave PIX (ver tabela de c�digos no manual)',
    canonical: null,
  },
  pix_chave: {
    pos: [82, 158],
    type: FieldType.ALFA,
    size: 77,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Chave PIX',
    canonical: null,
  },
  pix_qrcode_txid: {
    pos: [159, 193],
    type: FieldType.ALFA,
    size: 35,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de identifica��o do QR Code (TXID)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [194, 240],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
}
