/**
 * Santander CNAB 240 - Segmento Y-53 (Tipo de Pagamento)
 * Registro opcional para configurar pagamento parcial/com faixa de valores (mn/mx ou percentual).
 * Introduzido em Abril/2022.
 * Segmento Y-53 (pos 8 = '3', pos 14 = 'Y', pos 18-19 = '53')
 * 
 * NOTA: Os campos 024/040 (Tipo de valor Informado) tornam os campos 025-039 e 041-055 
 * condicionais - podem ser valores monetrios (N013,2) ou percentuais (N010,5).
 * Fonte do layout: Manual "MANUAL DO CLIENTE DE COBRANA", cdigo H7815, Verso 6, Fevereiro/2023
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const SANTANDER_CNAB240_SEGMENT_Y53: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento Remessa',
    canonical: null,
  },
  registro_opcional_id: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '53',
    description: 'Identificao do Registro Opcional: 53=Tipo de Pagamento',
    canonical: null,
  },
  tipo_pagamento_id: {
    pos: [20, 21],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificao de tipo de Pagamento',
    canonical: null,
  },
  pagamentos_quantidade: {
    pos: [22, 23],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de Pagamentos Possveis',
    canonical: null,
  },
  valor_maximo_tipo: {
    pos: [24, 24],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor Informado: indica se campo seguinte  valor ou percentual',
    canonical: null,
  },
  valor_maximo: {
    pos: [25, 39],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Mximo OU % Percentual (condicional ao tipo em pos 24) - N(13)V99 se valor, N(10)V99999 se percentual',
    canonical: null,
  },
  valor_minimo_tipo: {
    pos: [40, 40],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor Informado: indica se campo seguinte  valor ou percentual',
    canonical: null,
  },
  valor_minimo: {
    pos: [41, 55],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Mnimo OU % Percentual (condicional ao tipo em pos 40) - N(13)V99 se valor, N(10)V99999 se percentual',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [56, 240],
    type: FieldType.NUM,
    size: 185,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
}
