/**
 * Santander (033)  CNAB 400  Detalhe (Registro Tipo 1)
 * Fontes do layout:
 * - brcobranca (Ruby)
 * - cnab_yaml (YAML)
 * - laravel-boleto (PHP) *
 * Nota: O campo percentual_multa (79-82) tem 4 dgitos conforme cnab_yaml e
 * laravel-boleto (comentrio do brcobranca indicava 6 mas foi identificado
 * como desatualizado).
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  codigo_inscricao: {
    pos: [2, 3],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrio do cedente: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao: {
    pos: [4, 17],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do cedente',
    canonical: null,
  },
  codigo_transmissao: {
    pos: [18, 37],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de transmisso (agncia + cdigo cliente + conta)',
    canonical: null,
  },
  numero_controle: {
    pos: [38, 62],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero de controle do participante (uso da empresa)',
    canonical: null,
  },
  nosso_numero: {
    pos: [63, 70],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso nmero (8 dgitos)',
    canonical: 'nossoNumero',
  },
  data_seg_desconto: {
    pos: [71, 76],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: '000000',
    description: 'Data do segundo desconto',
    canonical: null,
  },
  brancos_1: {
    pos: [77, 77],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: ' ',
    description: 'Branco',
    canonical: null,
  },
  codigo_multa: {
    pos: [78, 78],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Indicador de multa: 0=Sem multa, 4=Com multa',
    canonical: null,
  },
  percentual_multa: {
    pos: [79, 82],
    type: FieldType.NUM,
    size: 4,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual de multa (2 decimais implcitas)',
    canonical: null,
  },
  unidade_valor: {
    pos: [83, 84],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Unidade de valor',
    canonical: null,
  },
  valor_outra_unidade: {
    pos: [85, 97],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor em outra unidade',
    canonical: null,
  },
  brancos_2: {
    pos: [98, 101],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: ' ',
    description: 'Brancos',
    canonical: null,
  },
  data_multa: {
    pos: [102, 107],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data para cobrana de multa',
    canonical: null,
  },
  carteira: {
    pos: [108, 108],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo da carteira: 1=Eletrnica, 5=Rpida',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de ocorrncia: 01=Entrada, 02=Baixa, 04=Concesso abatimento, 06=Alterao vencimento',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do documento (identificador livre do cedente)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do ttulo (2 decimais implcitas)',
    canonical: 'valor',
  },
  codigo_banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo do banco cobrador',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00000',
    description: 'Agncia cobradora',
    canonical: null,
  },
  especie: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espcie do documento',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'N',
    description: 'Identificao de aceite: A=Aceite, N=No aceite',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emisso do ttulo',
    canonical: 'dataEmissao',
  },
  instrucao1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira instruo de cobrana',
    canonical: null,
  },
  instrucao2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda instruo de cobrana',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor de juros de mora por dia (2 decimais implcitas)',
    canonical: null,
  },
  desconto_ate: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concesso de desconto',
    canonical: null,
  },
  valor_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do desconto (2 decimais implcitas)',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF (2 decimais implcitas)',
    canonical: null,
  },
  valor_abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento (2 decimais implcitas)',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo documento do sacado: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereo do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (8 dgitos)',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF',
    canonical: 'sacado.endereco.estado',
  },
  sacador_avalista: {
    pos: [352, 381],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do sacador/avalista',
    canonical: null,
  },
  brancos_3: {
    pos: [382, 382],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: ' ',
    description: 'Branco',
    canonical: null,
  },
  id_complemento: {
    pos: [383, 383],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'I',
    description: 'Identificao de complemento',
    canonical: null,
  },
  complemento_conta: {
    pos: [384, 385],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Complemento da conta (ltimo dgito + DV)',
    canonical: null,
  },
  brancos_4: {
    pos: [386, 391],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: ' ',
    description: 'Brancos',
    canonical: null,
  },
  prazo: {
    pos: [392, 393],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prazo em dias para protesto',
    canonical: null,
  },
  brancos_5: {
    pos: [394, 394],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: ' ',
    description: 'Branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial do registro',
    canonical: null,
  },
}
