/**
 * Santander (033)  CNAB 400  Header de Arquivo (Remessa)
 * Fontes do layout:
 * - Manual oficial Santander (Santander_Layout-Cobranca-400-posicoes-jul-2025-Portugues.pdf,
 *   v2.36)  revelou 5 campos de mensagem nas posies 117-351
 * - brcobranca (Ruby)
 * - cnab_yaml (YAML)
 * - laravel-boleto (PHP)
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const HEADER: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificao do registro header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operao: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Cdigo de servio: 01=Cobrana',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de servio',
    canonical: null,
  },
  codigo_transmissao: {
    pos: [27, 46],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de transmisso (agncia + cdigo cliente + conta)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficirio',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo FEBRABAN do Santander',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'SANTANDER',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de gerao do arquivo',
    canonical: 'dataGeracao',
  },
  zeros: {
    pos: [101, 116],
    type: FieldType.NUM,
    size: 16,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Zeros (branco)',
    canonical: null,
  },
  mensagem_1: {
    pos: [117, 163],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira mensagem livre (47 caracteres - revelado no manual jul/2025 v2.36)',
    canonical: null,
  },
  mensagem_2: {
    pos: [164, 210],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda mensagem livre (47 caracteres - revelado no manual jul/2025 v2.36)',
    canonical: null,
  },
  mensagem_3: {
    pos: [211, 257],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Terceira mensagem livre (47 caracteres - revelado no manual jul/2025 v2.36)',
    canonical: null,
  },
  mensagem_4: {
    pos: [258, 304],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quarta mensagem livre (47 caracteres - revelado no manual jul/2025 v2.36)',
    canonical: null,
  },
  mensagem_5: {
    pos: [305, 351],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quinta mensagem livre (47 caracteres - revelado no manual jul/2025 v2.36)',
    canonical: null,
  },
  reservado_1: {
    pos: [352, 385],
    type: FieldType.ALFA,
    size: 34,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado/filler (34 caracteres)',
    canonical: null,
  },
  reservado_2: {
    pos: [386, 391],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado/filler (6 caracteres)',
    canonical: null,
  },
  numero_versao: {
    pos: [392, 394],
    type: FieldType.ALFA,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000',
    description: 'Nmero da verso do layout',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Sequencial do registro (sempre 1 no header)',
    canonical: null,
  },
}
