/**
 * Bradesco CNAB 240 - Segmento R
 * Segmento R (pos 8 = '3', pos 14 = 'R')
 * Descontos adicionais (2º e 3º descontos), multa, informações ao sacado
 * e dados de débito autom?tico em conta corrente.
 * Este segmento é opcional e aparece quando ha descontos adicionais além do primeiro,
 * multa configurada, ou quando o título está vinculado a débito automático.
 * Fonte do layout: pycnab240 + laravel-boleto + manual oficial Bradesco
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_SEGMENT_R: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de serviço',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Segmento R = descontos/multa/débito automático',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento da remessa',
    canonical: null,
  },
  desconto2_codigo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do segundo desconto: 0=Sem, 1=Valor fixo, 2=Percentual',
    canonical: null,
  },
  desconto2_data: {
    pos: [19, 26],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para segundo desconto',
    canonical: null,
  },
  desconto2_valor: {
    pos: [27, 41],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do segundo desconto',
    canonical: null,
  },
  desconto3_codigo: {
    pos: [42, 42],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do terceiro desconto: 0=Sem, 1=Valor fixo, 2=Percentual',
    canonical: null,
  },
  desconto3_data: {
    pos: [43, 50],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para terceiro desconto',
    canonical: null,
  },
  desconto3_valor: {
    pos: [51, 65],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do terceiro desconto',
    canonical: null,
  },
  multa_codigo: {
    pos: [66, 66],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código da multa: 0=Isento, 1=Valor fixo, 2=Percentual',
    canonical: {
      field: 'multa.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2) return 'percentual'
        return undefined
      },
    },
  },
  multa_data: {
    pos: [67, 74],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de in?cio da cobrança de multa',
    canonical: 'multa.vigenciaAPartirDe',
  },
  multa_valor: {
    pos: [75, 89],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual da multa',
    canonical: 'multa.valor',
  },
  informacao_sacado_1: {
    pos: [90, 99],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informação ao sacado (linha 1)',
    canonical: null,
  },
  informacao_sacado_2: {
    pos: [100, 139],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informação ao sacado (linha 2)',
    canonical: null,
  },
  informacao_sacado_3: {
    pos: [140, 179],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informação ao sacado (linha 3)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [180, 199],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  debito_automatico_codigo_ocorrencia: {
    pos: [200, 207],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código de ocorrência do d?bito autom?tico',
    canonical: null,
  },
  debito_automatico_banco: {
    pos: [208, 210],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Banco para débito autom?tico',
    canonical: null,
  },
  debito_automatico_agencia: {
    pos: [211, 215],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag?ncia para débito autom?tico',
    canonical: null,
  },
  debito_automatico_agencia_dv: {
    pos: [216, 216],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D?gito verificador da agência',
    canonical: null,
  },
  debito_automatico_conta: {
    pos: [217, 228],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente para débito autom?tico',
    canonical: null,
  },
  debito_automatico_conta_dv: {
    pos: [229, 229],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D?gito verificador da conta',
    canonical: null,
  },
  debito_automatico_agencia_conta_dv: {
    pos: [230, 230],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D?gito verificador da agência/conta',
    canonical: null,
  },
  aviso_debito_automatico: {
    pos: [231, 231],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aviso para débito autom?tico: 0=Não, 1=Sim',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [232, 240],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
