/**
 * Bradesco CNAB 240 - Segmento Y-50
 * Registro Detalhe - Segmento Y-50 (Rateio de Crédito)
 * 
 * Registro opcional (Remessa/Retorno) que define o rateio de crédito de um título
 * entre múltiplas contas. Pode ocorrer várias vezes por título, permitindo distribuir
 * o valor entre diferentes beneficiários.
 * Este segmento permite que o valor de um título seja automaticamente dividido e
 * creditado em diferentes contas bancárias conforme percentuais ou valores fixos
 * definidos.
 * Estrutura:
 *   - Controle: banco (237), lote, registro tipo 3 (detalhe), segmento 'Y'
 *   - Código de registro opcional: '50' (identifica que é o Y-50)
 *   - Dados da conta de rateio: agência, conta e dígitos verificadores
 *   - Identificação do título: mesmo padrão do Segmento P (produto+zeros+nosso número+dígito)
 *   - Tipo de rateio: por valor ou por percentual
 *   - Dados do crédito: banco destino, agência, conta
 *   - Informações adicionais: nome do beneficiário, data de crédito, floating
 * Observação sobre valor_ou_percentual_rateio:
 * Segundo o manual, este campo tem formato variável conforme tipo_valor_informado:
 * - Se tipo = valor: formato 13.2 (13 dígitos inteiros, 2 decimais)
 * - Se tipo = percentual: formato 12.3 (12 dígitos inteiros, 3 decimais)
 * Para simplicidade do schema, mantemos decimais=2 como padrão.
 * A aplicação deve tratar a exceção do percentual internamente se necessário.
 * Fonte: Manual oficial Bradesco CNAB 240, versão 04, dez/2024
 * Seção: "Registro Detalhe - Segmento Y-50"
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const BRADESCO_CNAB240_SEGMENT_Y50: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de serviço',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento da remessa',
    canonical: null,
  },
  codigo_registro_opcional: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '50',
    description: 'Código do registro opcional: 50=Rateio de crédito',
    canonical: null,
  },
  rateio_agencia: {
    pos: [20, 24],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência da conta de rateio',
    canonical: null,
  },
  rateio_agencia_dv: {
    pos: [25, 25],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência',
    canonical: null,
  },
  rateio_conta: {
    pos: [26, 37],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente de rateio',
    canonical: null,
  },
  rateio_conta_dv: {
    pos: [38, 38],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },
  rateio_agencia_conta_dv: {
    pos: [39, 39],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência/conta',
    canonical: null,
  },
  identificacao_titulo_banco: {
    pos: [40, 59],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação completa do título no banco (carteira + produto + nosso número + dígito). Mesmo padrão do Segmento P: pode ser decomposto em carteira/produto(3), zeros(5), nosso número(12)',
    canonical: null,
  },
  codigo_calculo_rateio: {
    pos: [60, 60],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de cálculo do rateio: 1=Valor informado, 2=Percentual informado',
    canonical: null,
  },
  tipo_valor_informado: {
    pos: [61, 61],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor: 1=Valor fixo, 2=Percentual',
    canonical: null,
  },
  valor_ou_percentual_rateio: {
    pos: [62, 76],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do rateio. Formato: 13.2 se valor fixo, 12.3 se percentual (schema usa decimais=2 por padrão, aplicação deve ajustar para percentual)',
    canonical: null,
  },
  codigo_banco_credito: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código FEBRABAN do banco de crédito (destino do rateio)',
    canonical: null,
  },
  rateio_credito_agencia: {
    pos: [80, 84],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência do crédito de rateio',
    canonical: null,
  },
  rateio_credito_agencia_dv: {
    pos: [85, 85],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência de crédito',
    canonical: null,
  },
  rateio_credito_conta: {
    pos: [86, 97],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente de crédito do rateio',
    canonical: null,
  },
  rateio_credito_conta_dv: {
    pos: [98, 98],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta de crédito',
    canonical: null,
  },
  rateio_credito_agencia_conta_dv: {
    pos: [99, 99],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência/conta de crédito',
    canonical: null,
  },
  nome_beneficiario_rateio: {
    pos: [100, 139],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficiário do rateio',
    canonical: null,
  },
  identificacao_parcela: {
    pos: [140, 145],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da parcela (formato: parcela atual / total de parcelas)',
    canonical: null,
  },
  floating_dias_credito: {
    pos: [146, 148],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de dias para floating (postergação) do crédito',
    canonical: null,
  },
  data_credito: {
    pos: [149, 156],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data efetiva do crédito do rateio',
    canonical: null,
  },
  motivo_ocorrencia: {
    pos: [157, 166],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código de motivo da ocorrência (retorno)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [167, 240],
    type: FieldType.ALFA,
    size: 74,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
