/**
 * Bradesco CNAB 240 - Segmento Y-50
 * Registro Detalhe - Segmento Y-50 (Rateio de Cr�dito)
 * 
 * Registro opcional (Remessa/Retorno) que define o rateio de cr�dito de um t�tulo
 * entre m�ltiplas contas. Pode ocorrer v�rias vezes por t�tulo, permitindo distribuir
 * o valor entre diferentes benefici�rios.
 * Este segmento permite que o valor de um t�tulo seja automaticamente dividido e
 * creditado em diferentes contas banc�rias conforme percentuais ou valores fixos
 * definidos.
 * Estrutura:
 *   - Controle: banco (237), lote, registro tipo 3 (detalhe), segmento 'Y'
 *   - C�digo de registro opcional: '50' (identifica que � o Y-50)
 *   - Dados da conta de rateio: ag�ncia, conta e d�gitos verificadores
 *   - Identifica��o do t�tulo: mesmo padr�o do Segmento P (produto+zeros+nosso n�mero+d�gito)
 *   - Tipo de rateio: por valor ou por percentual
 *   - Dados do cr�dito: banco destino, ag�ncia, conta
 *   - Informa��es adicionais: nome do benefici�rio, data de cr�dito, floating
 * Observa��o sobre valor_ou_percentual_rateio:
 * Segundo o manual, este campo tem formato vari�vel conforme tipo_valor_informado:
 * - Se tipo = valor: formato 13.2 (13 d�gitos inteiros, 2 decimais)
 * - Se tipo = percentual: formato 12.3 (12 d�gitos inteiros, 3 decimais)
 * Para simplicidade do schema, mantemos decimais=2 como padr�o.
 * A aplica��o deve tratar a exce��o do percentual internamente se necess�rio.
 * Fonte: Manual oficial Bradesco CNAB 240, vers�o 04, dez/2024
 * Se��o: "Registro Detalhe - Segmento Y-50"
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_SEGMENT_Y50: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de servi�o',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento da remessa',
    canonical: null,
  },
  codigo_registro_opcional: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '50',
    description: 'C�digo do registro opcional: 50=Rateio de cr�dito',
    canonical: null,
  },
  rateio_agencia: {
    pos: [20, 24],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia da conta de rateio',
    canonical: null,
  },
  rateio_agencia_dv: {
    pos: [25, 25],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia',
    canonical: null,
  },
  rateio_conta: {
    pos: [26, 37],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente de rateio',
    canonical: null,
  },
  rateio_conta_dv: {
    pos: [38, 38],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta',
    canonical: null,
  },
  rateio_agencia_conta_dv: {
    pos: [39, 39],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia/conta',
    canonical: null,
  },
  identificacao_titulo_banco: {
    pos: [40, 59],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o completa do t�tulo no banco (carteira + produto + nosso n�mero + d�gito). Mesmo padr�o do Segmento P: pode ser decomposto em carteira/produto(3), zeros(5), nosso n�mero(12)',
    canonical: null,
  },
  codigo_calculo_rateio: {
    pos: [60, 60],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de c�lculo do rateio: 1=Valor informado, 2=Percentual informado',
    canonical: null,
  },
  tipo_valor_informado: {
    pos: [61, 61],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor: 1=Valor fixo, 2=Percentual',
    canonical: null,
  },
  valor_ou_percentual_rateio: {
    pos: [62, 76],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do rateio. Formato: 13.2 se valor fixo, 12.3 se percentual (schema usa decimais=2 por padr�o, aplica��o deve ajustar para percentual)',
    canonical: null,
  },
  codigo_banco_credito: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo FEBRABAN do banco de cr�dito (destino do rateio)',
    canonical: null,
  },
  rateio_credito_agencia: {
    pos: [80, 84],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia do cr�dito de rateio',
    canonical: null,
  },
  rateio_credito_agencia_dv: {
    pos: [85, 85],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia de cr�dito',
    canonical: null,
  },
  rateio_credito_conta: {
    pos: [86, 97],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente de cr�dito do rateio',
    canonical: null,
  },
  rateio_credito_conta_dv: {
    pos: [98, 98],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta de cr�dito',
    canonical: null,
  },
  rateio_credito_agencia_conta_dv: {
    pos: [99, 99],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia/conta de cr�dito',
    canonical: null,
  },
  nome_beneficiario_rateio: {
    pos: [100, 139],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do benefici�rio do rateio',
    canonical: null,
  },
  identificacao_parcela: {
    pos: [140, 145],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o da parcela (formato: parcela atual / total de parcelas)',
    canonical: null,
  },
  floating_dias_credito: {
    pos: [146, 148],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de dias para floating (posterga��o) do cr�dito',
    canonical: null,
  },
  data_credito: {
    pos: [149, 156],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data efetiva do cr�dito do rateio',
    canonical: null,
  },
  motivo_ocorrencia: {
    pos: [157, 166],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de motivo da ocorr�ncia (retorno)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [167, 240],
    type: FieldType.ALFA,
    size: 74,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
