/**
 * Bradesco CNAB 240 - Segmento Y-01
 * Registro Detalhe - Segmento Y-01 (Benefici�rio Final)
 * 
 * Registro opcional (Remessa/Retorno) que traz as informa��es completas do Benefici�rio Final,
 * incluindo endere�o completo. Este registro � diferente do Segmento Q, que apenas cont�m
 * tipo/n�mero/nome do sacador/avalista (que pode ser o benefici�rio final).
 * O Segmento Y-01 � usado quando h� necessidade de identificar o benefici�rio final da transa��o
 * com dados completos de endere�o, conforme exig�ncias regulat�rias ou contratuais.
 * Estrutura:
 *   - Controle: banco (237), lote, registro tipo 3 (detalhe), segmento 'Y'
 *   - C�digo de registro opcional: '01' (identifica que � o Y-01)
 *   - Dados do benefici�rio final: tipo/n�mero inscri��o, nome completo, endere�o completo
 * Fonte: Manual oficial Bradesco CNAB 240, vers�o 04, dez/2024
 * Se��o: "Registro Detalhe - Segmento Y-01"
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_SEGMENT_Y01: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de servi�o',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento da remessa',
    canonical: null,
  },
  codigo_registro_opcional: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'C�digo do registro opcional: 01=Benefici�rio Final',
    canonical: null,
  },
  beneficiario_final_inscricao_tipo: {
    pos: [20, 20],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_inscricao_numero: {
    pos: [21, 35],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do benefici�rio final',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [36, 75],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do benefici�rio final',
    canonical: null,
  },
  beneficiario_final_endereco: {
    pos: [76, 115],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do benefici�rio final',
    canonical: null,
  },
  beneficiario_final_bairro: {
    pos: [116, 130],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do benefici�rio final',
    canonical: null,
  },
  beneficiario_final_cep: {
    pos: [131, 135],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (5 d�gitos)',
    canonical: null,
  },
  beneficiario_final_cep_sufixo: {
    pos: [136, 138],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP sufixo (3 d�gitos)',
    canonical: null,
  },
  beneficiario_final_cidade: {
    pos: [139, 153],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do benefici�rio final',
    canonical: null,
  },
  beneficiario_final_uf: {
    pos: [154, 155],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do benefici�rio final',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [156, 240],
    type: FieldType.ALFA,
    size: 85,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
