/* *
 * Primeira linha de cada lote. Agrupa ttulos (boletos) que pertencem
 * ao mesmo tipo de servio (cobrana, pagamento, etc.).
 * Lote: nmero sequencial (0001, 0002, ...)
 * 
 * Baseado em:
 * - Manual "Layout Padro 240  Cobrana, Verso 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const SANTANDER_CNAB240_BATCH_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do lote (0001, 0002...)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo: 1=Header de Lote',
    canonical: null,
  },
  servico_operacao: {
    pos: [9, 9],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Tipo de operao: R=Remessa, T=Retorno',
    canonical: null,
  },
  servico_tipo: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Tipo de servio: 01=Cobrana',
    canonical: null,
  },
  servico_forma: {
    pos: [12, 13],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) - Manual 2023: brancos',
    canonical: null,
  },
  servico_layout: {
    pos: [14, 16],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '030',
    description: 'Verso do layout do lote (030 para CNAB 240 - Manual 2023)',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [17, 17],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrio: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do CPF/CNPJ do cedente',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [34, 53],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  codigo_transmissao: {
    pos: [54, 68],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de transmisso (agncia + "0000" + cdigo do cliente)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [69, 73],
    type: FieldType.ALFA,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  cedente_nome: {
    pos: [74, 103],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa/cedente',
    canonical: null,
  },
  mensagem_1: {
    pos: [104, 143],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 1 para todos os boletos do lote',
    canonical: null,
  },
  mensagem_2: {
    pos: [144, 183],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 para todos os boletos do lote',
    canonical: null,
  },
  numero_remessa_retorno: {
    pos: [184, 191],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial da remessa ou retorno',
    canonical: null,
  },
  data_gravacao: {
    pos: [192, 199],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de gravao do lote',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [200, 240],
    type: FieldType.ALFA,
    size: 41,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
