/* *
 * Primeira linha do arquivo CNAB. Contm identificao do banco,
 * dados do cedente (beneficirio) e informaes sobre o arquivo.
 * Lote: 0000
 * 
 * Baseado em:
 * - Manual "Layout Padro 240  Cobrana, Verso 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const SANTANDER_CNAB240_FILE_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0000',
    description: 'Lote 0000 = header de arquivo',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Tipo: 0=Header de Arquivo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 16],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [17, 17],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrio: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [18, 32],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do CPF/CNPJ do cedente',
    canonical: 'cedente.documento',
  },
  codigo_transmissao: {
    pos: [33, 47],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de transmisso (agncia + "0000" + cdigo do cliente)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [48, 72],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  cedente_nome: {
    pos: [73, 102],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa/cedente',
    canonical: 'cedente.nome',
  },
  nome_do_banco: {
    pos: [103, 132],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BANCO SANTANDER',
    description: 'Nome do banco',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [133, 142],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  arquivo_codigo: {
    pos: [143, 143],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Cdigo do arquivo: 1=Remessa, 2=Retorno',
    canonical: null,
  },
  arquivo_data_de_geracao: {
    pos: [144, 151],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de gerao do arquivo',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [152, 157],
    type: FieldType.ALFA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (hora no existe no Santander)',
    canonical: null,
  },
  arquivo_sequencia: {
    pos: [158, 163],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do arquivo',
    canonical: null,
  },
  arquivo_layout: {
    pos: [164, 166],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '040',
    description: 'Verso do layout (040 para CNAB 240)',
    canonical: null,
  },
  // Manual 2023: bloco nico "Reservado (uso Banco)", brancos. Verses anteriores
  // do schema subdividiam essa faixa em densidade/reservado_banco/reservado_empresa,
  // mas o manual e a maioria das fontes de terceiros (pycnab240, laravel-boleto)
  // tratam como um campo nico de 74 bytes.
  cnab_exclusivo_5: {
    pos: [167, 240],
    type: FieldType.ALFA,
    size: 74,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) - Manual 2023',
    canonical: null,
  },
}
