/**
 * Schema do Segmento P - Santander CNAB 240
 * 
 * Contém os dados financeiros do título (boleto): valor, vencimento,
 * nosso número, juros, descontos, etc.
 * 
 * Tipo de registro: 3 (detalhe)
 * Segmento: P
 * 
 * Baseado em:
 * - Manual "Layout Padrão 240 – Cobrança, Versão 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema } from '../../../../types'

export const SANTANDER_CNAB240_SEGMENT_P: RecordSchema = {
  // ========== CONTROLE (1-17) ==========
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Código FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'P',
    description: 'Segmento P = dados do título',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento da remessa (variável: 01=Entrada, 02=Baixa, 04=Abatimento, etc.)',
    canonical: null,
  },

  // ========== DADOS DO CEDENTE (18-44) - Estrutura Santander Manual 2023 ==========
  cedente_agencia: {
    pos: [18, 21],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência Destinatária (Santander usa 4 dígitos)',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [22, 22],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito da Agência Destinatária',
    canonical: null,
  },
  cedente_conta: {
    pos: [23, 31],
    type: 'num',
    size: 9,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente (Santander usa 9 dígitos)',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [32, 32],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },

  // ========== CONTA COBRANÇA FIDC (33-42) - Específico Santander ==========
  conta_cobranca: {
    pos: [33, 41],
    type: 'num',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta cobrança Destinatária FIDC (Santander, 9 dígitos)',
    canonical: null,
  },
  conta_cobranca_dv: {
    pos: [42, 42],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito da conta cobrança FIDC',
    canonical: null,
  },

  // ========== RESERVADO (43-44) ==========
  cnab_exclusivo_3: {
    pos: [43, 44],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },

  // ========== NOSSO NÚMERO (45-57) ==========
  nosso_numero: {
    pos: [45, 57],
    type: 'num',
    size: 13,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título no banco (Nosso Número)',
    canonical: 'nossoNumero',
  },

  // ========== CARTEIRA/COBRANÇA (58-62) ==========
  tipo_cobranca: {
    pos: [58, 58],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de cobrança: 1=Simples, 3=Caucionada, etc.',
    canonical: null,
  },
  forma_cadastramento: {
    pos: [59, 59],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Forma de cadastramento: 1=Com registro',
    canonical: null,
  },
  tipo_documento: {
    pos: [60, 60],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de documento',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [61, 62],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) - Manual 2023',
    canonical: null,
  },

  // ========== NÚMERO DO DOCUMENTO (63-77) ==========
  numero_documento: {
    pos: [63, 77],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento de cobrança (seu número)',
    canonical: 'numeroDocumento',
  },

  // ========== VENCIMENTO E VALOR (78-100) ==========
  vencimento_titulo: {
    pos: [78, 85],
    type: 'data',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data de vencimento do título',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [86, 100],
    type: 'num',
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor nominal do título',
    canonical: 'valor',
  },

  // ========== AGÊNCIA COBRADORA (101-106) ==========
  agencia_cobradora: {
    pos: [101, 104],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência encarregada da cobrança FIDC',
    canonical: null,
  },
  agencia_cobradora_dv: {
    pos: [105, 105],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito da Agência do Beneficiário FIDC',
    canonical: null,
  },
  cnab_exclusivo_6: {
    pos: [106, 106],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },

  // ========== ESPÉCIE E ACEITE (107-109) ==========
  especie_titulo: {
    pos: [107, 108],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '02',
    description: 'Espécie do título: 01=DM, 02=NP, etc.',
    canonical: null,
  },
  aceite: {
    pos: [109, 109],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Identificação de aceite: A=Aceite, N=Não aceite',
    canonical: null,
  },

  // ========== DATA DE EMISSÃO (110-117) ==========
  data_emissao_titulo: {
    pos: [110, 117],
    type: 'data',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data de emissão do título',
    canonical: 'dataEmissao',
  },

  // ========== JUROS DE MORA (118-141) ==========
  juros_mora_codigo: {
    pos: [118, 118],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Código de juros: 0=Isento, 1=Valor/dia, 2=%/mês',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2 || code === 3) return 'percentual'
        return undefined
      },
    },
  },
  juros_mora_data: {
    pos: [119, 126],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data a partir da qual incide juros',
    canonical: 'juros.vigenciaAPartirDe',
  },
  juros_mora_valor: {
    pos: [127, 141],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de juros por dia/mês',
    canonical: 'juros.valor',
  },

  // ========== DESCONTO (142-165) ==========
  desconto_codigo: {
    pos: [142, 142],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Código de desconto: 0=Sem, 1=Valor fixo, 2=%',
    canonical: null,
  },
  desconto_data: {
    pos: [143, 150],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data limite para desconto',
    canonical: null,
  },
  desconto_valor: {
    pos: [151, 165],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto',
    canonical: 'desconto.valor',
  },

  // ========== IOF (166-180) ==========
  iof_percentual: {
    pos: [166, 180],
    type: 'num',
    size: 15,
    decimals: 5,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual do IOF a ser recolhido (5 casas decimais — Nota 18 do manual). Preenchido apenas quando o Beneficiário não possui cadastro de IOF no perfil do convênio.',
    canonical: null,
  },

  // ========== ABATIMENTO (181-195) ==========
  abatimento_valor: {
    pos: [181, 195],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },

  // ========== IDENTIFICAÇÃO DO TÍTULO NA EMPRESA (196-220) ==========
  identificacao_titulo: {
    pos: [196, 220],
    type: 'alfa',
    size: 25,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título na empresa',
    canonical: null,
  },

  // ========== PROTESTO (221-223) ==========
  protesto_codigo: {
    pos: [221, 221],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Código de protesto: 0=Não protestar',
    canonical: null,
  },
  protesto_prazo: {
    pos: [222, 223],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prazo em dias para protesto',
    canonical: null,
  },

  // ========== BAIXA/DEVOLUÇÃO (224-227) ==========
  baixa_codigo: {
    pos: [224, 224],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Código de baixa: 0=Não baixar',
    canonical: null,
  },
  cnab_exclusivo_7: {
    pos: [225, 225],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) — zero fixo',
    canonical: null,
  },
  baixa_prazo: {
    pos: [226, 227],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de dias para Baixa/Devolução',
    canonical: null,
  },

  // ========== MOEDA (228-229) ==========
  moeda_codigo: {
    pos: [228, 229],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '09',
    description: 'Código da moeda: 09=Real',
    canonical: null,
  },

  // ========== RESERVADO (230-240) ==========
  cnab_exclusivo_5: {
    pos: [230, 240],
    type: 'alfa',
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
