/* *
 * Contm os dados financeiros do ttulo (boleto): valor, vencimento,
 * nosso nmero, juros, descontos, etc.
 * Segmento: P
 * 
 * Baseado em:
 * - Manual "Layout Padro 240  Cobrana, Verso 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const SANTANDER_CNAB240_SEGMENT_P: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Cdigo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'P',
    description: 'Segmento P = dados do ttulo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento da remessa (varivel: 01=Entrada, 02=Baixa, 04=Abatimento, etc.)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [18, 21],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agncia Destinatria (Santander usa 4 dgitos)',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [22, 22],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dgito da Agncia Destinatria',
    canonical: null,
  },
  cedente_conta: {
    pos: [23, 31],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero da conta corrente (Santander usa 9 dgitos)',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [32, 32],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dgito verificador da conta',
    canonical: null,
  },
  conta_cobranca: {
    pos: [33, 41],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta cobrana Destinatria FIDC (Santander, 9 dgitos)',
    canonical: null,
  },
  conta_cobranca_dv: {
    pos: [42, 42],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dgito da conta cobrana FIDC',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [43, 44],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  nosso_numero: {
    pos: [45, 57],
    type: FieldType.NUM,
    size: 13,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificao do ttulo no banco (Nosso Nmero)',
    canonical: 'nossoNumero',
  },
  tipo_cobranca: {
    pos: [58, 58],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de cobrana: 1=Simples, 3=Caucionada, etc.',
    canonical: null,
  },
  forma_cadastramento: {
    pos: [59, 59],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Forma de cadastramento: 1=Com registro',
    canonical: null,
  },
  tipo_documento: {
    pos: [60, 60],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de documento',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [61, 62],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) - Manual 2023',
    canonical: null,
  },
  numero_documento: {
    pos: [63, 77],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do documento de cobrana (seu nmero)',
    canonical: 'numeroDocumento',
  },
  vencimento_titulo: {
    pos: [78, 85],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de vencimento do ttulo',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [86, 100],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor nominal do ttulo',
    canonical: 'valor',
  },
  agencia_cobradora: {
    pos: [101, 104],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agncia encarregada da cobrana FIDC',
    canonical: null,
  },
  agencia_cobradora_dv: {
    pos: [105, 105],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dgito da Agncia do Beneficirio FIDC',
    canonical: null,
  },
  cnab_exclusivo_6: {
    pos: [106, 106],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  especie_titulo: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '02',
    description: 'Espcie do ttulo: 01=DM, 02=NP, etc.',
    canonical: null,
  },
  aceite: {
    pos: [109, 109],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Identificao de aceite: A=Aceite, N=No aceite',
    canonical: null,
  },
  data_emissao_titulo: {
    pos: [110, 117],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de emisso do ttulo',
    canonical: 'dataEmissao',
  },
  juros_mora_codigo: {
    pos: [118, 118],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Cdigo de juros: 0=Isento, 1=Valor/dia, 2=%/ms',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2 || code === 3) return 'percentual'
        return undefined
      },
    },
  },
  juros_mora_data: {
    pos: [119, 126],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data a partir da qual incide juros',
    canonical: 'juros.vigenciaAPartirDe',
  },
  juros_mora_valor: {
    pos: [127, 141],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de juros por dia/ms',
    canonical: 'juros.valor',
  },
  desconto_codigo: {
    pos: [142, 142],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Cdigo de desconto: 0=Sem, 1=Valor fixo, 2=%',
    canonical: null,
  },
  desconto_data: {
    pos: [143, 150],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para desconto',
    canonical: null,
  },
  desconto_valor: {
    pos: [151, 165],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto',
    canonical: 'desconto.valor',
  },
  iof_percentual: {
    pos: [166, 180],
    type: FieldType.NUM,
    size: 15,
    decimals: 5,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual do IOF a ser recolhido (5 casas decimais  Nota 18 do manual). Preenchido apenas quando o Beneficirio no possui cadastro de IOF no perfil do convnio.',
    canonical: null,
  },
  abatimento_valor: {
    pos: [181, 195],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  identificacao_titulo: {
    pos: [196, 220],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificao do ttulo na empresa',
    canonical: null,
  },
  protesto_codigo: {
    pos: [221, 221],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Cdigo de protesto: 0=No protestar',
    canonical: null,
  },
  protesto_prazo: {
    pos: [222, 223],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prazo em dias para protesto',
    canonical: null,
  },
  baixa_codigo: {
    pos: [224, 224],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Cdigo de baixa: 0=No baixar',
    canonical: null,
  },
  cnab_exclusivo_7: {
    pos: [225, 225],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)  zero fixo',
    canonical: null,
  },
  baixa_prazo: {
    pos: [226, 227],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero de dias para Baixa/Devoluo',
    canonical: null,
  },
  moeda_codigo: {
    pos: [228, 229],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '09',
    description: 'Cdigo da moeda: 09=Real',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [230, 240],
    type: FieldType.ALFA,
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
