/* *
 * Cont�m os dados financeiros do t�tulo (boleto): valor, vencimento,
 * nosso n�mero, juros, descontos, etc.
 * Segmento: P
 * 
 * Baseado em:
 * - Manual "Layout Padr�o 240 � Cobran�a, Vers�o 2.5" (Setembro/2014)
 * - pycnab240, laravel-boleto, brcobranca, cnab_yaml
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SANTANDER_CNAB240_SEGMENT_P: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'C�digo FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'P',
    description: 'Segmento P = dados do t�tulo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento da remessa (vari�vel: 01=Entrada, 02=Baixa, 04=Abatimento, etc.)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [18, 21],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia Destinat�ria (Santander usa 4 d�gitos)',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [22, 22],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito da Ag�ncia Destinat�ria',
    canonical: null,
  },
  cedente_conta: {
    pos: [23, 31],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero da conta corrente (Santander usa 9 d�gitos)',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [32, 32],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta',
    canonical: null,
  },
  conta_cobranca: {
    pos: [33, 41],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta cobran�a Destinat�ria FIDC (Santander, 9 d�gitos)',
    canonical: null,
  },
  conta_cobranca_dv: {
    pos: [42, 42],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito da conta cobran�a FIDC',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [43, 44],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  nosso_numero: {
    pos: [45, 57],
    type: FieldType.NUM,
    size: 13,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo no banco (Nosso N�mero)',
    canonical: 'nossoNumero',
  },
  tipo_cobranca: {
    pos: [58, 58],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de cobran�a: 1=Simples, 3=Caucionada, etc.',
    canonical: null,
  },
  forma_cadastramento: {
    pos: [59, 59],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Forma de cadastramento: 1=Com registro',
    canonical: null,
  },
  tipo_documento: {
    pos: [60, 60],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de documento',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [61, 62],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) - Manual 2023',
    canonical: null,
  },
  numero_documento: {
    pos: [63, 77],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do documento de cobran�a (seu n�mero)',
    canonical: 'numeroDocumento',
  },
  vencimento_titulo: {
    pos: [78, 85],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de vencimento do t�tulo',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [86, 100],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor nominal do t�tulo',
    canonical: 'valor',
  },
  agencia_cobradora: {
    pos: [101, 104],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia encarregada da cobran�a FIDC',
    canonical: null,
  },
  agencia_cobradora_dv: {
    pos: [105, 105],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito da Ag�ncia do Benefici�rio FIDC',
    canonical: null,
  },
  cnab_exclusivo_6: {
    pos: [106, 106],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  especie_titulo: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '02',
    description: 'Esp�cie do t�tulo: 01=DM, 02=NP, etc.',
    canonical: null,
  },
  aceite: {
    pos: [109, 109],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Identifica��o de aceite: A=Aceite, N=N�o aceite',
    canonical: null,
  },
  data_emissao_titulo: {
    pos: [110, 117],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de emiss�o do t�tulo',
    canonical: 'dataEmissao',
  },
  juros_mora_codigo: {
    pos: [118, 118],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo de juros: 0=Isento, 1=Valor/dia, 2=%/m�s',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2 || code === 3) return 'percentual'
        return undefined
      },
    },
  },
  juros_mora_data: {
    pos: [119, 126],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data a partir da qual incide juros',
    canonical: 'juros.vigenciaAPartirDe',
  },
  juros_mora_valor: {
    pos: [127, 141],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de juros por dia/m�s',
    canonical: 'juros.valor',
  },
  desconto_codigo: {
    pos: [142, 142],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo de desconto: 0=Sem, 1=Valor fixo, 2=%',
    canonical: null,
  },
  desconto_data: {
    pos: [143, 150],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para desconto',
    canonical: null,
  },
  desconto_valor: {
    pos: [151, 165],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de desconto',
    canonical: 'desconto.valor',
  },
  iof_percentual: {
    pos: [166, 180],
    type: FieldType.NUM,
    size: 15,
    decimals: 5,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual do IOF a ser recolhido (5 casas decimais � Nota 18 do manual). Preenchido apenas quando o Benefici�rio n�o possui cadastro de IOF no perfil do conv�nio.',
    canonical: null,
  },
  abatimento_valor: {
    pos: [181, 195],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  identificacao_titulo: {
    pos: [196, 220],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo na empresa',
    canonical: null,
  },
  protesto_codigo: {
    pos: [221, 221],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo de protesto: 0=N�o protestar',
    canonical: null,
  },
  protesto_prazo: {
    pos: [222, 223],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prazo em dias para protesto',
    canonical: null,
  },
  baixa_codigo: {
    pos: [224, 224],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'C�digo de baixa: 0=N�o baixar',
    canonical: null,
  },
  cnab_exclusivo_7: {
    pos: [225, 225],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco) � zero fixo',
    canonical: null,
  },
  baixa_prazo: {
    pos: [226, 227],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de dias para Baixa/Devolu��o',
    canonical: null,
  },
  moeda_codigo: {
    pos: [228, 229],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '09',
    description: 'C�digo da moeda: 09=Real',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [230, 240],
    type: FieldType.ALFA,
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
