/**
 * Santander CNAB 240 - Segmento S (Mensagens/Formulário Especial)
 * 
 * Registro opcional para mensagens de impressão no boleto.
 * Possui duas variantes mutuamente exclusivas identificadas pelo campo pos 18:
 * - Variante 1 (pos 18 = '1'): Formulário Especial
 * - Variante 2 (pos 18 = '2'): Mensagens fixas (blocos de 40 caracteres)
 * 
 * Segmento S (pos 8 = '3', pos 14 = 'S')
 * 
 * Fonte do layout: Manual "MANUAL DO CLIENTE DE COBRANÇA", código H7815, Versão 6, Fevereiro/2023
 */

import { RecordSchema } from '../../../../types'

// ========== SCHEMA BASE (campos comuns posições 1-17) ==========
export const SANTANDER_CNAB240_SEGMENT_S: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '033',
    description: 'Código FEBRABAN do Santander',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'S',
    description: 'Segmento S = mensagens/formulário',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento Remessa',
    canonical: null,
  },
  identificacao_impressao: {
    pos: [18, 18],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da impressão: 1=Formulário Especial, 2=Mensagens fixas',
    canonical: null,
  },
}

// ========== VARIANTE 1 - FORMULÁRIO ESPECIAL (pos 18 = '1') ==========
export const SANTANDER_CNAB240_SEGMENT_S_FORM: RecordSchema = {
  ...SANTANDER_CNAB240_SEGMENT_S,
  numero_linha: {
    pos: [19, 20],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da linha a ser impressa (01 a 22)',
    canonical: null,
  },
  mensagem_recibo: {
    pos: [21, 21],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem para recibo do Pagador: 2 ou 4',
    canonical: null,
  },
  mensagem_impressa: {
    pos: [22, 121],
    type: 'alfa',
    size: 100,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem a ser impressa',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [122, 240],
    type: 'alfa',
    size: 119,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
}

// ========== VARIANTE 2 - MENSAGENS FIXAS (pos 18 = '2') ==========
export const SANTANDER_CNAB240_SEGMENT_S_MESSAGES: RecordSchema = {
  ...SANTANDER_CNAB240_SEGMENT_S,
  mensagem_5: {
    pos: [19, 58],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 5',
    canonical: null,
  },
  mensagem_6: {
    pos: [59, 98],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 6',
    canonical: null,
  },
  mensagem_7: {
    pos: [99, 138],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 7',
    canonical: null,
  },
  mensagem_8: {
    pos: [139, 178],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 8',
    canonical: null,
  },
  mensagem_9: {
    pos: [179, 218],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 9',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [219, 240],
    type: 'alfa',
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado (uso Banco)',
    canonical: null,
  },
}
