/**
 * Itaú (341) é CNAB 400 é Registro Detalhe (Remessa)
 * Fonte do layout: laravel-boleto + brcobranca
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  codigo_inscricao: {
    pos: [2, 3],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do cedente: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao: {
    pos: [4, 17],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do cedente',
    canonical: null,
  },
  agencia: {
    pos: [18, 21],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência mantenedora da conta',
    canonical: null,
  },
  zeros: {
    pos: [22, 23],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Zeros (complemento de registro)',
    canonical: null,
  },
  conta: {
    pos: [24, 28],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente',
    canonical: null,
  },
  dac: {
    pos: [29, 29],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito de auto conferência da agência/conta',
    canonical: null,
  },
  brancos_1: {
    pos: [30, 33],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  instrucao_cancelar: {
    pos: [34, 37],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0000',
    description: 'Instrução para cancelamento de registros',
    canonical: null,
  },
  numero_controle: {
    pos: [38, 62],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título no sistema do cedente',
    canonical: null,
  },
  nosso_numero: {
    pos: [63, 70],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso número (identificação do título no banco)',
    canonical: 'nossoNumero',
  },
  qtde_moeda: {
    pos: [71, 83],
    type: FieldType.NUM,
    size: 13,
    decimals: 5,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de moeda (picture 9(08)V9(5) - 5 decimais)',
    canonical: null,
  },
  numero_carteira: {
    pos: [84, 86],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da carteira',
    canonical: null,
  },
  uso_banco: {
    pos: [87, 107],
    type: FieldType.ALFA,
    size: 21,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso do banco',
    canonical: null,
  },
  carteira: {
    pos: [108, 108],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da carteira (I=Cobrança Simples)',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de ocorrência (01=Remessa, 02=Pedido de baixa, etc)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento de cobrança (NF, Duplicata, etc)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título (2 decimais implícitas)',
    canonical: 'valor',
  },
  codigo_banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '341',
    description: 'Código do banco cobrador',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00000',
    description: 'Agência cobradora',
    canonical: null,
  },
  especie: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Espécie do título (01=Duplicata Mercantil)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    // Campo de negócio real, varia por título (manual: "A=ACEITE N=NÃO ACEITE") é não
    // é fixo como em outros bancos (ex: Bradesco, cujo manual diz "Sempre = N" pra essa
    // mesma posição). Não travar em 'N' via padrao, senão títulos reais com aceite='A'
    // seriam rejeitados como erro de validação.
    pattern: null,
    description: 'Identificação de título aceito ou não aceito: A=Aceite, N=Não aceite',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emissão do título',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Primeira instrução de cobrança',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Segunda instrução de cobrança',
    canonical: null,
  },
  juros_1dia: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor de juros de mora por dia de atraso',
    canonical: null,
  },
  desconto_ate: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concessão de desconto',
    canonical: null,
  },
  valor_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do desconto',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a ser recolhido',
    canonical: null,
  },
  abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: null,
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo documento: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF',
    canonical: 'sacado.endereco.estado',
  },
  sacador_avalista: {
    pos: [352, 381],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do sacador/avalista',
    canonical: null,
  },
  brancos_2: {
    pos: [382, 385],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  data_mora: {
    pos: [386, 391],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de início de cobrança de juros',
    canonical: 'juros.vigenciaAPartirDe',
  },
  prazo: {
    pos: [392, 393],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Prazo (complemento de registro)',
    canonical: null,
  },
  brancos_3: {
    pos: [394, 394],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento de registro)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial do registro',
    canonical: null,
  },
}
