export { Cnab240SicoobBoletoVencimentoField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-vencimento-field'
export { Cnab240SicoobBoletoEnderecoField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-endereco-field'
export { Cnab240SicoobBoletoBairroField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-bairro-field'
export { Cnab240SicoobBoletoCepField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-cep-field'
export { Cnab240SicoobBoletoCidadeField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-cidade-field'
export { Cnab240SicoobBoletoUfField } from '@cnab/bank/sicoob/cnab/cnab240/field/cnab240-sicoob-boleto-uf-field'
