/**
 * Itaú (341) — CNAB 400 — Registro Tipo 6, Layout 1 (Dados do Título)
 *
 * Registro para emissão física de boleto pelo cedente (fluxo paralelo ao tipo 1).
 * Este layout contém os dados principais do título.
 *
 * IMPORTANTE:
 * - Família paralela e independente do fluxo tipo 1/2/4/5
 * - Usa o mesmo header e trailer já implementados
 * - Campo codigo_layout = '1' identifica este layout
 * - Para moeda variável, valor_titulo usa 5 decimais (não 2)
 *
 * ATENÇÃO: Sem evidência real no fixture (não presente no ITAU_cnab_400.REM).
 * Schema baseado exclusivamente no manual oficial Itaú, p.44-45.
 *
 * Fonte: Manual oficial Itaú, layout_cobranca_400bytes_cnab_itau.pdf, §6, p.44-45
 */

import { RecordSchema, DateFormat, FieldType } from '@/types/all-types'

export const TYPE6_LAYOUT1_TITLE: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '6',
    description: 'Identificação do registro tipo 6 (emissão de boleto)',
    canonical: null,
  },
  codigo_layout: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Identificação do layout 1 (dados do título)',
    canonical: null,
  },
  agencia: {
    pos: [3, 6],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência mantenedora da conta',
    canonical: null,
  },
  zeros: {
    pos: [7, 8],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Zeros (complemento de registro)',
    canonical: null,
  },
  conta: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente da empresa',
    canonical: null,
  },
  dac: {
    pos: [14, 14],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito de auto conferência agência/conta empresa',
    canonical: null,
  },
  numero_carteira: {
    pos: [15, 17],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da carteira no banco',
    canonical: null,
  },
  nosso_numero: {
    pos: [18, 25],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título no banco (nosso número)',
    canonical: null,
  },
  dac_nosso_numero: {
    pos: [26, 26],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DAC do nosso número',
    canonical: null,
  },
  codigo_moeda: {
    pos: [27, 27],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da moeda: 0=Real, 1=Moeda variável (NOTA 23)',
    canonical: null,
  },
  literal_moeda: {
    pos: [28, 31],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da moeda a imprimir no boleto (moeda variável, NOTA 23)',
    canonical: null,
  },
  valor_titulo: {
    pos: [32, 44],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título - 2 decimais para Real, 5 decimais para moeda variável (NOTA 24)',
    canonical: null,
  },
  seu_numero: {
    pos: [45, 54],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento na empresa',
    canonical: null,
  },
  vencimento: {
    pos: [55, 60],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento do título',
    canonical: null,
  },
  especie: {
    pos: [61, 62],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Espécie do título (NOTA 10)',
    canonical: null,
  },
  aceite: {
    pos: [63, 63],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Aceite do título: A=Sim, N=Não',
    canonical: null,
  },
  data_emissao: {
    pos: [64, 69],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emissão do título',
    canonical: null,
  },
  codigo_inscricao: {
    pos: [70, 71],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do pagador: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao: {
    pos: [72, 86],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador',
    canonical: null,
  },
  nome: {
    pos: [87, 116],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: null,
  },
  brancos_1: {
    pos: [117, 125],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Complemento de registro (brancos)',
    canonical: null,
  },
  logradouro: {
    pos: [126, 165],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Rua, número e complemento do pagador',
    canonical: null,
  },
  bairro: {
    pos: [166, 177],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do pagador',
    canonical: null,
  },
  cep: {
    pos: [178, 185],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador',
    canonical: null,
  },
  cidade: {
    pos: [186, 200],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do pagador',
    canonical: null,
  },
  estado: {
    pos: [201, 202],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do pagador',
    canonical: null,
  },
  sacador_avalista: {
    pos: [203, 232],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do sacador/avalista',
    canonical: null,
  },
  brancos_2: {
    pos: [233, 236],
    type: FieldType.ALFA,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Complemento de registro (brancos)',
    canonical: null,
  },
  local_pagamento_1: {
    pos: [237, 291],
    type: FieldType.ALFA,
    size: 55,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Local para pagamento do título - linha 1',
    canonical: null,
  },
  local_pagamento_2: {
    pos: [292, 346],
    type: FieldType.ALFA,
    size: 55,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Local para pagamento do título - linha 2',
    canonical: null,
  },
  sacador_codigo_inscricao: {
    pos: [347, 348],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do sacador/avalista: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacador_numero_inscricao: {
    pos: [349, 363],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do sacador/avalista',
    canonical: null,
  },
  brancos_3: {
    pos: [364, 394],
    type: FieldType.ALFA,
    size: 31,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Complemento de registro (brancos)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial do registro no arquivo',
    canonical: null,
  },
}
