/**
 * Itaú (341) — CNAB 400 — Registro Tipo 4 (Rateio de Crédito)
 *
 * Registro opcional para indicar que o crédito do título deve ser rateado
 * entre até 14 contas de crédito por registro.
 *
 * IMPORTANTE:
 * - Opcional: apenas quando houver rateio de crédito
 * - Até 3 registros tipo 4 por título (total: até 42 contas / título)
 * - Manual menciona limite de 30 contas por título
 * - Cada registro tem 14 blocos de rateio (agência+conta+dac+valor)
 * - Rateio pode ser por valor ou percentual (ver campo tipo_valor)
 *
 * Regras críticas:
 * - Agência/conta/nosso número devem coincidir com o tipo 1 correspondente
 * - Soma dos valores/percentuais não pode ultrapassar valor nominal
 * - Não aceita desconto ou abatimento quando há rateio
 * - Beneficiário e centralizadora não podem estar nas contas de rateio
 *
 * ATENÇÃO: Sem evidência real no fixture (não presente no ITAU_cnab_400.REM).
 * Schema baseado exclusivamente no manual oficial Itaú, p.10-11.
 *
 * Fonte: Manual oficial Itaú, layout_cobranca_400bytes_cnab_itau.pdf, p.10-11
 */

import { RecordSchema } from '../../../../../../types'

export const TYPE4_CREDIT_ALLOCATION: RecordSchema = {
  // ========== Campos fixos (posições 1-43) ==========
  
  tipo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '4',
    description: 'Identificação do registro tipo 4 (rateio de crédito)',
    canonical: null,
  },
  codigo_inscricao: {
    pos: [2, 3],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição da empresa/beneficiário: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao: {
    pos: [4, 17],
    type: 'num',
    size: 14,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ da empresa beneficiária',
    canonical: null,
  },
  agencia: {
    pos: [18, 21],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência mantenedora da conta',
    canonical: null,
  },
  zeros: {
    pos: [22, 23],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Zeros (complemento de registro)',
    canonical: null,
  },
  conta: {
    pos: [24, 28],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente da empresa',
    canonical: null,
  },
  dac: {
    pos: [29, 29],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito de auto conferência agência/conta empresa',
    canonical: null,
  },
  numero_carteira: {
    pos: [30, 32],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da carteira no banco',
    canonical: null,
  },
  nosso_numero: {
    pos: [33, 40],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título no banco (nosso número)',
    canonical: null,
  },
  dac_nosso_numero: {
    pos: [41, 41],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC do nosso número',
    canonical: null,
  },
  sequencia_registro: {
    pos: [42, 43],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial dos registros tipo 4 do título (1 a 3)',
    canonical: null,
  },

  // ========== Bloco de Rateio 01 ==========
  
  agencia_credito_01: {
    pos: [44, 47],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 01',
    canonical: null,
  },
  conta_credito_01: {
    pos: [48, 54],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 01',
    canonical: null,
  },
  dac_credito_01: {
    pos: [55, 55],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 01',
    canonical: null,
  },
  valor_credito_01: {
    pos: [56, 68],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 01 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 02 ==========
  
  agencia_credito_02: {
    pos: [69, 72],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 02',
    canonical: null,
  },
  conta_credito_02: {
    pos: [73, 79],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 02',
    canonical: null,
  },
  dac_credito_02: {
    pos: [80, 80],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 02',
    canonical: null,
  },
  valor_credito_02: {
    pos: [81, 93],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 02 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 03 ==========
  
  agencia_credito_03: {
    pos: [94, 97],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 03',
    canonical: null,
  },
  conta_credito_03: {
    pos: [98, 104],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 03',
    canonical: null,
  },
  dac_credito_03: {
    pos: [105, 105],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 03',
    canonical: null,
  },
  valor_credito_03: {
    pos: [106, 118],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 03 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 04 ==========
  
  agencia_credito_04: {
    pos: [119, 122],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 04',
    canonical: null,
  },
  conta_credito_04: {
    pos: [123, 129],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 04',
    canonical: null,
  },
  dac_credito_04: {
    pos: [130, 130],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 04',
    canonical: null,
  },
  valor_credito_04: {
    pos: [131, 143],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 04 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 05 ==========
  
  agencia_credito_05: {
    pos: [144, 147],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 05',
    canonical: null,
  },
  conta_credito_05: {
    pos: [148, 154],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 05',
    canonical: null,
  },
  dac_credito_05: {
    pos: [155, 155],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 05',
    canonical: null,
  },
  valor_credito_05: {
    pos: [156, 168],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 05 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 06 ==========
  
  agencia_credito_06: {
    pos: [169, 172],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 06',
    canonical: null,
  },
  conta_credito_06: {
    pos: [173, 179],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 06',
    canonical: null,
  },
  dac_credito_06: {
    pos: [180, 180],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 06',
    canonical: null,
  },
  valor_credito_06: {
    pos: [181, 193],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 06 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 07 ==========
  
  agencia_credito_07: {
    pos: [194, 197],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 07',
    canonical: null,
  },
  conta_credito_07: {
    pos: [198, 204],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 07',
    canonical: null,
  },
  dac_credito_07: {
    pos: [205, 205],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 07',
    canonical: null,
  },
  valor_credito_07: {
    pos: [206, 218],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 07 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 08 ==========
  
  agencia_credito_08: {
    pos: [219, 222],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 08',
    canonical: null,
  },
  conta_credito_08: {
    pos: [223, 229],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 08',
    canonical: null,
  },
  dac_credito_08: {
    pos: [230, 230],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 08',
    canonical: null,
  },
  valor_credito_08: {
    pos: [231, 243],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 08 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 09 ==========
  
  agencia_credito_09: {
    pos: [244, 247],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 09',
    canonical: null,
  },
  conta_credito_09: {
    pos: [248, 254],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 09',
    canonical: null,
  },
  dac_credito_09: {
    pos: [255, 255],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 09',
    canonical: null,
  },
  valor_credito_09: {
    pos: [256, 268],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 09 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 10 ==========
  
  agencia_credito_10: {
    pos: [269, 272],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 10',
    canonical: null,
  },
  conta_credito_10: {
    pos: [273, 279],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 10',
    canonical: null,
  },
  dac_credito_10: {
    pos: [280, 280],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 10',
    canonical: null,
  },
  valor_credito_10: {
    pos: [281, 293],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 10 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 11 ==========
  
  agencia_credito_11: {
    pos: [294, 297],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 11',
    canonical: null,
  },
  conta_credito_11: {
    pos: [298, 304],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 11',
    canonical: null,
  },
  dac_credito_11: {
    pos: [305, 305],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 11',
    canonical: null,
  },
  valor_credito_11: {
    pos: [306, 318],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 11 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 12 ==========
  
  agencia_credito_12: {
    pos: [319, 322],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 12',
    canonical: null,
  },
  conta_credito_12: {
    pos: [323, 329],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 12',
    canonical: null,
  },
  dac_credito_12: {
    pos: [330, 330],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 12',
    canonical: null,
  },
  valor_credito_12: {
    pos: [331, 343],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 12 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 13 ==========
  
  agencia_credito_13: {
    pos: [344, 347],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 13',
    canonical: null,
  },
  conta_credito_13: {
    pos: [348, 354],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 13',
    canonical: null,
  },
  dac_credito_13: {
    pos: [355, 355],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 13',
    canonical: null,
  },
  valor_credito_13: {
    pos: [356, 368],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 13 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Bloco de Rateio 14 ==========
  
  agencia_credito_14: {
    pos: [369, 372],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de crédito - Conta 14',
    canonical: null,
  },
  conta_credito_14: {
    pos: [373, 379],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta de crédito - Conta 14',
    canonical: null,
  },
  dac_credito_14: {
    pos: [380, 380],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DAC da conta de crédito - Conta 14',
    canonical: null,
  },
  valor_credito_14: {
    pos: [381, 393],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual de crédito - Conta 14 (ver tipo_valor)',
    canonical: null,
  },

  // ========== Campos finais ==========
  
  tipo_valor: {
    pos: [394, 394],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indica se o rateio é por valor ou percentual (ver NOTA 32 do manual)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial do registro no arquivo',
    canonical: null,
  },
}
