/**
 * Caixa Econ�mica Federal (104) � CNAB 400 � Detalhe de Remessa (Registro Tipo 1)
 * Usa sistema SIGCB, nosso n�mero de 17 posi��es (2 d�gitos modalidade + 15 d�gitos livres).
 *
 * Particularidade: Caixa usa "c�digo do benefici�rio" de 7 d�gitos (posi��o 21-27) em vez de
 * ag�ncia+conta separados. Tamb�m tem campo de ag�ncia pr�prio (18-20, hoje zeros) al�m do
 * c�digo do benefici�rio � n�o � substituto, � complementar.
 * Fontes:
 * - Manual oficial Caixa CNAB 400 (caixa_layout_CNAB_400_2024.pdf, 2024)
 * - laravel-boleto (PHP) - fonte original, concordante
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const DETAIL: RecordSchema = {
  codigo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  tipo_inscricao_empresa: {
    pos: [2, 3],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do benefici�rio: 1=CPF, 2=CNPJ (NE011)',
    canonical: null,
  },
  numero_inscricao_empresa: {
    pos: [4, 17],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do benefici�rio (NE012)',
    canonical: null,
  },
  uso_exclusivo_1: {
    pos: [18, 20],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Zeros - campo antes usava c�digo da ag�ncia, hoje � ignorado pela CAIXA',
    canonical: null,
  },
  codigo_beneficiario: {
    pos: [21, 27],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o da empresa na CAIXA (NE004)',
    canonical: null,
  },
  id_emissao: {
    pos: [28, 28],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o da emiss�o do boleto (NE027)',
    canonical: null,
  },
  id_postagem: {
    pos: [29, 29],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o da entrega/distribui��o do boleto (NE028)',
    canonical: null,
  },
  taxa_permanencia: {
    pos: [30, 31],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Comiss�o de perman�ncia - preencher com zeros',
    canonical: null,
  },
  uso_empresa_beneficiario: {
    pos: [32, 56],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo na empresa (NE014)',
    canonical: null,
  },
  nosso_numero_modalidade: {
    pos: [57, 58],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Modalidade do nosso n�mero: 11=registrado emiss�o CAIXA, 14=registrado emiss�o benefici�rio (NE015)',
    canonical: null,
  },
  nosso_numero: {
    pos: [59, 73],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo na CAIXA - n�mero livre, n�o pode repetir (NE015)',
    canonical: 'nossoNumero',
  },
  brancos_1: {
    pos: [74, 75],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  uso_livre_pagamento_parcial: {
    pos: [76, 76],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso livre banco/empresa ou autoriza��o de pagamento parcial (NE055)',
    canonical: null,
  },
  codigo_juros: {
    pos: [77, 77],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do tipo de juros (NE066): 1=Valor dias corridos, 3=% ao m�s dias corridos, 5=Isento, 6=Valor dia �til, 8=% ao m�s dias �teis',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 5) return 'dispensado'
        if (code === 1 || code === 6) return 'valor'
        if (code === 3 || code === 8) return 'percentual'
        return undefined
      },
    },
  },
  data_juros: {
    pos: [78, 83],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de in�cio de juros (NE063)',
    canonical: 'juros.vigenciaAPartirDe',
  },
  codigo_desconto: {
    pos: [84, 84],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do tipo de desconto (NE061)',
    canonical: null,
  },
  brancos_2: {
    pos: [85, 106],
    type: FieldType.ALFA,
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  carteira: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da carteira - 000=Cess�o de Direitos Credit�rios (NE016)',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento: 01=Entrada de T�tulo, 02=Pedido de Baixa, 03=Concess�o de Abatimento, 04=Cancelamento de Abatimento, 05=Altera��o de Vencimento, 06=Altera��o do uso da Empresa, 07=Altera��o do Prazo de Protesto, 08=Altera��o do Prazo de Devolu��o, 09=Altera��o de outros dados, 10=Altera��o de dados com emiss�o/emiss�o de boleto, 11=Altera��o da op��o de Protesto para Devolu��o, 12=Altera��o da op��o de Devolu��o para Protesto, 13=Altera��o do valor nominal do t�tulo, 14=Altera��o da carteira (NE017)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Seu n�mero - obrigat�rio (NE018)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento (NE019)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do t�tulo (2 decimais impl�citas) (NE020)',
    canonical: 'valor',
  },
  codigo_banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '104',
    description: 'C�digo do banco cobrador (NE006) - obrigatorio:false por consist�ncia com o mesmo campo em BB/Ita�, para n�o rejeitar arquivos reais com o campo em branco ou correspondente diferente',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia encarregada da cobran�a (NE021)',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Esp�cie do t�tulo (NE022)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aceite do t�tulo (NE023)',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emiss�o do t�tulo (NE056)',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira instru��o de cobran�a (NE024)',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda instru��o de cobran�a',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros de mora por dia/valor (2 decimais impl�citas) (NE064)',
    canonical: 'juros.valor',
  },
  data_desconto: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concess�o do desconto (NE057)',
    canonical: null,
  },
  valor_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do desconto (2 decimais impl�citas) (NE062)',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a recolher (2 decimais impl�citas)',
    canonical: null,
  },
  abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento a conceder/cancelar (2 decimais impl�citas)',
    canonical: null,
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do pagador: 1=CPF, 2=CNPJ (NE011)',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador (NE012)',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do pagador (NE058)',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do pagador',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do pagador',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do pagador',
    canonical: 'sacado.endereco.estado',
  },
  data_multa: {
    pos: [352, 357],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Defini��o da data para pagamento de multa (NE059)',
    canonical: null,
  },
  valor_multa: {
    pos: [358, 367],
    type: FieldType.NUM,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor nominal da multa',
    canonical: null,
  },
  sacador_avalista: {
    pos: [368, 389],
    type: FieldType.ALFA,
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Sacador/Avalista (assim rotulado no manual oficial da Caixa 2024 - diferente de BB/Bradesco/Sicredi, que j� usam "Benefici�rio Final"; campo tamb�m mais curto: 22 caracteres, contra 30-60 nos outros bancos)',
    canonical: null,
  },
  instrucao_3: {
    pos: [390, 391],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Terceira instru��o de cobran�a (NE029)',
    canonical: null,
  },
  prazo: {
    pos: [392, 393],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de dias para in�cio do protesto/devolu��o (NE025)',
    canonical: null,
  },
  codigo_moeda: {
    pos: [394, 394],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da moeda (NE026)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro',
    canonical: null,
  },
}
