/**
 * Caixa Econômica Federal (104) — CNAB 400 — Detalhe de Remessa (Registro Tipo 1)
 *
 * Usa sistema SIGCB, nosso número de 17 posições (2 dígitos modalidade + 15 dígitos livres).
 *
 * Particularidade: Caixa usa "código do beneficiário" de 7 dígitos (posição 21-27) em vez de
 * agência+conta separados. Também tem campo de agência próprio (18-20, hoje zeros) além do
 * código do beneficiário — não é substituto, é complementar.
 *
 * Fontes:
 * - Manual oficial Caixa CNAB 400 (caixa_layout_CNAB_400_2024.pdf, 2024)
 * - laravel-boleto (PHP) - fonte original, concordante
 *
 */

import { RecordSchema } from '../../../../types'

export const DETAIL: RecordSchema = {
  codigo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro detalhe',
    canonical: null,
  },
  tipo_inscricao_empresa: {
    pos: [2, 3],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do beneficiário: 1=CPF, 2=CNPJ (NE011)',
    canonical: null,
  },
  numero_inscricao_empresa: {
    pos: [4, 17],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do beneficiário (NE012)',
    canonical: null,
  },
  uso_exclusivo_1: {
    pos: [18, 20],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Zeros - campo antes usava código da agência, hoje é ignorado pela CAIXA',
    canonical: null,
  },
  codigo_beneficiario: {
    pos: [21, 27],
    type: 'num',
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da empresa na CAIXA (NE004)',
    canonical: null,
  },
  id_emissao: {
    pos: [28, 28],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da emissão do boleto (NE027)',
    canonical: null,
  },
  id_postagem: {
    pos: [29, 29],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da entrega/distribuição do boleto (NE028)',
    canonical: null,
  },
  taxa_permanencia: {
    pos: [30, 31],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Comissão de permanência - preencher com zeros',
    canonical: null,
  },
  uso_empresa_beneficiario: {
    pos: [32, 56],
    type: 'alfa',
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título na empresa (NE014)',
    canonical: null,
  },
  nosso_numero_modalidade: {
    pos: [57, 58],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Modalidade do nosso número: 11=registrado emissão CAIXA, 14=registrado emissão beneficiário (NE015)',
    canonical: null,
  },
  nosso_numero: {
    pos: [59, 73],
    type: 'num',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título na CAIXA - número livre, não pode repetir (NE015)',
    canonical: 'nossoNumero',
  },
  brancos_1: {
    pos: [74, 75],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  uso_livre_pagamento_parcial: {
    pos: [76, 76],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso livre banco/empresa ou autorização de pagamento parcial (NE055)',
    canonical: null,
  },
  codigo_juros: {
    pos: [77, 77],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do tipo de juros (NE066): 1=Valor dias corridos, 3=% ao mês dias corridos, 5=Isento, 6=Valor dia útil, 8=% ao mês dias úteis',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 5) return 'dispensado'
        if (code === 1 || code === 6) return 'valor'
        if (code === 3 || code === 8) return 'percentual'
        return undefined
      },
    },
  },
  data_juros: {
    pos: [78, 83],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de início de juros (NE063)',
    canonical: 'juros.vigenciaAPartirDe',
  },
  codigo_desconto: {
    pos: [84, 84],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do tipo de desconto (NE061)',
    canonical: null,
  },
  brancos_2: {
    pos: [85, 106],
    type: 'alfa',
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  carteira: {
    pos: [107, 108],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código da carteira - 000=Cessão de Direitos Creditórios (NE016)',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento: 01=Entrada de Título, 02=Pedido de Baixa, 03=Concessão de Abatimento, 04=Cancelamento de Abatimento, 05=Alteração de Vencimento, 06=Alteração do uso da Empresa, 07=Alteração do Prazo de Protesto, 08=Alteração do Prazo de Devolução, 09=Alteração de outros dados, 10=Alteração de dados com emissão/emissão de boleto, 11=Alteração da opção de Protesto para Devolução, 12=Alteração da opção de Devolução para Protesto, 13=Alteração do valor nominal do título, 14=Alteração da carteira (NE017)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Seu número - obrigatório (NE018)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de vencimento (NE019)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: 'num',
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título (2 decimais implícitas) (NE020)',
    canonical: 'valor',
  },
  codigo_banco_cobrador: {
    pos: [140, 142],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '104',
    description: 'Código do banco cobrador (NE006) - obrigatorio:false por consistência com o mesmo campo em BB/Itaú, para não rejeitar arquivos reais com o campo em branco ou correspondente diferente',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência encarregada da cobrança (NE021)',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espécie do título (NE022)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aceite do título (NE023)',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de emissão do título (NE056)',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Primeira instrução de cobrança (NE024)',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Segunda instrução de cobrança',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros de mora por dia/valor (2 decimais implícitas) (NE064)',
    canonical: 'juros.valor',
  },
  data_desconto: {
    pos: [174, 179],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data limite para concessão do desconto (NE057)',
    canonical: null,
  },
  valor_desconto: {
    pos: [180, 192],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do desconto (2 decimais implícitas) (NE062)',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [193, 205],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a recolher (2 decimais implícitas)',
    canonical: null,
  },
  abatimento: {
    pos: [206, 218],
    type: 'num',
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento a conceder/cancelar (2 decimais implícitas)',
    canonical: null,
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do pagador: 1=CPF, 2=CNPJ (NE011)',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do pagador (NE012)',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do pagador (NE058)',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [315, 326],
    type: 'alfa',
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do pagador',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do pagador',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do pagador',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do pagador',
    canonical: 'sacado.endereco.estado',
  },
  data_multa: {
    pos: [352, 357],
    type: 'data',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Definição da data para pagamento de multa (NE059)',
    canonical: null,
  },
  valor_multa: {
    pos: [358, 367],
    type: 'num',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor nominal da multa',
    canonical: null,
  },
  sacador_avalista: {
    pos: [368, 389],
    type: 'alfa',
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Sacador/Avalista (assim rotulado no manual oficial da Caixa 2024 - diferente de BB/Bradesco/Sicredi, que já usam "Beneficiário Final"; campo também mais curto: 22 caracteres, contra 30-60 nos outros bancos)',
    canonical: null,
  },
  instrucao_3: {
    pos: [390, 391],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Terceira instrução de cobrança (NE029)',
    canonical: null,
  },
  prazo: {
    pos: [392, 393],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de dias para início do protesto/devolução (NE025)',
    canonical: null,
  },
  codigo_moeda: {
    pos: [394, 394],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código da moeda (NE026)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro',
    canonical: null,
  },
}
