/**
 * Caixa Econômica Federal (104) — CNAB 400 — Header de Arquivo (Remessa)
 *
 * Usa sistema SIGCB, nosso número de 17 posições (2 dígitos modalidade + 15 dígitos livres).
 *
 * Fontes:
 * - Manual oficial Caixa CNAB 400 (caixa_layout_CNAB_400_2024.pdf, 2024)
 * - laravel-boleto (PHP) - fonte original, concordante
 *
 */

import { RecordSchema } from '../../../../types'

export const HEADER: RecordSchema = {
  codigo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificação do header',
    canonical: null,
  },
  codigo_remessa: {
    pos: [2, 2],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operação: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: 'alfa',
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código de serviço',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de serviço (NE002)',
    canonical: null,
  },
  codigo_agencia: {
    pos: [27, 30],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da agência de vinculação do beneficiário (NE003)',
    canonical: null,
  },
  codigo_beneficiario: {
    pos: [31, 37],
    type: 'num',
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificador da empresa na CAIXA (NE004)',
    canonical: null,
  },
  uso_exclusivo_1: {
    pos: [38, 46],
    type: 'alfa',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos/uso exclusivo banco',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: 'alfa',
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome por extenso do cedente (NE005)',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '104',
    description: 'Código FEBRABAN da Caixa (NE006)',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do banco (NE007)',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: 'data',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAA',
    pattern: null,
    description: 'Data de geração do arquivo (NE008)',
    canonical: 'dataGeracao',
  },
  versao_layout: {
    pos: [101, 103],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número da versão do layout (NE065) - campo que só existe também no Sicredi entre os bancos do projeto',
    canonical: null,
  },
  uso_exclusivo_2: {
    pos: [104, 389],
    type: 'alfa',
    size: 286,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos/uso exclusivo banco',
    canonical: null,
  },
  numero_sequencial_arquivo: {
    pos: [390, 394],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do arquivo remessa (NE009)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro (NE010)',
    canonical: null,
  },
}
