/**
 * Caixa Econ�mica Federal (104) � CNAB 400 � Header de Arquivo (Remessa)
 * Usa sistema SIGCB, nosso n�mero de 17 posi��es (2 d�gitos modalidade + 15 d�gitos livres).
 *
 * Fontes:
 * - Manual oficial Caixa CNAB 400 (caixa_layout_CNAB_400_2024.pdf, 2024)
 * - laravel-boleto (PHP) - fonte original, concordante
 *
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const HEADER: RecordSchema = {
  codigo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identifica��o do header',
    canonical: null,
  },
  codigo_remessa: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de opera��o: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de servi�o',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal de servi�o (NE002)',
    canonical: null,
  },
  codigo_agencia: {
    pos: [27, 30],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da ag�ncia de vincula��o do benefici�rio (NE003)',
    canonical: null,
  },
  codigo_beneficiario: {
    pos: [31, 37],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificador da empresa na CAIXA (NE004)',
    canonical: null,
  },
  uso_exclusivo_1: {
    pos: [38, 46],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos/uso exclusivo banco',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome por extenso do cedente (NE005)',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '104',
    description: 'C�digo FEBRABAN da Caixa (NE006)',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do banco (NE007)',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de gera��o do arquivo (NE008)',
    canonical: 'dataGeracao',
  },
  versao_layout: {
    pos: [101, 103],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero da vers�o do layout (NE065) - campo que s� existe tamb�m no Sicredi entre os bancos do projeto',
    canonical: null,
  },
  uso_exclusivo_2: {
    pos: [104, 389],
    type: FieldType.ALFA,
    size: 286,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos/uso exclusivo banco',
    canonical: null,
  },
  numero_sequencial_arquivo: {
    pos: [390, 394],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do arquivo remessa (NE009)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro (NE010)',
    canonical: null,
  },
}
