/**
 * Bradesco CNAB 240 - Header de Lote
 * Header de Lote (pos 8 = '1')
 * Primeira linha de cada lote dentro do arquivo. Um arquivo pode conter vários lotes,
 * cada um com seu header próprio. O lote agrupa títulos/boletos relacionados.
 * Contém dados do cedente (beneficiário) específicos do lote, como agência, conta,
 * convênio e informações complementares.
 * ATENÇÃO: O campo 
umero_remessa_retorno` (pos 184-191) é o campo autoritativo
 * para o número sequencial de remessa do Bradesco (não o campo do Header de Arquivo).
 * Este número deve ser incrementado a cada novo arquivo de remessa enviado.
 * Fonte do layout: 
 * - Manual oficial Bradesco CNAB 240 (bradesco_cnab240_2024.pdf, versão 04, dez/2024)
 * - pycnab240 (header_lote_cobranca.json)
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_BATCH_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do lote (incrementa de 1 em 1, começa em 0001)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo: 1=Header de Lote',
    canonical: null,
  },
  servico_operacao: {
    pos: [9, 9],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Tipo de operação: R=Remessa, T=Retorno',
    canonical: null,
  },
  servico_tipo: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Tipo de serviço: 01=Cobrança',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [12, 13],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
  servico_layout: {
    pos: [14, 16],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '042',
    description: 'Número da versão do layout do lote (042 para cobrança Bradesco)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [17, 17],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (branco)',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do cedente: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número de inscrição do cedente (CPF ou CNPJ com zeros é esquerda)',
    canonical: null,
  },
  cedente_convenio: {
    pos: [34, 53],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código do convênio no banco (fornecido pelo Bradesco)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [54, 58],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da agência mantenedora da conta',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [59, 59],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência (branco se não houver)',
    canonical: null,
  },
  cedente_conta: {
    pos: [60, 71],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [72, 72],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [73, 73],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (branco)',
    canonical: null,
  },
  cedente_nome: {
    pos: [74, 103],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do cedente/beneficiário (razão social ou nome completo)',
    canonical: null,
  },
  informacao_1: {
    pos: [104, 143],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 1 (informação livre para impressão no boleto)',
    canonical: null,
  },
  informacao_2: {
    pos: [144, 183],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 (informação livre para impressão no boleto)',
    canonical: null,
  },
  numero_remessa_retorno: {
    pos: [184, 191],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial da remessa (campo autoritativo - incrementa a cada arquivo enviado)',
    canonical: null,
  },
  data_gravacao: {
    pos: [192, 199],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de gravação do arquivo (DDMMAAAA)',
    canonical: null,
  },
  data_credito: {
    pos: [200, 207],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de crédito (DDMMAAAA, zeros se não aplicável)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [208, 240],
    type: FieldType.ALFA,
    size: 33,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
}

