/**
 * Bradesco CNAB 240 - Header de Lote
 * Header de Lote (pos 8 = '1')
 * Primeira linha de cada lote dentro do arquivo. Um arquivo pode conter v�rios lotes,
 * cada um com seu header pr�prio. O lote agrupa t�tulos/boletos relacionados.
 * Cont�m dados do cedente (benefici�rio) espec�ficos do lote, como ag�ncia, conta,
 * conv�nio e informa��es complementares.
 * ATEN��O: O campo 
umero_remessa_retorno` (pos 184-191) � o campo autoritativo
 * para o n�mero sequencial de remessa do Bradesco (n�o o campo do Header de Arquivo).
 * Este n�mero deve ser incrementado a cada novo arquivo de remessa enviado.
 * Fonte do layout: 
 * - Manual oficial Bradesco CNAB 240 (bradesco_cnab240_2024.pdf, vers�o 04, dez/2024)
 * - pycnab240 (header_lote_cobranca.json)
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_BATCH_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do lote (incrementa de 1 em 1, come�a em 0001)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo: 1=Header de Lote',
    canonical: null,
  },
  servico_operacao: {
    pos: [9, 9],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Tipo de opera��o: R=Remessa, T=Retorno',
    canonical: null,
  },
  servico_tipo: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Tipo de servi�o: 01=Cobran�a',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [12, 13],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
  servico_layout: {
    pos: [14, 16],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '042',
    description: 'N�mero da vers�o do layout do lote (042 para cobran�a Bradesco)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [17, 17],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (branco)',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o do cedente: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de inscri��o do cedente (CPF ou CNPJ com zeros � esquerda)',
    canonical: null,
  },
  cedente_convenio: {
    pos: [34, 53],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do conv�nio no banco (fornecido pelo Bradesco)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [54, 58],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da ag�ncia mantenedora da conta',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [59, 59],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia (branco se n�o houver)',
    canonical: null,
  },
  cedente_conta: {
    pos: [60, 71],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero da conta corrente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [72, 72],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [73, 73],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (branco)',
    canonical: null,
  },
  cedente_nome: {
    pos: [74, 103],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do cedente/benefici�rio (raz�o social ou nome completo)',
    canonical: null,
  },
  informacao_1: {
    pos: [104, 143],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 1 (informa��o livre para impress�o no boleto)',
    canonical: null,
  },
  informacao_2: {
    pos: [144, 183],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 (informa��o livre para impress�o no boleto)',
    canonical: null,
  },
  numero_remessa_retorno: {
    pos: [184, 191],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial da remessa (campo autoritativo - incrementa a cada arquivo enviado)',
    canonical: null,
  },
  data_gravacao: {
    pos: [192, 199],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de grava��o do arquivo (DDMMAAAA)',
    canonical: null,
  },
  data_credito: {
    pos: [200, 207],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de cr�dito (DDMMAAAA, zeros se n�o aplic�vel)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [208, 240],
    type: FieldType.ALFA,
    size: 33,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
}

