/**
 * Bradesco CNAB 240 - Trailer de Lote
 * Trailer de Lote (pos 8 = '5')
 * �ltima linha de cada lote dentro do arquivo. Cont�m totalizadores do lote:
 * quantidade de registros, quantidade e valor total de t�tulos por tipo de cobran�a
 * (simples, vinculada, caucionada, descontada).
 * Fonte do layout:
 * - Manual oficial Bradesco CNAB 240 (bradesco_cnab240_2024.pdf, vers�o 04, dez/2024)
 * - pycnab240 (trailer_lote_cobranca.json)
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_BATCH_TRAILER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do lote (mesmo n�mero do Header de Lote correspondente)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '5',
    description: 'Tipo: 5=Trailer de Lote',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 17],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
  quantidade_registros: {
    pos: [18, 23],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade total de registros no lote (incluindo header e trailer)',
    canonical: null,
  },
  cobranca_simples_qtde_titulos: {
    pos: [24, 29],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de t�tulos em cobran�a simples',
    canonical: null,
  },
  cobranca_simples_valor_total: {
    pos: [30, 46],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor total dos t�tulos em cobran�a simples (2 decimais impl�citas)',
    canonical: null,
  },
  cobranca_vinculada_qtde_titulos: {
    pos: [47, 52],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de t�tulos em cobran�a vinculada',
    canonical: null,
  },
  cobranca_vinculada_valor_total: {
    pos: [53, 69],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor total dos t�tulos em cobran�a vinculada (2 decimais impl�citas)',
    canonical: null,
  },
  cobranca_caucionada_qtde_titulos: {
    pos: [70, 75],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de t�tulos em cobran�a caucionada',
    canonical: null,
  },
  cobranca_caucionada_valor_total: {
    pos: [76, 92],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor total dos t�tulos em cobran�a caucionada (2 decimais impl�citas)',
    canonical: null,
  },
  cobranca_descontada_qtde_titulos: {
    pos: [93, 98],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de t�tulos em cobran�a descontada',
    canonical: null,
  },
  cobranca_descontada_valor_total: {
    pos: [99, 115],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor total dos t�tulos em cobran�a descontada (2 decimais impl�citas)',
    canonical: null,
  },
  numero_aviso_lancamento: {
    pos: [116, 123],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do aviso de lan�amento (informado pelo banco)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [124, 240],
    type: FieldType.ALFA,
    size: 117,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
}

