/**
 * Bradesco CNAB 240 - Header de Arquivo
 * Header de Arquivo (pos 8 = '0')
 * Primeira linha do arquivo. Contém os dados de quem está emitindo os boletos
 * (a empresa/beneficiário), o código do banco, e a data/hora em que o arquivo foi gerado.
 * é como a "capa" do arquivo é identifica quem mandou e quando.
 * ATENÇÃO: O campo `arquivo_sequencia` (pos 158-163) NÃO é o número sequencial
 * de remessa. O campo autoritativo para isso é o 
umero_remessa_retorno` do
 * Header de Lote (pos 184-191 do registro tipo '1').
 * Fonte do layout:
 * - Manual oficial Bradesco CNAB 240 (bradesco_cnab240_2024.pdf, versão 04, dez/2024)
 * - pycnab240 (header_arquivo.json)
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0000',
    description: 'Lote 0000 = header de arquivo',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Tipo: 0=Header de Arquivo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 17],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do cedente: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 32],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número de inscrição do cedente (CPF ou CNPJ com zeros é esquerda)',
    canonical: 'cedente.documento',
  },
  cedente_convenio: {
    pos: [33, 52],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código do convênio no banco (fornecido pelo Bradesco)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [53, 57],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da agência mantenedora da conta',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [58, 58],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência (branco se não houver)',
    canonical: null,
  },
  cedente_conta: {
    pos: [59, 70],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [71, 71],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [72, 72],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (branco)',
    canonical: null,
  },
  cedente_nome: {
    pos: [73, 102],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do cedente/beneficiário (razão social ou nome completo)',
    canonical: 'cedente.nome',
  },
  nome_do_banco: {
    pos: [103, 132], 
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do banco (Bradesco)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [133, 142],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
  arquivo_codigo: {
    pos: [143, 143],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Código do arquivo: 1=Remessa, 2=Retorno',
    canonical: null,
  },
  arquivo_data_de_geracao: {
    pos: [144, 151],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de geração do arquivo (DDMMAAAA)',
    canonical: 'dataGeracao',
  },
  arquivo_hora_de_geracao: {
    pos: [152, 157],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Hora de geração do arquivo (HHMMSS)',
    canonical: null,
  },
  arquivo_sequencia: {
    pos: [158, 163],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sequencial do arquivo (incrementa a cada arquivo). ATENÇÃO: Este NÃO é o número sequencial de remessa - o campo autoritativo para isso é o numero_remessa_retorno do Header de Lote (pos 184-191 do registro tipo 1)',
    canonical: null,
  },
  arquivo_layout: {
    pos: [164, 166],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '084',
    description: 'Versão do layout do arquivo (084 para CNAB 240)',
    canonical: null,
  },
  arquivo_densidade: {
    pos: [167, 171],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Densidade de gravação (ex: 6250 BPI - legado, normalmente vazio)',
    canonical: null,
  },
  reservado_banco: {
    pos: [172, 191],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado para uso do banco (brancos)',
    canonical: null,
  },
  reservado_empresa: {
    pos: [192, 211],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Reservado para uso da empresa (brancos)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [212, 240],
    type: FieldType.ALFA,
    size: 29,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo FEBRABAN/CNAB (brancos)',
    canonical: null,
  },
}
