/**
 * Bradesco CNAB 240 - Segmento P
 * Segmento P (pos 8 = '3', pos 14 = 'P')
 * Linha com os dados financeiros de cada boleto: valor cobrado, data de vencimento,
 * nosso n�mero (identificador �nico do boleto no banco), esp�cie do t�tulo, etc.
 * Cada boleto gera uma linha de Segmento P.
 * Fonte do layout: pycnab240 + cnab_yaml generic FEBRABAN
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_SEGMENT_P: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de servi�o',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'P',
    description: 'Segmento P = dados do t�tulo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento da remessa',
    canonical: null,
  },
  cedente_agencia: {
    pos: [18, 22],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia do cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [23, 23],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia',
    canonical: null,
  },
  cedente_conta: {
    pos: [24, 35],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente do cedente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [36, 36],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta',
    canonical: null,
  },
  cedente_agencia_conta_dv: {
    pos: [37, 37],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia/conta do cedente',
    canonical: null,
  },
  identificacao_titulo_banco: {
    pos: [38, 57],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo no banco (carteira + nosso n�mero)',
    canonical: null,
  },
  cobranca_carteira: {
    pos: [58, 58],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da carteira: 1=Simples, 3=Caucionada, 4=Descontada',
    canonical: null,
  },
  cobranca_cadastramento: {
    pos: [59, 59],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Forma de cadastramento: 0=Com registro, 1=Sem registro',
    canonical: null,
  },
  cobranca_documento_tipo: {
    pos: [60, 60],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de documento',
    canonical: null,
  },
  cobranca_emissao_bloqueto: {
    pos: [61, 61],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '2',
    description: 'Identifica��o da emiss�o: 1=Banco, 2=Empresa',
    canonical: null,
  },
  cobranca_distribuicao_bloqueto: {
    pos: [62, 62],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o da distribui��o: 1=Banco, 2=Empresa',
    canonical: null,
  },
  numero_documento: {
    pos: [63, 77],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do documento de cobran�a',
    canonical: 'numeroDocumento',
  },
  vencimento_titulo: {
    pos: [78, 85],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de vencimento',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [86, 100],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do t�tulo',
    canonical: 'valor',
  },
  agencia_cobradora: {
    pos: [101, 105],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia cobradora/recebedora',
    canonical: null,
  },
  agencia_cobradora_dv: {
    pos: [106, 106],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia cobradora',
    canonical: null,
  },
  especie_titulo: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Esp�cie do t�tulo: 01=DM, 02=NP, etc.',
    canonical: null,
  },
  aceite_titulo: {
    pos: [109, 109],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Aceite: A=Aceite, N=N�o aceite',
    canonical: null,
  },
  data_emissao_titulo: {
    pos: [110, 117],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de emiss�o do t�tulo',
    canonical: 'dataEmissao',
  },
  juros_codigo: {
    pos: [118, 118],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de juros: 0=Isento, 1=Valor/dia, 2=Taxa mensal',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 0) return 'dispensado'
        if (code === 1) return 'valor'
        if (code === 2 || code === 3) return 'percentual' // 3=monthly rate in some banks
        return undefined
      },
    },
  },
  juros_data: {
    pos: [119, 126],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de in�cio da cobran�a de juros',
    canonical: 'juros.vigenciaAPartirDe',
  },
  juros_valor: {
    pos: [127, 141],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou taxa de juros',
    canonical: 'juros.valor',
  },
  desconto1_codigo: {
    pos: [142, 142],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo do primeiro desconto: 0=Sem, 1=Valor fixo, 2=Percentual',
    canonical: null,
  },
  desconto1_data: {
    pos: [143, 150],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data limite para primeiro desconto',
    canonical: 'desconto.dataLimite',
  },
  desconto1_valor: {
    pos: [151, 165],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou percentual do primeiro desconto',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [166, 180],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF',
    canonical: null,
  },
  valor_abatimento: {
    pos: [181, 195],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  identificacao_titulo_empresa: {
    pos: [196, 220],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o do t�tulo na empresa',
    canonical: null,
  },
  codigo_protesto: {
    pos: [221, 221],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo para protesto: 1=Protestar, 3=N�o protestar',
    canonical: null,
  },
  prazo_protesto: {
    pos: [222, 223],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de dias para protesto',
    canonical: null,
  },
  codigo_baixa: {
    pos: [224, 224],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo para baixa/devolu��o: 1=Baixar, 2=N�o baixar',
    canonical: null,
  },
  prazo_baixa: {
    pos: [225, 227],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de dias para baixa/devolu��o',
    canonical: null,
  },
  codigo_moeda: {
    pos: [228, 229],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da moeda: 09=Real',
    canonical: null,
  },
  numero_contrato: {
    pos: [230, 239],
    type: FieldType.NUM,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do contrato da opera��o de cr�dito',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [240, 240],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
