/**
 * Bradesco CNAB 240 - Segmento Q
 * Segmento Q (pos 8 = '3', pos 14 = 'Q')
 * Linha com os dados de quem vai pagar o boleto (o pagador/sacado): nome, CPF/CNPJ,
 * endereço, CEP, cidade, UF. Sempre vem logo após o Segmento P do mesmo boleto.
 * Terminologia:
 *   Cedente = quem emite o boleto (a empresa que está cobrando)
 *   Sacado/Pagador = quem vai pagar o boleto (o devedor)
 * Fonte do layout: pycnab240 + cnab_yaml generic FEBRABAN
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const BRADESCO_CNAB240_SEGMENT_Q: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de serviço',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Q',
    description: 'Segmento Q = dados do pagador',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento da remessa',
    canonical: null,
  },
  sacado_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  sacado_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ',
    canonical: 'sacado.documento',
  },
  sacado_nome: {
    pos: [34, 73],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador',
    canonical: 'sacado.nome',
  },
  sacado_endereco: {
    pos: [74, 113],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço',
    canonical: 'sacado.endereco.logradouro',
  },
  sacado_bairro: {
    pos: [114, 128],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro',
    canonical: 'sacado.endereco.bairro',
  },
  sacado_cep: {
    pos: [129, 133],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (5 dígitos)',
    canonical: 'sacado.endereco.cep',
  },
  sacado_cep_sufixo: {
    pos: [134, 136],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP sufixo',
    canonical: null,
  },
  sacado_cidade: {
    pos: [137, 151],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade',
    canonical: 'sacado.endereco.cidade',
  },
  sacado_uf: {
    pos: [152, 153],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF',
    canonical: 'sacado.endereco.estado',
  },
  beneficiario_final_inscricao_tipo: {
    pos: [154, 154],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do Beneficiário Final: 0=Isento, 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_inscricao_numero: {
    pos: [155, 169],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do Beneficiário Final',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [170, 209],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Beneficiário Final (nomenclatura BACEN 3598/3656/3956 é antigo "Sacador/Avalista")',
    canonical: null,
  },
  banco_correspondente: {
    pos: [210, 212],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do banco correspondente',
    canonical: null,
  },
  numero_banco_correspondente: {
    pos: [213, 232],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nosso número no banco correspondente',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [233, 240],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
