/**
 * Bradesco CNAB 240 - Segmento Y-01
 * 
 * Registro Detalhe - Segmento Y-01 (Beneficiário Final)
 * 
 * Registro opcional (Remessa/Retorno) que traz as informações completas do Beneficiário Final,
 * incluindo endereço completo. Este registro é diferente do Segmento Q, que apenas contém
 * tipo/número/nome do sacador/avalista (que pode ser o beneficiário final).
 * 
 * O Segmento Y-01 é usado quando há necessidade de identificar o beneficiário final da transação
 * com dados completos de endereço, conforme exigências regulatórias ou contratuais.
 * 
 * Estrutura:
 *   - Controle: banco (237), lote, registro tipo 3 (detalhe), segmento 'Y'
 *   - Código de registro opcional: '01' (identifica que é o Y-01)
 *   - Dados do beneficiário final: tipo/número inscrição, nome completo, endereço completo
 * 
 * Fonte: Manual oficial Bradesco CNAB 240, versão 04, dez/2024
 * Seção: "Registro Detalhe - Segmento Y-01"
 */

import { RecordSchema } from '../../../../types'

export const BRADESCO_CNAB240_SEGMENT_Y01: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de serviço',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = registro opcional',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento da remessa',
    canonical: null,
  },
  codigo_registro_opcional: {
    pos: [18, 19],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Código do registro opcional: 01=Beneficiário Final',
    canonical: null,
  },
  beneficiario_final_inscricao_tipo: {
    pos: [20, 20],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_inscricao_numero: {
    pos: [21, 35],
    type: 'num',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do beneficiário final',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [36, 75],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficiário final',
    canonical: null,
  },
  beneficiario_final_endereco: {
    pos: [76, 115],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do beneficiário final',
    canonical: null,
  },
  beneficiario_final_bairro: {
    pos: [116, 130],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do beneficiário final',
    canonical: null,
  },
  beneficiario_final_cep: {
    pos: [131, 135],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (5 dígitos)',
    canonical: null,
  },
  beneficiario_final_cep_sufixo: {
    pos: [136, 138],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP sufixo (3 dígitos)',
    canonical: null,
  },
  beneficiario_final_cidade: {
    pos: [139, 153],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do beneficiário final',
    canonical: null,
  },
  beneficiario_final_uf: {
    pos: [154, 155],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do beneficiário final',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [156, 240],
    type: 'alfa',
    size: 85,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '',
    description: 'Uso exclusivo FEBRABAN/CNAB',
    canonical: null,
  },
}
