/* *
 * Registro de encerramento do lote (tipo 5). *
 * IMPORTANTE: Diferente do Santander, o Sicredi usa a estrutura rica de
 * totalizadores mesmo em remessa (no simplifica). Os campos de totalizao
 * so preenchidos com zeros na remessa e usados apenas no retorno.
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_BATCH_TRAILER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '5',
    description: 'Tipo registro: 5=Trailer de Lote',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 17],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  quantidade_registros: {
    pos: [18, 23],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de Registros (soma dos registros tipo 1+3+5)',
    canonical: null,
  },
  totais_quantidade_titulos_simples: {
    pos: [24, 29],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade Ttulos Cobrana Simples (usado s no retorno; na remessa 000000)',
    canonical: null,
  },
  totais_valor_titulos_simples: {
    pos: [30, 46],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Total Ttulos Cobrana Simples (usado s no retorno; na remessa 00000000000000000)',
    canonical: null,
  },
  totais_quantidade_titulos_vinculados: {
    pos: [47, 52],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade Ttulos Cobrana Vinculada (usado s no retorno; na remessa 000000)',
    canonical: null,
  },
  totais_valor_titulos_vinculados: {
    pos: [53, 69],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Total Cobrana Vinculada (usado s no retorno; na remessa 00000000000000000)',
    canonical: null,
  },
  totais_quantidade_titulos_caucionados: {
    pos: [70, 75],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade Ttulos Cobrana Caucionada (usado s no retorno; na remessa 000000)',
    canonical: null,
  },
  totais_valor_titulos_caucionados: {
    pos: [76, 92],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Total Cobrana Caucionada (usado s no retorno; na remessa 00000000000000000)',
    canonical: null,
  },
  totais_quantidade_titulos_descontados: {
    pos: [93, 98],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade Ttulos Cobrana Descontada (usado s no retorno; na remessa 000000)',
    canonical: null,
  },
  totais_valor_titulos_descontados: {
    pos: [99, 115],
    type: FieldType.NUM,
    size: 17,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor Total Cobrana Descontada (usado s no retorno; na remessa 00000000000000000)',
    canonical: null,
  },
  numero_aviso: {
    pos: [116, 123],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do Aviso (no utilizado, sem preenchimento)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [124, 240],
    type: FieldType.ALFA,
    size: 117,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
