/* *
 * Registro de abertura do lote (tipo 1). *
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_BATCH_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de Servio (sequencial, 0001 no primeiro lote)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo registro: 1=Header Lote',
    canonical: null,
  },
  servico_operacao: {
    pos: [9, 9],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Tipo de Operao: R=Remessa',
    canonical: null,
  },
  servico_tipo: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Tipo de Servio: 01=Cobrana',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [12, 13],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_layout: {
    pos: [14, 16],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '040',
    description: 'Layout do Lote',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [17, 17],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrio da empresa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero de inscrio da empresa (CPF/CNPJ)',
    canonical: null,
  },
  convenio_codigo: {
    pos: [34, 53],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo do Convnio (sem preenchimento)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [54, 58],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agncia Cdigo do beneficirio/cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [59, 59],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agncia (sem preenchimento)',
    canonical: null,
  },
  cedente_conta: {
    pos: [60, 71],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta Nmero',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [72, 72],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DV da conta corrente',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [73, 73],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_nome: {
    pos: [74, 103],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa (sem acento)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [104, 143],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  mensagem_2: {
    pos: [144, 183],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 (sem preenchimento)',
    canonical: null,
  },
  remessa_sequencial: {
    pos: [184, 191],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial da remessa (sequencial, 00000001 no primeiro)',
    canonical: null,
  },
  data_geracao: {
    pos: [192, 199],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de gerao',
    canonical: null,
  },
  data_credito: {
    pos: [200, 207],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data do Crdito (s usado no retorno; na remessa 00000000)',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [208, 240],
    type: FieldType.ALFA,
    size: 33,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
