/**
 * Schema do Header de Lote - Sicredi CNAB 240
 * 
 * Registro de abertura do lote (tipo 1).
 * 
 * Tipo de registro: 1 (header de lote)
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, versão 29 (seção 8 - Arquivo de Remessa)
 * - Layout CNAB 240 versão 081
 */

import { RecordSchema } from '../../../../types'

export const SICREDI_CNAB240_BATCH_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Código FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Lote de Serviço (sequencial, 0001 no primeiro lote)',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo registro: 1=Header Lote',
    canonical: null,
  },
  servico_operacao: {
    pos: [9, 9],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Tipo de Operação: R=Remessa',
    canonical: null,
  },
  servico_tipo: {
    pos: [10, 11],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Tipo de Serviço: 01=Cobrança',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [12, 13],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_layout: {
    pos: [14, 16],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '040',
    description: 'Layout do Lote',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [17, 17],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição da empresa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 33],
    type: 'num',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número de inscrição da empresa (CPF/CNPJ)',
    canonical: null,
  },
  convenio_codigo: {
    pos: [34, 53],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código do Convênio (sem preenchimento)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [54, 58],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência Código do beneficiário/cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [59, 59],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agência (sem preenchimento)',
    canonical: null,
  },
  cedente_conta: {
    pos: [60, 71],
    type: 'num',
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta Número',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [72, 72],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DV da conta corrente',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [73, 73],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_nome: {
    pos: [74, 103],
    type: 'alfa',
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa (sem acento)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [104, 143],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  mensagem_2: {
    pos: [144, 183],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Mensagem 2 (sem preenchimento)',
    canonical: null,
  },
  remessa_sequencial: {
    pos: [184, 191],
    type: 'num',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial da remessa (sequencial, 00000001 no primeiro)',
    canonical: null,
  },
  data_geracao: {
    pos: [192, 199],
    type: 'data',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data de geração',
    canonical: null,
  },
  data_credito: {
    pos: [200, 207],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data do Crédito (só usado no retorno; na remessa 00000000)',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [208, 240],
    type: 'alfa',
    size: 33,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
