/**
 * Schema do Header de Arquivo - Sicredi CNAB 240
 * 
 * Registro de abertura do arquivo (tipo 0, lote 0000).
 * 
 * Tipo de registro: 0 (header de arquivo)
 * Lote: 0000
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, versão 29 (seção 8 - Arquivo de Remessa)
 * - Layout CNAB 240 versão 081
 */

import { RecordSchema } from '../../../../types'

export const SICREDI_CNAB240_FILE_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Código FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0000',
    description: 'Lote 0000 indica header de arquivo',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Tipo registro: 0=Header de Arquivo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 17],
    type: 'alfa',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição da empresa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 32],
    type: 'num',
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do beneficiário/cedente',
    canonical: 'cedente.documento',
  },
  convenio: {
    pos: [33, 52],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Convênio (sem preenchimento)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [53, 57],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência (Conta Corrente) do beneficiário/cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [58, 58],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agência (sem preenchimento)',
    canonical: null,
  },
  cedente_conta: {
    pos: [59, 70],
    type: 'num',
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente do beneficiário/cedente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [71, 71],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DV da conta corrente',
    canonical: null,
  },
  cedente_conta_dv_adicional: {
    pos: [72, 72],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV adicional (sem preenchimento - "o Sicredi não usa esse campo")',
    canonical: null,
  },
  cedente_nome: {
    pos: [73, 102],
    type: 'alfa',
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa (sem acento gráfico)',
    canonical: 'cedente.nome',
  },
  nome_do_banco: {
    pos: [103, 132],
    type: 'alfa',
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'SICREDI',
    description: 'Nome do banco',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [133, 142],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  arquivo_codigo: {
    pos: [143, 143],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Código do arquivo: 1=Remessa',
    canonical: null,
  },
  arquivo_data_de_geracao: {
    pos: [144, 151],
    type: 'data',
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data de geração do arquivo',
    canonical: null,
  },
  arquivo_hora_de_geracao: {
    pos: [152, 157],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Hora de geração do arquivo (HHMMSS)',
    canonical: null,
  },
  arquivo_sequencial: {
    pos: [158, 163],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do arquivo de remessa (começa em 000001)',
    canonical: null,
  },
  arquivo_layout: {
    pos: [164, 166],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '081',
    description: 'Layout do arquivo',
    canonical: null,
  },
  densidade: {
    pos: [167, 171],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01600',
    description: 'Densidade de gravação',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [172, 191],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [192, 211],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [212, 240],
    type: 'alfa',
    size: 29,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
