/* *
 * Registro de abertura do arquivo (tipo 0, lote 0000).
 * Lote: 0000
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, vers�o 29 (se��o 8 - Arquivo de Remessa)
 * - Layout CNAB 240 vers�o 081
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_FILE_HEADER: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'C�digo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0000',
    description: 'Lote 0000 indica header de arquivo',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Tipo registro: 0=Header de Arquivo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [9, 17],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cedente_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o da empresa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  cedente_inscricao_numero: {
    pos: [19, 32],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do benefici�rio/cedente',
    canonical: 'cedente.documento',
  },
  convenio: {
    pos: [33, 52],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conv�nio (sem preenchimento)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [53, 57],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia (Conta Corrente) do benefici�rio/cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [58, 58],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da ag�ncia (sem preenchimento)',
    canonical: null,
  },
  cedente_conta: {
    pos: [59, 70],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente do benefici�rio/cedente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [71, 71],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DV da conta corrente',
    canonical: null,
  },
  cedente_conta_dv_adicional: {
    pos: [72, 72],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV adicional (sem preenchimento - "o Sicredi n�o usa esse campo")',
    canonical: null,
  },
  cedente_nome: {
    pos: [73, 102],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome da empresa (sem acento gr�fico)',
    canonical: 'cedente.nome',
  },
  nome_do_banco: {
    pos: [103, 132],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'SICREDI',
    description: 'Nome do banco',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [133, 142],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  arquivo_codigo: {
    pos: [143, 143],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'C�digo do arquivo: 1=Remessa',
    canonical: null,
  },
  arquivo_data_de_geracao: {
    pos: [144, 151],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de gera��o do arquivo',
    canonical: null,
  },
  arquivo_hora_de_geracao: {
    pos: [152, 157],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Hora de gera��o do arquivo (HHMMSS)',
    canonical: null,
  },
  arquivo_sequencial: {
    pos: [158, 163],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do arquivo de remessa (come�a em 000001)',
    canonical: null,
  },
  arquivo_layout: {
    pos: [164, 166],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '081',
    description: 'Layout do arquivo',
    canonical: null,
  },
  densidade: {
    pos: [167, 171],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01600',
    description: 'Densidade de grava��o',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [172, 191],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [192, 211],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [212, 240],
    type: FieldType.ALFA,
    size: 29,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
