/**
 * Schema do Segmento Q - Sicredi CNAB 240
 * 
 * Contém os dados do pagador (sacado): nome, CPF/CNPJ, endereço,
 * CEP, cidade, UF, etc.
 * 
 * Tipo de registro: 3 (detalhe)
 * Segmento: Q
 * 
 * IMPORTANTE: O Sicredi já usa a nomenclatura "Beneficiário Final"
 * conforme Circulares BACEN 3598, 3656 e 3956.
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, versão 29 (seção 8 - Arquivo de Remessa)
 * - Layout CNAB 240 versão 081
 */

import { RecordSchema } from '../../../../types'

export const SICREDI_CNAB240_SEGMENT_Q: RecordSchema = {
  // ========== CONTROLE (1-17) ==========
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Código FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Q',
    description: 'Segmento Q = dados do pagador',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento (mesma tabela do Segmento P)',
    canonical: null,
  },

  // ========== DADOS DO PAGADOR (18-153) ==========
  sacado_inscricao_tipo: {
    pos: [18, 18],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de pessoa (pagador): 1=CPF, 2=CNPJ',
    canonical: null,
  },
  sacado_inscricao_numero: {
    pos: [19, 33],
    type: 'num',
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  sacado_nome: {
    pos: [34, 73],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador (sem acentuação)',
    canonical: 'sacado.nome',
  },
  sacado_endereco: {
    pos: [74, 113],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  cnab_exclusivo_2: {
    pos: [114, 128],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN (sem preenchimento)',
    canonical: null,
  },
  sacado_cep: {
    pos: [129, 136],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (8 dígitos)',
    canonical: 'sacado.endereco.cep',
  },
  sacado_cidade: {
    pos: [137, 151],
    type: 'alfa',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade',
    canonical: 'sacado.endereco.cidade',
  },
  sacado_uf: {
    pos: [152, 153],
    type: 'alfa',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF',
    canonical: 'sacado.endereco.estado',
  },

  // ========== BENEFICIÁRIO FINAL (154-209) ==========
  beneficiario_final_tipo: {
    pos: [154, 154],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de pessoa (Beneficiário Final): 0=Sem Beneficiário Final, 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_inscricao: {
    pos: [155, 169],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do Beneficiário Final (branco se não houver)',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [170, 209],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Beneficiário Final (sem acentuação)',
    canonical: null,
  },

  // ========== BANCO CORRESPONDENTE (210-232) ==========
  banco_correspondente_codigo: {
    pos: [210, 212],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código Banco Correspondente (não utilizado, 000)',
    canonical: null,
  },
  banco_correspondente_nosso_numero: {
    pos: [213, 232],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nosso Número no Banco Correspondente (sem preenchimento)',
    canonical: null,
  },

  // ========== RESERVADO (233-240) ==========
  cnab_exclusivo_3: {
    pos: [233, 240],
    type: 'alfa',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
