/* *
 * Contm os dados financeiros do ttulo (boleto): valor, vencimento,
 * nosso nmero, juros, descontos, etc.
 * Segmento: P
 * 
 * IMPORTANTE: O campo valor_titulo (pos 086-100) tem decimais condicionais:
 * - 2 decimais quando moeda corrente (moeda_codigo = '09')
 * - 5 decimais quando moeda varivel (qualquer outro cdigo)
 * O schema declara `decimais: 2` fixo (correto s para moeda corrente) - use
 * `resolveTitleAmountSegmentP` de `segment-p-helper.ts` para obter o valor
 * com a preciso correta em ambos os casos.
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_SEGMENT_P: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote (comea em 00001)',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'P',
    description: 'Segmento P = dados do ttulo',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento (varivel: 01,02,04,05,06,07,08,09,10,11,12,13,16,17,31,45,75,76)',
    canonical: null,
  },
  cedente_agencia: {
    pos: [18, 22],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agncia do beneficirio/cedente',
    canonical: null,
  },
  cedente_agencia_dv: {
    pos: [23, 23],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agncia (sem preenchimento)',
    canonical: null,
  },
  cedente_conta: {
    pos: [24, 35],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente do beneficirio/cedente',
    canonical: null,
  },
  cedente_conta_dv: {
    pos: [36, 36],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'DV da conta corrente',
    canonical: null,
  },
  cedente_dv_agencia_conta: {
    pos: [37, 37],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agncia/Cooperativa (sem preenchimento)',
    canonical: null,
  },
  nosso_numero: {
    pos: [38, 46],
    type: FieldType.NUM,
    size: 9,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso Nmero (9 dgitos reais: formato "AA B XXXXX D" = ano+byte gerao+sequencial+DV)',
    canonical: 'nossoNumero',
  },
  nosso_numero_complemento: {
    pos: [47, 57],
    type: FieldType.ALFA,
    size: 11,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Complemento do Nosso Nmero (sem preenchimento - posies 47-57 no usadas)',
    canonical: null,
  },
  carteira: {
    pos: [58, 58],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Carteira: 1=Cobrana Simples',
    canonical: null,
  },
  cadastramento: {
    pos: [59, 59],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Cadastramento: 1=Cobrana com registro',
    canonical: null,
  },
  tipo_documento: {
    pos: [60, 60],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de documento: 1=Tradicional, 2=Escritural (Sicredi no diferencia)',
    canonical: null,
  },
  emissao_boleto: {
    pos: [61, 61],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Emisso Boleto: 1=Sicredi emite, 2=Beneficirio emite',
    canonical: null,
  },
  distribuicao_boleto: {
    pos: [62, 62],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Distribuio/Postagem: 1=Sicredi distribui, 2=Beneficirio distribui',
    canonical: null,
  },
  seu_numero: {
    pos: [63, 77],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Seu Nmero (s as 10 primeiras posies 063-072 so validadas pelo Sicredi)',
    canonical: 'numeroDocumento',
  },
  vencimento_titulo: {
    pos: [78, 85],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de vencimento do ttulo (deve ser emisso+7 dias se emisso Sicredi)',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [86, 100],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'Valor nominal do ttulo (decimais condicionais: 2 se moeda corrente, 5 se moeda varivel - use resolveTitleAmountSegmentP)',
    canonical: 'valor',
  },
  agencia_cobradora: {
    pos: [101, 105],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cooperativa/Agncia Cobradora (no usado, 00000)',
    canonical: null,
  },
  agencia_cobradora_dv: {
    pos: [106, 106],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV da agncia cobradora (sem preenchimento)',
    canonical: null,
  },
  especie_titulo: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Espcie de Ttulo: 03,05,06,07,12,13,16,17,19,32,99',
    canonical: null,
  },
  aceite: {
    pos: [109, 109],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Aceite: A=com aceite, N=sem aceite',
    canonical: null,
  },
  data_emissao_titulo: {
    pos: [110, 117],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data de emisso do ttulo',
    canonical: 'dataEmissao',
  },
  juros_mora_codigo: {
    pos: [118, 118],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de Juros: 1=Valor monetrio, 2=Taxa mensal, 3=Isento',
    canonical: {
      field: 'juros.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        if (code === 1) return 'valor'
        if (code === 2) return 'percentual'
        if (code === 3) return 'dispensado'
        return undefined
      },
    },
  },
  juros_mora_data: {
    pos: [119, 126],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data Juros (DDMMAAAA ou zeros)',
    canonical: 'juros.vigenciaAPartirDe',
  },
  juros_mora_valor: {
    pos: [127, 141],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros (valor monetrio ou percentual conforme cdigo 118)',
    canonical: 'juros.valor',
  },
  desconto_codigo: {
    pos: [142, 142],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo desconto 1: 0=Sem, 1=Valor fixo, 2=Percentual, 3=Antecipao, 7=Cancelamento',
    canonical: null,
  },
  desconto_data: {
    pos: [143, 150],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data desconto 1 (DDMMAAAA ou zeros)',
    canonical: null,
  },
  desconto_valor: {
    pos: [151, 165],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor desconto 1',
    canonical: 'desconto.valor',
  },
  iof_valor: {
    pos: [166, 180],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor IOF (no utilizado pelo Sicredi, sempre 000000000000000)',
    canonical: null,
  },
  abatimento_valor: {
    pos: [181, 195],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor abatimento',
    canonical: 'abatimento.valor',
  },
  uso_empresa: {
    pos: [196, 220],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso Empresa Beneficirio (identificao do ttulo na empresa)',
    canonical: null,
  },
  protesto_codigo: {
    pos: [221, 221],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo para Protesto/Negativao: 1=Protestar, 3=No protestar/negativar, 8=Negativar, 9=Cancelar',
    canonical: null,
  },
  protesto_prazo: {
    pos: [222, 223],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prazo para Protesto/Negativao (mnimo 03 dias)',
    canonical: null,
  },
  baixa_codigo: {
    pos: [224, 224],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Cdigo para Baixa/Devoluo (sempre 1)',
    canonical: null,
  },
  baixa_prazo: {
    pos: [225, 227],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero de dias para baixa/devoluo (no utilizado, 000)',
    canonical: null,
  },
  moeda_codigo: {
    pos: [228, 229],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '09',
    description: 'Cdigo da Moeda: 09=Real',
    canonical: null,
  },
  contrato_numero: {
    pos: [230, 239],
    type: FieldType.NUM,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do contrato (no utilizado, 0000000000)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [240, 240],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo Sicredi',
    canonical: null,
  },
}
