/* *
 * Cont�m os dados do pagador (sacado): nome, CPF/CNPJ, endere�o,
 * CEP, cidade, UF, etc.
 * Segmento: Q
 * 
 * IMPORTANTE: O Sicredi j� usa a nomenclatura "Benefici�rio Final"
 * conforme Circulares BACEN 3598, 3656 e 3956.
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, vers�o 29 (se��o 8 - Arquivo de Remessa)
 * - Layout CNAB 240 vers�o 081
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_SEGMENT_Q: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'C�digo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Q',
    description: 'Segmento Q = dados do pagador',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento (mesma tabela do Segmento P)',
    canonical: null,
  },
  sacado_inscricao_tipo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de pessoa (pagador): 1=CPF, 2=CNPJ',
    canonical: null,
  },
  sacado_inscricao_numero: {
    pos: [19, 33],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do pagador',
    canonical: 'sacado.documento',
  },
  sacado_nome: {
    pos: [34, 73],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do pagador (sem acentua��o)',
    canonical: 'sacado.nome',
  },
  sacado_endereco: {
    pos: [74, 113],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do pagador',
    canonical: 'sacado.endereco.logradouro',
  },
  cnab_exclusivo_2: {
    pos: [114, 128],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN (sem preenchimento)',
    canonical: null,
  },
  sacado_cep: {
    pos: [129, 136],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (8 d�gitos)',
    canonical: 'sacado.endereco.cep',
  },
  sacado_cidade: {
    pos: [137, 151],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade',
    canonical: 'sacado.endereco.cidade',
  },
  sacado_uf: {
    pos: [152, 153],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF',
    canonical: 'sacado.endereco.estado',
  },
  beneficiario_final_tipo: {
    pos: [154, 154],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de pessoa (Benefici�rio Final): 0=Sem Benefici�rio Final, 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_inscricao: {
    pos: [155, 169],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do Benefici�rio Final (branco se n�o houver)',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [170, 209],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Benefici�rio Final (sem acentua��o)',
    canonical: null,
  },
  banco_correspondente_codigo: {
    pos: [210, 212],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo Banco Correspondente (n�o utilizado, 000)',
    canonical: null,
  },
  banco_correspondente_nosso_numero: {
    pos: [213, 232],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nosso N�mero no Banco Correspondente (sem preenchimento)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [233, 240],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
}
