/**
 * Schema do Segmento R - Sicredi CNAB 240
 * 
 * Registro opcional para descontos adicionais (2 e 3) e multa.
 * 
 * IMPORTANTE: A maioria dos campos deste segmento (posições 090-240)
 * é marcada como "não utilizado pelo Sicredi" no manual oficial.
 * Apenas os campos de desconto 2/3 e multa (018-089) são funcionais.
 * 
 * Tipo de registro: 3 (detalhe)
 * Segmento: R
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, versão 29 (seção 8 - Arquivo de Remessa)
 * - Layout CNAB 240 versão 081
 */

import { RecordSchema } from '../../../../types'

export const SICREDI_CNAB240_SEGMENT_R: RecordSchema = {
  // ========== CONTROLE (1-17) ==========
  controle_banco: {
    pos: [1, 3],
    type: 'num',
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Código FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: 'num',
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: 'num',
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Segmento R = descontos adicionais e multa',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: 'num',
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de movimento (variável: 01,02,04,05,06,07,08,09,10,11,12,13,16,17,31,45,75,76)',
    canonical: null,
  },

  // ========== DESCONTO 2 (18-41) ==========
  desconto2_codigo: {
    pos: [18, 18],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código desconto 2: 0=Sem, 1=Valor fixo, 2=Percentual, 3=Antecipação, 7=Cancelamento',
    canonical: null,
  },
  desconto2_data: {
    pos: [19, 26],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data desconto 2 (DDMMAAAA ou zeros)',
    canonical: null,
  },
  desconto2_valor: {
    pos: [27, 41],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor desconto 2',
    canonical: null,
  },

  // ========== DESCONTO 3 (42-65) ==========
  desconto3_codigo: {
    pos: [42, 42],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código desconto 3: 0=Sem, 1=Valor fixo, 2=Percentual, 3=Antecipação, 7=Cancelamento',
    canonical: null,
  },
  desconto3_data: {
    pos: [43, 50],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data desconto 3 (DDMMAAAA ou zeros)',
    canonical: null,
  },
  desconto3_valor: {
    pos: [51, 65],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor desconto 3',
    canonical: null,
  },

  // ========== MULTA (66-89) ==========
  multa_codigo: {
    pos: [66, 66],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código da Multa: 1=Valor monetário, 2=Percentual',
    canonical: {
      field: 'multa.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        // Sicredi doesn't document code for "waived" - implementing only 1 and 2
        if (code === 1) return 'valor'
        if (code === 2) return 'percentual'
        return undefined
      },
    },
  },
  multa_data: {
    pos: [67, 74],
    type: 'data',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: 'DDMMAAAA',
    pattern: null,
    description: 'Data da Multa (DDMMAAAA ou zeros)',
    canonical: 'multa.vigenciaAPartirDe',
  },
  multa_valor: {
    pos: [75, 89],
    type: 'num',
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou Percentual da Multa',
    canonical: 'multa.valor',
  },

  // ========== CAMPOS NÃO UTILIZADOS PELO SICREDI (90-240) ==========
  cnab_exclusivo_2: {
    pos: [90, 99],
    type: 'alfa',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informação ao Pagador (não usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [100, 139],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (não usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [140, 179],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (não usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [180, 199],
    type: 'alfa',
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (não usado pelo Sicredi)',
    canonical: null,
  },
  debito_ocorrencia_codigo: {
    pos: [200, 207],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código Ocorrência Pagador (não usado pelo Sicredi, 00000000)',
    canonical: null,
  },
  debito_banco: {
    pos: [208, 210],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Banco débito automático (não usado pelo Sicredi, 000)',
    canonical: null,
  },
  debito_agencia: {
    pos: [211, 215],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência débito automático (não usado pelo Sicredi, 00000)',
    canonical: null,
  },
  debito_agencia_dv: {
    pos: [216, 216],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV agência débito (não usado pelo Sicredi, 0)',
    canonical: null,
  },
  debito_conta: {
    pos: [217, 228],
    type: 'num',
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta Corrente débito automático (não usado pelo Sicredi, 000000000000)',
    canonical: null,
  },
  debito_conta_dv: {
    pos: [229, 229],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV conta débito (não usado pelo Sicredi)',
    canonical: null,
  },
  debito_agencia_conta_dv: {
    pos: [230, 230],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV agência/conta débito (não usado pelo Sicredi)',
    canonical: null,
  },
  debito_aviso_emissao: {
    pos: [231, 231],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação Emissão Aviso Débito (não usado pelo Sicredi, 0)',
    canonical: null,
  },
  cnab_exclusivo_6: {
    pos: [232, 240],
    type: 'alfa',
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (não usado pelo Sicredi)',
    canonical: null,
  },
}
