export { Cnab240ItauBoletoValorTituloField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-valor-titulo-field'
export { Cnab240ItauBoletoVencimentoField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-vencimento-field'
export { Cnab240ItauBoletoSacadoDocumentoField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-sacado-documento-field'
export { Cnab240ItauBoletoEnderecoField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-endereco-field'
export { Cnab240ItauBoletoBairroField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-bairro-field'
export { Cnab240ItauBoletoCepField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-cep-field'
export { Cnab240ItauBoletoCidadeField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-cidade-field'
export { Cnab240ItauBoletoUfField } from '@cnab/bank/itau/cnab/cnab240/field/cnab240-itau-boleto-uf-field'
