/* *
 * Registro opcional para descontos adicionais (2 e 3) e multa.
 * IMPORTANTE: A maioria dos campos deste segmento (posi��es 090-240)
 * � marcada como "n�o utilizado pelo Sicredi" no manual oficial.
 * Apenas os campos de desconto 2/3 e multa (018-089) s�o funcionais.
 * Segmento: R
 * 
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, vers�o 29 (se��o 8 - Arquivo de Remessa)
 * - Layout CNAB 240 vers�o 081
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_SEGMENT_R: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'C�digo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'R',
    description: 'Segmento R = descontos adicionais e multa',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo de movimento (vari�vel: 01,02,04,05,06,07,08,09,10,11,12,13,16,17,31,45,75,76)',
    canonical: null,
  },
  desconto2_codigo: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo desconto 2: 0=Sem, 1=Valor fixo, 2=Percentual, 3=Antecipa��o, 7=Cancelamento',
    canonical: null,
  },
  desconto2_data: {
    pos: [19, 26],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data desconto 2 (DDMMAAAA ou zeros)',
    canonical: null,
  },
  desconto2_valor: {
    pos: [27, 41],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor desconto 2',
    canonical: null,
  },
  desconto3_codigo: {
    pos: [42, 42],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo desconto 3: 0=Sem, 1=Valor fixo, 2=Percentual, 3=Antecipa��o, 7=Cancelamento',
    canonical: null,
  },
  desconto3_data: {
    pos: [43, 50],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data desconto 3 (DDMMAAAA ou zeros)',
    canonical: null,
  },
  desconto3_valor: {
    pos: [51, 65],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor desconto 3',
    canonical: null,
  },
  multa_codigo: {
    pos: [66, 66],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da Multa: 1=Valor monet�rio, 2=Percentual',
    canonical: {
      field: 'multa.tipo',
      interpret: (value: unknown) => {
        const code = Number(value)
        // Sicredi n�o documenta c�digo para "dispensado" - implementando apenas 1 e 2
        if (code === 1) return 'valor'
        if (code === 2) return 'percentual'
        return undefined
      },
    },
  },
  multa_data: {
    pos: [67, 74],
    type: FieldType.DATA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAAAA,
    pattern: null,
    description: 'Data da Multa (DDMMAAAA ou zeros)',
    canonical: 'multa.vigenciaAPartirDe',
  },
  multa_valor: {
    pos: [75, 89],
    type: FieldType.NUM,
    size: 15,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor ou Percentual da Multa',
    canonical: 'multa.valor',
  },
  cnab_exclusivo_2: {
    pos: [90, 99],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informa��o ao Pagador (n�o usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [100, 139],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (n�o usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [140, 179],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (n�o usado pelo Sicredi)',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [180, 199],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (n�o usado pelo Sicredi)',
    canonical: null,
  },
  debito_ocorrencia_codigo: {
    pos: [200, 207],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'C�digo Ocorr�ncia Pagador (n�o usado pelo Sicredi, 00000000)',
    canonical: null,
  },
  debito_banco: {
    pos: [208, 210],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Banco d�bito autom�tico (n�o usado pelo Sicredi, 000)',
    canonical: null,
  },
  debito_agencia: {
    pos: [211, 215],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia d�bito autom�tico (n�o usado pelo Sicredi, 00000)',
    canonical: null,
  },
  debito_agencia_dv: {
    pos: [216, 216],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV ag�ncia d�bito (n�o usado pelo Sicredi, 0)',
    canonical: null,
  },
  debito_conta: {
    pos: [217, 228],
    type: FieldType.NUM,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta Corrente d�bito autom�tico (n�o usado pelo Sicredi, 000000000000)',
    canonical: null,
  },
  debito_conta_dv: {
    pos: [229, 229],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV conta d�bito (n�o usado pelo Sicredi)',
    canonical: null,
  },
  debito_agencia_conta_dv: {
    pos: [230, 230],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'DV ag�ncia/conta d�bito (n�o usado pelo Sicredi)',
    canonical: null,
  },
  debito_aviso_emissao: {
    pos: [231, 231],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identifica��o Emiss�o Aviso D�bito (n�o usado pelo Sicredi, 0)',
    canonical: null,
  },
  cnab_exclusivo_6: {
    pos: [232, 240],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (n�o usado pelo Sicredi)',
    canonical: null,
  },
}
