/* *
 * Registro obrigatrio quando boleto hbrido (QR Code/PIX).
 * IMPORTANTE: Este segmento no  opcional condicional simples.
 *  obrigatrio sempre que o boleto usa QR Code/PIX hbrido.
 * Segmento: Y
 * Cdigo do registro: 04
 * NOTA: Campo 070-071 tem inconsistncia no manual (TAM="01" mas intervalo
 * tem 2 posies). Implementado com 2 posies conforme os vizinhos 069 e 072.
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, FieldType } from '@/types/all-types'

export const SICREDI_CNAB240_SEGMENT_Y04: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = dados adicionais',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento (domnio pode ser restrito a "01" para este segmento - conferir manual)',
    canonical: null,
  },
  codigo_registro: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '04',
    description: 'Cdigo do registro: 04=PIX/QR Code',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [20, 69],
    type: FieldType.ALFA,
    size: 50,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sem preenchimento',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [70, 71],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sem preenchimento (nota: manual declara TAM="01" mas intervalo tem 2 posies)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [72, 80],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sem preenchimento',
    canonical: null,
  },
  pix_tipo_chave: {
    pos: [81, 81],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de chave PIX (sem preenchimento - Sicredi no valida)',
    canonical: null,
  },
  pix_chave: {
    pos: [82, 158],
    type: FieldType.ALFA,
    size: 77,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Chave PIX aleatria gerada pelo Sicredi',
    canonical: null,
  },
  pix_txid: {
    pos: [159, 193],
    type: FieldType.ALFA,
    size: 35,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'TXID (sem preenchimento - Sicredi gera e vincula ao ttulo)',
    canonical: null,
  },
  cnab_exclusivo_5: {
    pos: [194, 240],
    type: FieldType.ALFA,
    size: 47,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (sem preenchimento)',
    canonical: null,
  },
}
