/* *
 * Registro opcional para identificao do Beneficirio Final.
 * NOTA: O manual Sicredi j usa a nomenclatura correta "Beneficirio Final"
 * conforme Circulares BACEN: 3598, 3656 e 3956, que substituram a
 * nomenclatura antiga "Sacador/Avalista".
 * Segmento: Y
 * Cdigo do registro: 01
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, FieldType } from '@tp-types/index'

export const SICREDI_CNAB240_SEGMENT_Y01: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo registro: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'Y',
    description: 'Segmento Y = dados adicionais',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CNAB/FEBRABAN',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento (varivel)',
    canonical: null,
  },
  codigo_registro: {
    pos: [18, 19],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Cdigo do registro: 01=Beneficirio Final',
    canonical: null,
  },
  beneficiario_final_tipo_pessoa: {
    pos: [20, 20],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de pessoa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  beneficiario_final_cpf_cnpj: {
    pos: [21, 35],
    type: FieldType.NUM,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF/CNPJ do Beneficirio Final',
    canonical: null,
  },
  beneficiario_final_nome: {
    pos: [36, 75],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do Beneficirio Final (sem acentuao)',
    canonical: null,
  },
  beneficiario_final_endereco: {
    pos: [76, 115],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereo do Beneficirio Final',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [116, 130],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Sem preenchimento',
    canonical: null,
  },
  beneficiario_final_cep: {
    pos: [131, 138],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP (8 dgitos)',
    canonical: null,
  },
  beneficiario_final_cidade: {
    pos: [139, 153],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do Beneficirio Final',
    canonical: null,
  },
  beneficiario_final_uf: {
    pos: [154, 155],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do Beneficirio Final',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [156, 240],
    type: FieldType.ALFA,
    size: 85,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (sem preenchimento)',
    canonical: null,
  },
}
