/**
 * Sicredi CNAB 240 - Segmento S (Mensagens para impresso)
 * Registro opcional para mensagens de impresso no boleto.
 * Possui duas variantes identificadas pelo campo pos 18 (tipo_impressao):
 * - Variante 1 (pos 18 = '1' ou '2'): Frente/Verso do boleto (layout comum)
 * - Variante 2 (pos 18 = '3'): Corpo de instrues da ficha de compensao
 * Segmento S (pos 8 = '3', pos 14 = 'S')
 * 
 * NOTA: Manual menciona "Tipo de impresso" com domnio {1=Frente, 2=Verso, 3=Ficha}
 * mas apenas duas estruturas de campos distintas (1 e 2 compartilham, 3  prprio).
 * Baseado em:
 * - Manual oficial Sicredi CNAB 240, verso 29 (seo 8 - Arquivo de Remessa)
 * - Layout CNAB 240 verso 081
 */

import { RecordSchema, FieldType } from '@/types/all-types'
export const SICREDI_CNAB240_SEGMENT_S: RecordSchema = {
  controle_banco: {
    pos: [1, 3],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '748',
    description: 'Cdigo FEBRABAN do Sicredi',
    canonical: null,
  },
  controle_lote: {
    pos: [4, 7],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero do lote',
    canonical: null,
  },
  controle_registro: {
    pos: [8, 8],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '3',
    description: 'Tipo: 3=Detalhe',
    canonical: null,
  },
  servico_numero_registro: {
    pos: [9, 13],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nmero sequencial do registro no lote',
    canonical: null,
  },
  servico_segmento: {
    pos: [14, 14],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'S',
    description: 'Segmento S = mensagens para impresso',
    canonical: null,
  },
  cnab_exclusivo_1: {
    pos: [15, 15],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo Sicredi',
    canonical: null,
  },
  servico_codigo_movimento: {
    pos: [16, 17],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Cdigo de movimento Remessa (varivel)',
    canonical: null,
  },
  tipo_impressao: {
    pos: [18, 18],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de Impresso: 1=Frente do boleto, 2=Verso do boleto, 3=Corpo de instrues da ficha',
    canonical: null,
  },
}
export const SICREDI_CNAB240_SEGMENT_S_FRONT_BACK: RecordSchema = {
  ...SICREDI_CNAB240_SEGMENT_S,
  numero_linha: {
    pos: [19, 20],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero da linha a ser impressa (01 a 20)',
    canonical: null,
  },
  mensagem: {
    pos: [21, 100],
    type: FieldType.ALFA,
    size: 80,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem (texto livre)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [101, 160],
    type: FieldType.ALFA,
    size: 60,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (reservado)',
    canonical: null,
  },
  tipo_fonte: {
    pos: [161, 162],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de Fonte (sem preenchimento)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [163, 240],
    type: FieldType.ALFA,
    size: 78,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (reservado)',
    canonical: null,
  },
}
export const SICREDI_CNAB240_SEGMENT_S_BODY_INSTRUCTIONS: RecordSchema = {
  ...SICREDI_CNAB240_SEGMENT_S,
  numero_linha: {
    pos: [19, 20],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nmero da linha a ser impressa (01 a 20)',
    canonical: null,
  },
  mensagem_1: {
    pos: [21, 58],
    type: FieldType.ALFA,
    size: 38,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem 1 (texto livre)',
    canonical: null,
  },
  mensagem_2: {
    pos: [59, 98],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem 2 (texto livre)',
    canonical: null,
  },
  mensagem_3: {
    pos: [99, 138],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem 3 (texto livre)',
    canonical: null,
  },
  cnab_exclusivo_2: {
    pos: [139, 178],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem (sem preenchimento)',
    canonical: null,
  },
  cnab_exclusivo_3: {
    pos: [179, 218],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Informativo/Mensagem (sem preenchimento)',
    canonical: null,
  },
  cnab_exclusivo_4: {
    pos: [219, 240],
    type: FieldType.ALFA,
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CNAB (no documentado no manual, assumido como reservado at completar 240 bytes)',
    canonical: null,
  },
}
