/**
 * Banco do Brasil (001) — CNAB 400 — Detalhe de Remessa (Registro Tipo 7)
 * PARTICULARIDADE DO BB: tipo_registro = '7' (não '1' como padrão FEBRABAN)
 *
 * Fonte:
 * - Manual oficial BB remessa (Doc2627CBR641Pos7.pdf, abril/2012) — §3 p.5-6
 * - Manual oficial BB 2024 (banco_do_brasil_2024_cnab400.pdf, jun/2024) — campos tipo_moeda
 *   e indicador_recebimento_parcial revelados para convênios > 1.000.000
 * - brcobranca (remessa/cnab400/banco_brasil.rb)
 * - cnab_yaml (cnab400/001/remessa/detalhe.yml)
 * - laravel-boleto (Cnab/Remessa/Cnab400/Banco/Bb.php)
 * Observação importante sobre campo "nome" (235-271):
 * O BB usa apenas 37 posições para o nome do sacado, seguido de 3 brancos (272-274).
 * Padrão FEBRABAN são 40 posições, mas o BB mantém essa peculiaridade.
 * Confirmado pelo manual oficial e todas as libs de referência.
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '7',
    description: 'Tipo do registro detalhe (7 no BB - não 1 como padrão FEBRABAN)',
    canonical: null,
  },
  codigo_inscricao_cedente: {
    pos: [2, 3],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do cedente: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  numero_inscricao_cedente: {
    pos: [4, 17],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do cedente',
    canonical: null,
  },
  agencia: {
    pos: [18, 21],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da agência do cedente',
    canonical: null,
  },
  agencia_dv: {
    pos: [22, 22],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência',
    canonical: null,
  },
  conta: {
    pos: [23, 30],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente',
    canonical: null,
  },
  conta_dv: {
    pos: [31, 31],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },
  convenio: {
    pos: [32, 38],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do convênio de cobrança do cedente',
    canonical: null,
  },
  codigo_controle_empresa: {
    pos: [39, 63],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de controle do participante (uso da empresa)',
    canonical: null,
  },
  nosso_numero: {
    pos: [64, 80],
    type: FieldType.NUM,
    size: 17,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título no banco (nosso número)',
    canonical: 'nossoNumero',
  },
  numero_prestacao: {
    pos: [81, 82],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Número da prestação (00 se parcela única)',
    canonical: null,
  },
  grupo_valor: {
    pos: [83, 84],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Grupo de valor (00 se não utilizado)',
    canonical: null,
  },
  tipo_moeda: {
    pos: [85, 86],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de moeda (revelado no manual 2024)',
    canonical: null,
  },
  brancos_1: {
    pos: [87, 87],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos',
    canonical: null,
  },
  indicativo_mensagem_sacador: {
    pos: [88, 88],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indicativo de mensagem ou beneficiário final',
    canonical: null,
  },
  prefixo_titulo: {
    pos: [89, 91],
    type: FieldType.ALFA,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo do título (brancos)',
    canonical: null,
  },
  variacao_carteira: {
    pos: [92, 94],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Variação da carteira',
    canonical: null,
  },
  conta_caucao: {
    pos: [95, 95],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Conta caução: 0=Não, outros=Sim',
    canonical: null,
  },
  numero_bordero: {
    pos: [96, 101],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000000',
    description: 'Número do borderô (000000 se não utilizado)',
    canonical: null,
  },
  tipo_cobranca: {
    pos: [102, 106],
    type: FieldType.ALFA,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de cobrança',
    canonical: null,
  },
  numero_carteira: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da carteira',
    canonical: null,
  },
  comando: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código de ocorrência/comando (01=Entrada de título, 02=Pedido de baixa, 04=Concessão de abatimento, 06=Alteração de Vencimento)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento de cobrança (seu número)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento do título',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título (2 decimais implícitas)',
    canonical: 'valor',
  },
  codigo_banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '001',
    description: 'Código do banco cobrador (001 para BB)',
    canonical: null,
  },
  prefixo_agencia_cobradora: {
    pos: [143, 146],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0000',
    description: 'Prefixo da agência cobradora',
    canonical: null,
  },
  dv_agencia_cobradora: {
    pos: [147, 147],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito da agência cobradora (brancos)',
    canonical: null,
  },
  especie: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Espécie do título (NOTA 07)',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Identificação de título aceito/não aceito',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emissão do título',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Primeira instrução de cobrança',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Segunda instrução de cobrança',
    canonical: null,
  },
  juros_mora_dia: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Juros de mora por dia de atraso',
    canonical: null,
  },
  desconto_ate: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concessão de desconto',
    canonical: null,
  },
  valor_desconto: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do desconto a ser concedido',
    canonical: 'desconto.valor',
  },
  valor_iof: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a ser recolhido',
    canonical: null,
  },
  abatimento: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento a ser concedido',
    canonical: null,
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição do sacado: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do sacado',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 271],
    type: FieldType.ALFA,
    size: 37,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description:
      'Nome do sacado (37 chars no BB — padrão FEBRABAN são 40, mas BB usa 37 + 3 brancos)',
    canonical: 'sacado.nome',
  },
  brancos_2: {
    pos: [272, 274],
    type: FieldType.ALFA,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos (complemento do campo nome - BB usa 37+3 em vez de 40 contínuos)',
    canonical: null,
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do sacado',
    canonical: 'sacado.endereco.logradouro',
  },
  bairro: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Bairro do sacado',
    canonical: 'sacado.endereco.bairro',
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do sacado (8 dígitos sem hífen)',
    canonical: 'sacado.endereco.cep',
  },
  cidade: {
    pos: [335, 349],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Cidade do sacado',
    canonical: 'sacado.endereco.cidade',
  },
  estado: {
    pos: [350, 351],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'UF do sacado (2 letras)',
    canonical: 'sacado.endereco.estado',
  },
  sacador_avalista: {
    pos: [352, 391],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficiário final ou observações (nomenclatura atualizada conforme Circulares BACEN 3598, 3656 e 3956)',
    canonical: null,
  },
  prazo_protesto: {
    pos: [392, 393],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Prazo para protesto em dias',
    canonical: null,
  },
  indicador_recebimento_parcial: {
    pos: [394, 394],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      "Indicador de recebimento parcial: 'N'=não aceita, 'S'=aceita, branco=conforme cadastro no sistema (revelado no manual 2024)",
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no arquivo',
    canonical: null,
  },
}
