/**
 * Banco do Brasil (001) — CNAB 400 — Header de Arquivo (Remessa)
 * Fonte:
 * - Manual oficial BB remessa (Doc2627CBR641Pos7.pdf, abril/2012) — §3 p.4
 * - brcobranca (remessa/cnab400/banco_brasil.rb)
 * - cnab_yaml (cnab400/001/remessa/header_arquivo.yml)
 * - laravel-boleto (Cnab/Remessa/Cnab400/Banco/Bb.php)
 * Todas as fontes concordam byte a byte.
 *
 * Atenção: campo "numero_sequencial" aparece em DUAS posições diferentes:
 * - 101-107: sequencial da remessa (controle do cliente)
 * - 395-400: sequencial do registro (sempre '000001' no header)
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const HEADER: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificação do registro header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operação: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal identificando arquivo de remessa',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Código do serviço: 01=Cobrança',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal do tipo de serviço',
    canonical: null,
  },
  agencia: {
    pos: [27, 30],
    type: FieldType.NUM,
    size: 4,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Prefixo da agência do cedente',
    canonical: null,
  },
  agencia_dv: {
    pos: [31, 31],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência',
    canonical: null,
  },
  conta: {
    pos: [32, 39],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número da conta corrente',
    canonical: null,
  },
  conta_dv: {
    pos: [40, 40],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta',
    canonical: null,
  },
  zeros: {
    pos: [41, 46],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000000',
    description: 'Zeros (preenchimento)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Razão social do cedente',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '001',
    description: 'Código FEBRABAN do Banco do Brasil',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BANCODOBRASIL',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de geração do arquivo',
    canonical: 'dataGeracao',
  },
  sequencial_remessa: {
    pos: [101, 107],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0000001',
    description: 'Número sequencial da remessa (controle do cliente)',
    canonical: null,
  },
  brancos_1: {
    pos: [108, 129],
    type: FieldType.ALFA,
    size: 22,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos',
    canonical: null,
  },
  convenio_lider: {
    pos: [130, 136],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0000000',
    description: 'Número do convênio líder',
    canonical: null,
  },
  brancos_2: {
    pos: [137, 394],
    type: FieldType.ALFA,
    size: 258,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Brancos',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Número sequencial do registro no arquivo (sempre 000001 no header)',
    canonical: null,
  },
}
