/**
 * Caixa Econômica Federal (104) — CNAB 400 — Registro Tipo 4 (Tipo de Pagamento e Rateio)
 *
 * O mais complexo dos três registros opcionais da Caixa: combina duas finalidades num
 * único registro:
 * 1. Definição de regras de pagamento com valor flexível (posições 57-139) — permite
 *    configurar se o título aceita pagamento em valor diferente do nominal, dentro de
 *    uma faixa mínima/máxima (expressa em valor monetário ou percentual).
 * 2. Rateio de crédito entre beneficiários (posições 183-289) — embutido no mesmo
 *    registro, diferente do padrão dos outros bancos (que usam registro separado).
 *
 * Fonte:
 * - Manual oficial Caixa (caixa_layout_CNAB_400_2024.pdf, 2024)
 *
 * REGISTRO NÃO CONFIRMADO POR TERCEIROS: laravel-boleto não implementa este registro.
 * Todas as posições vêm exclusivamente do manual oficial de 2024.
 *
 * PARTICULARIDADES E INCERTEZAS:
 * - codigo_registro='4' é INFERIDO do contexto, não confirmado explicitamente pela
 *   tabela do manual. Vale confirmar contra um arquivo real.
 * - codigo_calculo_rateio (pos 183) e tipo_valor_informado_rateio (pos 184): o manual
 *   mostra códigos 2 e 3 como "0 0 (000)" em vez de dígitos únicos — provável artefato
 *   de célula vazia na extração do PDF, NÃO CONFIRMADO. Os valores prováveis (por
 *   analogia com outros bancos) são '1'/'2'/'3' para cálculo e '1'/'2' para tipo de
 *   valor, mas isso NÃO está confirmado pelo manual.
 * - nome_beneficiario (pos 223-262) aparece com picture 9(040) (numérico) no manual —
 *   quase certamente erro do PDF, já que é campo de nome; implementado como alfa por
 *   analogia com outros bancos.
 * - uso_exclusivo_4: o manual mostra posições 289-394, que sobrepõe 1 byte com o campo
 *   anterior (motivo_ocorrido, que termina em 289). Corrigido aqui para 290-394 (105
 *   bytes) — essa é a faixa que fecha a soma total em exatos 400 bytes.
 */

import { RecordSchema } from '../../../../../../types'

export const TYPE4_PAYMENT_ALLOCATION: RecordSchema = {
  codigo_registro: {
    pos: [1, 1],
    type: 'num',
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '4',
    description:
      'Identificação do registro tipo 4 (inferido do contexto — ver comentário no cabeçalho)',
    canonical: null,
  },
  tipo_inscricao_empresa: {
    pos: [2, 3],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição da empresa: 1=CPF, 2=CNPJ',
    canonical: null,
  },
  numero_inscricao_empresa: {
    pos: [4, 17],
    type: 'num',
    size: 14,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de inscrição da empresa (CPF/CNPJ do beneficiário)',
    canonical: null,
  },
  codigo_agencia: {
    pos: [18, 21],
    type: 'num',
    size: 4,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Código da agência de vinculação do beneficiário',
    canonical: null,
  },
  codigo_beneficiario: {
    pos: [22, 28],
    type: 'num',
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da empresa na CAIXA',
    canonical: null,
  },
  uso_exclusivo_1: {
    pos: [29, 31],
    type: 'alfa',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CAIXA',
    canonical: null,
  },
  brancos_1: {
    pos: [32, 56],
    type: 'alfa',
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Em branco',
    canonical: null,
  },
  codigo_registro_opcional: {
    pos: [57, 58],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Identificação do registro opcional (NE042 — não totalmente esclarecido na extração)',
    canonical: null,
  },
  tipo_pagamento: {
    pos: [59, 60],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do tipo de pagamento (NE043)',
    canonical: null,
  },
  quantidade_pagamentos_possiveis: {
    pos: [61, 62],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de pagamentos possíveis (NE044)',
    canonical: null,
  },
  valor_nominal_titulo: {
    pos: [63, 77],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Alteração do valor nominal do título',
    canonical: null,
  },
  tipo_valor_maximo: {
    pos: [78, 78],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor informado — valor ou percentual (NE045)',
    canonical: null,
  },
  valor_maximo: {
    pos: [79, 93],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor máximo aceito',
    canonical: null,
  },
  percentual_maximo: {
    pos: [94, 108],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual máximo aceito',
    canonical: null,
  },
  tipo_valor_minimo: {
    pos: [109, 109],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de valor informado — valor ou percentual (NE045)',
    canonical: null,
  },
  valor_minimo: {
    pos: [110, 124],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor mínimo aceito',
    canonical: null,
  },
  percentual_minimo: {
    pos: [125, 139],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual mínimo aceito',
    canonical: null,
  },
  uso_exclusivo_2: {
    pos: [140, 142],
    type: 'alfa',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CAIXA',
    canonical: null,
  },
  agencia_credito_beneficiario: {
    pos: [143, 147],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência mantenedora da conta de crédito do beneficiário (NE048)',
    canonical: null,
  },
  dv_agencia_credito: {
    pos: [148, 148],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência (NE049)',
    canonical: null,
  },
  conta_credito_beneficiario: {
    pos: [149, 160],
    type: 'num',
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente de crédito do beneficiário (NE050)',
    canonical: null,
  },
  dv_conta_credito: {
    pos: [161, 161],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta (NE051)',
    canonical: null,
  },
  dv_agencia_conta: {
    pos: [162, 162],
    type: 'alfa',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência/conta combinada (NE052)',
    canonical: null,
  },
  nosso_numero_modalidade: {
    pos: [163, 164],
    type: 'num',
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Modalidade: 11=emissão CAIXA, 14=emissão beneficiário (NE015)',
    canonical: null,
  },
  nosso_numero: {
    pos: [165, 179],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação do título na CAIXA (NE015)',
    canonical: null,
  },
  uso_exclusivo_3: {
    pos: [180, 182],
    type: 'alfa',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Uso exclusivo CAIXA',
    canonical: null,
  },
  codigo_calculo_rateio: {
    pos: [183, 183],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Código do cálculo de rateio — INCERTEZA: manual mostra "0 0 (000)", provável artefato de extração. Valores prováveis (não confirmados): 1=valor cobrado, 2=valor do registro, 3=rateio pelo menor valor',
    canonical: null,
  },
  tipo_valor_informado_rateio: {
    pos: [184, 184],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Tipo de valor informado para rateio — INCERTEZA: manual mostra "0 0 (000)", provável artefato de extração. Valores prováveis (não confirmados): 1=percentual, 2=valor/quantidade',
    canonical: null,
  },
  valor_ou_percentual_rateio: {
    pos: [185, 199],
    type: 'num',
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Valor/percentual do título ou quantidade de moedas para rateio (NE053)',
    canonical: null,
  },
  codigo_banco_credito: {
    pos: [200, 202],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Banco para crédito do beneficiário do rateio',
    canonical: null,
  },
  agencia_credito: {
    pos: [203, 207],
    type: 'num',
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência para crédito do beneficiário do rateio (NE048)',
    canonical: null,
  },
  dv_agencia_credito_2: {
    pos: [208, 208],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência (NE049)',
    canonical: null,
  },
  conta_credito: {
    pos: [209, 220],
    type: 'num',
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente para crédito do beneficiário do rateio (NE050)',
    canonical: null,
  },
  dv_conta_credito_2: {
    pos: [221, 221],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta (NE051)',
    canonical: null,
  },
  dv_agencia_conta_2: {
    pos: [222, 222],
    type: 'num',
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência/conta combinada (NE052)',
    canonical: null,
  },
  nome_beneficiario: {
    pos: [223, 262],
    type: 'alfa',
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Nome do beneficiário do rateio — manual mostra picture 9(040) (numérico), quase certamente erro do PDF; implementado como alfa por analogia com outros bancos',
    canonical: null,
  },
  parcela: {
    pos: [263, 268],
    type: 'num',
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação da parcela do rateio',
    canonical: null,
  },
  floating: {
    pos: [269, 271],
    type: 'num',
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de dias para crédito do beneficiário',
    canonical: null,
  },
  data_credito: {
    pos: [272, 279],
    type: 'num',
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Data de crédito do beneficiário do rateio',
    canonical: null,
  },
  motivo_ocorrido: {
    pos: [280, 289],
    type: 'num',
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Identificação das rejeições (NE054)',
    canonical: null,
  },
  uso_exclusivo_4: {
    pos: [290, 394],
    type: 'alfa',
    size: 105,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description:
      'Uso exclusivo CAIXA — posição corrigida para 290-394 (manual mostra 289-394, que sobrepõe 1 byte com campo anterior)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: 'num',
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro no arquivo',
    canonical: null,
  },
}
