/**
 * Contém dados financeiros do título e informações do sacado.
 * 
 * Fontes:
 * - brcobranca (Ruby) — remessa/cnab400/bradesco.rb
 * - cnab_yaml (YAML) — cnab400/237/remessa/detalhe.yml
 * - Manual "Layout de Cobrança CNAB 400 — versão em português" (27/07/2017)
 * - Manual "Layout de Cobrança CNAB 400 - Padrão 400 posições" (2022) — 
 *   revelou 2 campos nas posições 105 e 107-108
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB400_DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro: 1=Detalhe',
    canonical: null,
  },
  agencia_debito: {
    pos: [2, 6],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia de d�bito autom�tico (se aplic�vel)',
    canonical: null,
  },
  agencia_debito_dv: {
    pos: [7, 7],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da ag�ncia de d�bito',
    canonical: null,
  },
  razao_conta_corrente: {
    pos: [8, 12],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Raz�o da conta corrente',
    canonical: null,
  },
  conta_corrente: {
    pos: [13, 19],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente',
    canonical: null,
  },
  conta_corrente_dv: {
    pos: [20, 20],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta corrente',
    canonical: null,
  },
  zeros_1: {
    pos: [21, 21],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Zero fixo',
    canonical: null,
  },
  carteira_codigo: {
    pos: [22, 24],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da carteira (ex: 109)',
    canonical: null,
  },
  agencia_cedente: {
    pos: [25, 29],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia do cedente',
    canonical: null,
  },
  conta_cedente: {
    pos: [30, 36],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta do cedente',
    canonical: null,
  },
  conta_cedente_dv: {
    pos: [37, 37],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador da conta do cedente',
    canonical: null,
  },
  numero_controle_empresa: {
    pos: [38, 62],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero de controle do participante (uso da empresa)',
    canonical: null,
  },
  codigo_banco: {
    pos: [63, 65],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    // Campo condicional (manual 2022, "Das Posi��es", 063 a 065): '237' quando o
    // pagador optou por D�bito Autom�tico em conta, '000' quando n�o. N�o � um valor
    // fixo � n�o deve travar em '000' via padrao, sen�o remessas reais com d�bito
    // autom�tico habilitado ('237') seriam rejeitadas como erro de valida��o.
    pattern: null,
    description:
      "C�digo do banco para d�bito autom�tico: '237' se d�bito autom�tico em conta contratado, '000' caso contr�rio",
    canonical: null,
  },
  multa_indicador: {
    pos: [66, 66],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Indicador de multa: 0=Sem multa, 2=Com multa',
    canonical: null,
  },
  multa_percentual: {
    pos: [67, 70],
    type: FieldType.NUM,
    size: 4,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual de multa (2 decimais impl�citas)',
    canonical: null,
  },
  nosso_numero: {
    pos: [71, 81],
    type: FieldType.NUM,
    size: 11,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso n�mero (11 d�gitos)',
    canonical: 'nossoNumero',
  },
  nosso_numero_dv: {
    pos: [82, 82],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'D�gito verificador do nosso n�mero',
    canonical: null,
  },
  desconto_bonificacao: {
    pos: [83, 92],
    type: FieldType.NUM,
    size: 10,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Desconto bonifica��o por dia',
    canonical: null,
  },
  condicao_emissao: {
    pos: [93, 93],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '2',
    description: 'Emiss�o do boleto: 1=Banco, 2=Cliente',
    canonical: null,
  },
  identificacao_debito: {
    pos: [94, 94],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'N',
    description: 'Identifica��o de d�bito autom�tico: N=N�o',
    canonical: null,
  },
  brancos_1: {
    pos: [95, 104],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco / uso do banco',
    canonical: null,
  },
  indicador_rateio_credito: {
    pos: [105, 105],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indicador de rateio de cr�dito: "R"=contratado servi�o de rateio, branco=sem rateio (revelado no manual 2022, documentado em tipo3-rateio-credito.md)',
    canonical: null,
  },
  indicador_endereco_debito: {
    pos: [106, 106],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '2',
    description: 'Endere�o para aviso de d�bito: 2=Ignora',
    canonical: null,
  },
  quantidade_pagamentos: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de pagamentos (revelado no manual 2022)',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    // N�o � um valor fixo: varia por t�tulo (01=Entrada de t�tulo, 02=Pedido de baixa,
    // 04=Concess�o de abatimento, 06=Altera��o de vencimento � ver manual para lista completa).
    // Um arquivo real legitimamente mistura esses c�digos entre os detalhes.
    pattern: null,
    description: 'C�digo de ocorr�ncia (01=Entrada, 02=Pedido de baixa, 04=Concess�o de abatimento, 06=Altera��o de vencimento, etc.)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do documento (seu n�mero)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento do t�tulo',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do t�tulo (2 decimais impl�citas)',
    canonical: 'valor',
  },
  banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000',
    description: 'C�digo do banco cobrador (000=Bradesco)',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Ag�ncia cobradora',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Esp�cie do t�tulo: 01=Duplicata, 02=Nota promiss�ria, etc.',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Aceite: A=Aceite, N=N�o aceite',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emiss�o do t�tulo',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Primeira instru��o de cobran�a',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Segunda instru��o de cobran�a',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor de juros de mora por dia de atraso (2 decimais impl�citas)',
    canonical: null,
  },
  desconto_data_limite: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concess�o de desconto',
    canonical: null,
  },
  desconto_valor: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do desconto',
    canonical: 'desconto.valor',
  },
  iof_valor: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a ser recolhido',
    canonical: null,
  },
  abatimento_valor: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscri��o: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do sacado (pagador)',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do sacado',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endere�o do sacado',
    canonical: 'sacado.endereco.logradouro',
  },
  brancos_3: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco / 1� mensagem',
    canonical: null,
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do sacado',
    canonical: 'sacado.endereco.cep',
  },
  sacador_avalista: {
    pos: [335, 394],
    type: FieldType.ALFA,
    size: 60,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do benefici�rio final ou 2� mensagem de cobran�a (nomenclatura atualizada conforme Circulares BACEN 3598, 3656 e 3956)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial do registro',
    canonical: null,
  },
}
