/**
 * Contém dados financeiros do título e informações do sacado.
 * 
 * Fontes:
 * - brcobranca (Ruby) — remessa/cnab400/bradesco.rb
 * - cnab_yaml (YAML) — cnab400/237/remessa/detalhe.yml
 * - Manual "Layout de Cobrança CNAB 400 — versão em português" (27/07/2017)
 * - Manual "Layout de Cobrança CNAB 400 - Padrão 400 posições" (2022) — 
 *   revelou 2 campos nas posições 105 e 107-108
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const BRADESCO_CNAB400_DETAIL: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo do registro: 1=Detalhe',
    canonical: null,
  },
  agencia_debito: {
    pos: [2, 6],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência de débito automático (se aplicável)',
    canonical: null,
  },
  agencia_debito_dv: {
    pos: [7, 7],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da agência de débito',
    canonical: null,
  },
  razao_conta_corrente: {
    pos: [8, 12],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Razão da conta corrente',
    canonical: null,
  },
  conta_corrente: {
    pos: [13, 19],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Conta corrente',
    canonical: null,
  },
  conta_corrente_dv: {
    pos: [20, 20],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta corrente',
    canonical: null,
  },
  zeros_1: {
    pos: [21, 21],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Zero fixo',
    canonical: null,
  },
  carteira_codigo: {
    pos: [22, 24],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da carteira (ex: 109)',
    canonical: null,
  },
  agencia_cedente: {
    pos: [25, 29],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Agência do cedente',
    canonical: null,
  },
  conta_cedente: {
    pos: [30, 36],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Conta do cedente',
    canonical: null,
  },
  conta_cedente_dv: {
    pos: [37, 37],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador da conta do cedente',
    canonical: null,
  },
  numero_controle_empresa: {
    pos: [38, 62],
    type: FieldType.ALFA,
    size: 25,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número de controle do participante (uso da empresa)',
    canonical: null,
  },
  codigo_banco: {
    pos: [63, 65],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    // Campo condicional (manual 2022, "Das Posições", 063 a 065): '237' quando o
    // pagador optou por Débito Automático em conta, '000' quando não. Não é um valor
    // fixo é não deve travar em '000' via padrao, senão remessas reais com débito
    // automático habilitado ('237') seriam rejeitadas como erro de validação.
    pattern: null,
    description:
      "Código do banco para débito automático: '237' se débito automático em conta contratado, '000' caso contrário",
    canonical: null,
  },
  multa_indicador: {
    pos: [66, 66],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '0',
    description: 'Indicador de multa: 0=Sem multa, 2=Com multa',
    canonical: null,
  },
  multa_percentual: {
    pos: [67, 70],
    type: FieldType.NUM,
    size: 4,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Percentual de multa (2 decimais implícitas)',
    canonical: null,
  },
  nosso_numero: {
    pos: [71, 81],
    type: FieldType.NUM,
    size: 11,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nosso número (11 dígitos)',
    canonical: 'nossoNumero',
  },
  nosso_numero_dv: {
    pos: [82, 82],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Dígito verificador do nosso número',
    canonical: null,
  },
  desconto_bonificacao: {
    pos: [83, 92],
    type: FieldType.NUM,
    size: 10,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Desconto bonificação por dia',
    canonical: null,
  },
  condicao_emissao: {
    pos: [93, 93],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '2',
    description: 'Emissão do boleto: 1=Banco, 2=Cliente',
    canonical: null,
  },
  identificacao_debito: {
    pos: [94, 94],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'N',
    description: 'Identificação de débito automático: N=Não',
    canonical: null,
  },
  brancos_1: {
    pos: [95, 104],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco / uso do banco',
    canonical: null,
  },
  indicador_rateio_credito: {
    pos: [105, 105],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Indicador de rateio de crédito: "R"=contratado serviço de rateio, branco=sem rateio (revelado no manual 2022, documentado em tipo3-rateio-credito.md)',
    canonical: null,
  },
  indicador_endereco_debito: {
    pos: [106, 106],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '2',
    description: 'Endereço para aviso de débito: 2=Ignora',
    canonical: null,
  },
  quantidade_pagamentos: {
    pos: [107, 108],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Quantidade de pagamentos (revelado no manual 2022)',
    canonical: null,
  },
  codigo_ocorrencia: {
    pos: [109, 110],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    // Não é um valor fixo: varia por título (01=Entrada de título, 02=Pedido de baixa,
    // 04=Concessão de abatimento, 06=Alteração de vencimento é ver manual para lista completa).
    // Um arquivo real legitimamente mistura esses códigos entre os detalhes.
    pattern: null,
    description: 'Código de ocorrência (01=Entrada, 02=Pedido de baixa, 04=Concessão de abatimento, 06=Alteração de vencimento, etc.)',
    canonical: null,
  },
  numero_documento: {
    pos: [111, 120],
    type: FieldType.ALFA,
    size: 10,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número do documento (seu número)',
    canonical: 'numeroDocumento',
  },
  vencimento: {
    pos: [121, 126],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de vencimento do título',
    canonical: 'vencimento',
  },
  valor_titulo: {
    pos: [127, 139],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Valor do título (2 decimais implícitas)',
    canonical: 'valor',
  },
  banco_cobrador: {
    pos: [140, 142],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '000',
    description: 'Código do banco cobrador (000=Bradesco)',
    canonical: null,
  },
  agencia_cobradora: {
    pos: [143, 147],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Agência cobradora',
    canonical: null,
  },
  especie_titulo: {
    pos: [148, 149],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Espécie do título: 01=Duplicata, 02=Nota promissária, etc.',
    canonical: null,
  },
  aceite: {
    pos: [150, 150],
    type: FieldType.ALFA,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'N',
    description: 'Aceite: A=Aceite, N=Não aceite',
    canonical: null,
  },
  data_emissao: {
    pos: [151, 156],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de emissão do título',
    canonical: 'dataEmissao',
  },
  instrucao_1: {
    pos: [157, 158],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Primeira instrução de cobrança',
    canonical: null,
  },
  instrucao_2: {
    pos: [159, 160],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '00',
    description: 'Segunda instrução de cobrança',
    canonical: null,
  },
  juros_mora: {
    pos: [161, 173],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor de juros de mora por dia de atraso (2 decimais implícitas)',
    canonical: null,
  },
  desconto_data_limite: {
    pos: [174, 179],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data limite para concessão de desconto',
    canonical: null,
  },
  desconto_valor: {
    pos: [180, 192],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do desconto',
    canonical: 'desconto.valor',
  },
  iof_valor: {
    pos: [193, 205],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do IOF a ser recolhido',
    canonical: null,
  },
  abatimento_valor: {
    pos: [206, 218],
    type: FieldType.NUM,
    size: 13,
    decimals: 2,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Valor do abatimento',
    canonical: 'abatimento.valor',
  },
  sacado_codigo_inscricao: {
    pos: [219, 220],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Tipo de inscrição: 01=CPF, 02=CNPJ',
    canonical: null,
  },
  sacado_numero_inscricao: {
    pos: [221, 234],
    type: FieldType.NUM,
    size: 14,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'CPF ou CNPJ do sacado (pagador)',
    canonical: 'sacado.documento',
  },
  nome: {
    pos: [235, 274],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Nome do sacado',
    canonical: 'sacado.nome',
  },
  logradouro: {
    pos: [275, 314],
    type: FieldType.ALFA,
    size: 40,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Endereço do sacado',
    canonical: 'sacado.endereco.logradouro',
  },
  brancos_3: {
    pos: [315, 326],
    type: FieldType.ALFA,
    size: 12,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco / 1ª mensagem',
    canonical: null,
  },
  cep: {
    pos: [327, 334],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'CEP do sacado',
    canonical: 'sacado.endereco.cep',
  },
  sacador_avalista: {
    pos: [335, 394],
    type: FieldType.ALFA,
    size: 60,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Nome do beneficiário final ou 2ª mensagem de cobrança (nomenclatura atualizada conforme Circulares BACEN 3598, 3656 e 3956)',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial do registro',
    canonical: null,
  },
}
