/* *
 * Primeira linha do arquivo CNAB 400. Cont�m identifica��o do banco,
 * dados do cedente e informa��es sobre o arquivo.
 * 
 * Baseado em:
 * - Manual "Layout de Cobran�a CNAB 400 � vers�o em portugu�s" (27/07/2017)
 * - brcobranca, cnab_yaml, laravel-boleto
 */

import { RecordSchema, DateFormat , FieldType } from '@tp-types/index'

export const BRADESCO_CNAB400_HEADER_REMESSA: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identifica��o do registro: 0=Header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de opera��o: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'C�digo de servi�o: 01=Cobran�a',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal COBRANCA (com espa�os � direita)',
    canonical: null,
  },
  codigo_cedente: {
    pos: [27, 46],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da empresa no banco (20 posi��es)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Raz�o social do cedente',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BRADESCO',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de gera��o do arquivo',
    canonical: 'dataGeracao',
  },
  brancos_1: {
    pos: [101, 108],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  identificacao_sistema: {
    pos: [109, 110],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'MX',
    description: 'Identifica��o do sistema: MX (fixo)',
    canonical: null,
  },
  sequencial_remessa: {
    pos: [111, 117],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'N�mero sequencial da remessa',
    canonical: null,
  },
  brancos_2: {
    pos: [118, 394],
    type: FieldType.ALFA,
    size: 277,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'N�mero sequencial do registro (sempre 000001 no header)',
    canonical: null,
  },
}

export const BRADESCO_CNAB400_HEADER_RETORNO: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identifica��o do registro: 0=Header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '2',
    description: 'Tipo de opera��o: 2=Retorno',
    canonical: null,
  },
  literal_retorno: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'RETORNO',
    description: 'Literal RETORNO',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'C�digo de servi�o: 01=Cobran�a',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal COBRANCA (com espa�os � direita)',
    canonical: null,
  },
  codigo_cedente: {
    pos: [27, 46],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'C�digo da empresa no banco (20 posi��es)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Raz�o social do cedente',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'C�digo FEBRABAN do Bradesco',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BRADESCO',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de gera��o do arquivo de retorno',
    canonical: 'dataGeracao',
  },
  densidade_gravacao: {
    pos: [101, 108],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '01600000',
    description: 'Densidade de grava��o (campo legado)',
    canonical: null,
  },
  numero_aviso_bancario: {
    pos: [109, 113],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'N�mero do aviso banc�rio (5 d�gitos no retorno)',
    canonical: null,
  },
  brancos: {
    pos: [114, 379],
    type: FieldType.ALFA,
    size: 266,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  data_credito: {
    pos: [380, 385],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de cr�dito dos valores',
    canonical: null,
  },
  brancos_2: {
    pos: [386, 394],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espa�os em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'N�mero sequencial do registro (sempre 000001 no header)',
    canonical: null,
  },
}
