/* *
 * Primeira linha do arquivo CNAB 400. Contém identificação do banco,
 * dados do cedente e informações sobre o arquivo.
 * 
 * Baseado em:
 * - Manual "Layout de Cobrança CNAB 400 é versão em português" (27/07/2017)
 * - brcobranca, cnab_yaml, laravel-boleto
 */

import { RecordSchema, DateFormat , FieldType } from '@/types/all-types'

export const BRADESCO_CNAB400_HEADER_REMESSA: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificação do registro: 0=Header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '1',
    description: 'Tipo de operação: 1=Remessa',
    canonical: null,
  },
  literal_remessa: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'REMESSA',
    description: 'Literal REMESSA',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Código de serviço: 01=Cobrança',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal COBRANCA (com espaços é direita)',
    canonical: null,
  },
  codigo_cedente: {
    pos: [27, 46],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da empresa no banco (20 posições)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Razão social do cedente',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BRADESCO',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de geração do arquivo',
    canonical: 'dataGeracao',
  },
  brancos_1: {
    pos: [101, 108],
    type: FieldType.ALFA,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  identificacao_sistema: {
    pos: [109, 110],
    type: FieldType.ALFA,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'MX',
    description: 'Identificação do sistema: MX (fixo)',
    canonical: null,
  },
  sequencial_remessa: {
    pos: [111, 117],
    type: FieldType.NUM,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Número sequencial da remessa',
    canonical: null,
  },
  brancos_2: {
    pos: [118, 394],
    type: FieldType.ALFA,
    size: 277,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Número sequencial do registro (sempre 000001 no header)',
    canonical: null,
  },
}

export const BRADESCO_CNAB400_HEADER_RETORNO: RecordSchema = {
  tipo_registro: {
    pos: [1, 1],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '0',
    description: 'Identificação do registro: 0=Header',
    canonical: null,
  },
  tipo_operacao: {
    pos: [2, 2],
    type: FieldType.NUM,
    size: 1,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '2',
    description: 'Tipo de operação: 2=Retorno',
    canonical: null,
  },
  literal_retorno: {
    pos: [3, 9],
    type: FieldType.ALFA,
    size: 7,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'RETORNO',
    description: 'Literal RETORNO',
    canonical: null,
  },
  codigo_servico: {
    pos: [10, 11],
    type: FieldType.NUM,
    size: 2,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '01',
    description: 'Código de serviço: 01=Cobrança',
    canonical: null,
  },
  literal_servico: {
    pos: [12, 26],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: 'COBRANCA',
    description: 'Literal COBRANCA (com espaços é direita)',
    canonical: null,
  },
  codigo_cedente: {
    pos: [27, 46],
    type: FieldType.ALFA,
    size: 20,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Código da empresa no banco (20 posições)',
    canonical: null,
  },
  nome_empresa: {
    pos: [47, 76],
    type: FieldType.ALFA,
    size: 30,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: null,
    description: 'Razão social do cedente',
    canonical: 'cedente.nome',
  },
  codigo_banco: {
    pos: [77, 79],
    type: FieldType.NUM,
    size: 3,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '237',
    description: 'Código FEBRABAN do Bradesco',
    canonical: null,
  },
  nome_banco: {
    pos: [80, 94],
    type: FieldType.ALFA,
    size: 15,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: 'BRADESCO',
    description: 'Nome do banco',
    canonical: null,
  },
  data_geracao: {
    pos: [95, 100],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de geração do arquivo de retorno',
    canonical: 'dataGeracao',
  },
  densidade_gravacao: {
    pos: [101, 108],
    type: FieldType.NUM,
    size: 8,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: '01600000',
    description: 'Densidade de gravação (campo legado)',
    canonical: null,
  },
  numero_aviso_bancario: {
    pos: [109, 113],
    type: FieldType.NUM,
    size: 5,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Número do aviso bancário (5 dígitos no retorno)',
    canonical: null,
  },
  brancos: {
    pos: [114, 379],
    type: FieldType.ALFA,
    size: 266,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  data_credito: {
    pos: [380, 385],
    type: FieldType.DATA,
    size: 6,
    decimals: 0,
    required: false,
    dateFormat: DateFormat.DDMMAA,
    pattern: null,
    description: 'Data de crédito dos valores',
    canonical: null,
  },
  brancos_2: {
    pos: [386, 394],
    type: FieldType.ALFA,
    size: 9,
    decimals: 0,
    required: false,
    dateFormat: null,
    pattern: null,
    description: 'Espaços em branco',
    canonical: null,
  },
  numero_sequencial: {
    pos: [395, 400],
    type: FieldType.NUM,
    size: 6,
    decimals: 0,
    required: true,
    dateFormat: null,
    pattern: '000001',
    description: 'Número sequencial do registro (sempre 000001 no header)',
    canonical: null,
  },
}
