export { Cnab240BradescoBoletoNomeField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-nome-field'
export { Cnab240BradescoBoletoValorTituloField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-valor-titulo-field'
export { Cnab240BradescoBoletoVencimentoField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-vencimento-field'
export { Cnab240BradescoBoletoSacadoDocumentoField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-sacado-documento-field'
export { Cnab240BradescoBoletoEnderecoField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-endereco-field'
export { Cnab240BradescoBoletoBairroField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-bairro-field'
export { Cnab240BradescoBoletoCepField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-cep-field'
export { Cnab240BradescoBoletoCepSufixoField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-cep-sufixo-field'
export { Cnab240BradescoBoletoCidadeField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-cidade-field'
export { Cnab240BradescoBoletoUfField } from '@cnab/bank/bradesco/cnab/cnab240/field/cnab240-bradesco-boleto-uf-field'

